# -*- coding: utf-8 -*-
"""Volume 2: 兩漢魏晉史傳與風骨雄文 (Rounds 8-14, 35 works)"""

vol2_items = [
    # Round 8: 史記名篇
    (8, "v2", "r08_01_shiji_zixu", "《史記·太史公自序》", "Sử Ký - Thái Sử Công Tự Tự", "Records of the Grand Historian: Author's Preface", "司馬遷", "Tư Mã Thiên", "西漢", "Tây Hán",
     "昔西伯拘羑里，演《周易》；孔子厄陳蔡，作《春秋》；屈原放逐，著《離騷》；左丘失明，厥有《國語》；孫子臏腳，論兵法；韓非囚秦，《說難》、《孤憤》；《詩》三百篇，大抵聖賢發憤之所為作也。余述歷代，究天人之際，通古今之變，成一家之言。",
     "自古聖賢皆因受挫發憤著書。司馬遷歷述周文王、孔子、屈原、左丘明、孫臏、韓非發憤著述之大志，發願究天人之際、通古今之變、成一家之言著成《史記》。",
     "Ancient sages produced immortal writings in adversity. I sought to examine the boundaries of Heaven and man, comprehend the changes of past and present, and achieve a work of an independent school.",
     "司馬遷「發憤著書」說與「究天人之際、通古今之變、成一家之言」之史家宏願，奠定中國紀傳體史學與崇高人格典範。",
     "【漢越音考證】史 (Sử), 遷 (Thiên), 序 (Tự), 究 (Cứu), 際 (Tế), 變 (Biến), 憤 (Phẫn).",
     [{"viet": "Cứu thiên nhân chi tế, thông cổ kim chi biến, thành nhất gia chi ngôn.", "zh": "究天人之際，通古今之變，成一家之言。", "en": "Examine the boundary between Heaven and man, comprehend changes of past and present, and form an independent school of thought.", "hanViet": "Cứu thiên nhân chi tế"}]),

    (8, "v2", "r08_02_shiji_hongmenyan", "《史記·項羽本紀·鴻門宴》", "Sử Ký - Hạng Vũ Bản Kỷ - Hồng Môn Yến", "Records of the Grand Historian: Feast at Hong Gate", "司馬遷", "Tư Mã Thiên", "西漢", "Tây Hán",
     "項莊拔劍起舞，項伯亦拔劍起舞，常以身翼蔽沛公，莊不得擊。樊噲側其盾以撞，衛士仆地，入立，目眥盡裂，頭髮上指。沛公如廁，因招樊噲出。樊噲曰：「大行不顧細謹，大禮不辭小讓。如今人方為刀俎，我為魚肉，何辭為？」遂脫歸。",
     "鴻門宴上項莊舞劍意在沛公，樊噲闖帳救駕目眥盡裂。樊噲進言「大行不顧細謹，如今人為刀俎我為魚肉」，劉邦遂藉如廁脫險回營。",
     "Xiang Zhuang danced with sword intending to slay Liu Bang. Fan Kuai rushed in: 'A great deed disregards petty scruples! When others are the cleaver and we the meat, why bid farewell?'",
     "鴻門宴波譎雲詭、情節跌宕起伏，人物刻畫入木三分，為中國敘事文學最高典範。",
     "【漢越音考證】項 (Hạng), 羽 (Vũ), 沛 (Bái), 樊 (Phàn), 噲 (Khoái), 俎 (Trở), 肉 (Nhục).",
     [{"viet": "Đại hành bất cố tế cẩn, đại lễ bất từ tiểu nhượng. Kim nhân phương vi đao trở, ngã vi ngư nhục.", "zh": "大行不顧細謹，大禮不辭小讓。如今人方為刀俎，我為魚肉，何辭為？", "en": "Great actions heed not small scruples. Now others are cleaver and we are fish and meat!", "hanViet": "Đại hành bất cố tế cẩn"}]),

    (8, "v2", "r08_03_shiji_gaixia", "《史記·項羽本紀·垓下之圍》", "Sử Ký - Hạng Vũ Bản Kỷ - Cai Hạ Chi Vi", "Records of the Grand Historian: Siege of Gaixia", "司馬遷", "Tư Mã Thiên", "西漢", "Tây Hán",
     "項王軍壁垓下，兵少食盡，漢軍及諸侯兵圍之數重。夜聞漢軍四面皆楚歌，項王乃大驚曰：「漢皆已得楚乎？是何楚人之多也！」項王則夜起，飲帳中。有美人名虞，常幸從；駿馬名騅，常騎之。於是項王乃悲歌忼慨，自為詩曰：「力拔山兮氣蓋世，時不利兮騅不逝。騅不逝兮可奈何，虞兮虞兮奈若何！」歌數闋，美人和之。項王泣數行下，左右皆泣，莫能仰視。",
     "項羽垓下被圍兵少糧盡，四面楚歌。夜起帳中悲歌慷慨：「力拔山兮氣蓋世，時不利兮騅不逝！虞兮虞兮奈若何！」虞姬相和，左右英雄皆掩面痛泣。",
     "Surrounded at Gaixia, Xiang Yu heard Chu songs from four sides. He sang mournfully: 'My strength plucked up mountains, my might dominated the world. But times are against me; Yu, oh Yu, what can I do for you?'",
     "司馬遷以雄奇悲壯之筆刻畫一代霸王項羽之悲劇命運，四面楚歌與霸王別姬成為千古絕響。",
     "【漢越音考證】垓 (Cai), 歌 (Ca), 虞 (Ngu), 姬 (Cơ), 騅 (Truy), 慷 (Khang), 慨 (Khái).",
     [{"viet": "Lực bạt sơn hề khí cái thế, thời bất lợi hề Truy bất thệ. Truy bất thệ hề khả nại hà, Ngu hề Ngu hề nại nhược hà!", "zh": "力拔山兮氣蓋世，時不利兮騅不逝。騅不逝兮可奈何，虞兮虞兮奈若何！", "en": "My strength uprooted mountains, my spirit covered the earth. Yu, oh Yu, what fate awaits you!", "hanViet": "Lực bạt sơn hề khí cái thế"}]),

    (8, "v2", "r08_04_shiji_quyuan", "《史記·屈原賈生列傳》", "Sử Ký - Khuất Nguyên Giả Sanh Liệt Truyện", "Records of the Grand Historian: Qu Yuan & Jia Yi", "司馬遷", "Tư Mã Thiên", "西漢", "Tây Hán",
     "屈平疾王聽之不聰也，讒諂之蔽明也，邪曲之害公也，方正之不容也，故憂愁幽思而作《離騷》。《國風》好色而不淫，《小雅》怨誹而不亂。若《離騷》者，可謂兼之矣。其文約，其辭微，其志潔，其行廉。其志潔，故其稱物芳；其行廉，故死而不容。推此志也，雖與日月爭光可也！",
     "屈原痛心懷王昏蔽、讒邪害公，故憂憤作《離騷》。司馬遷盛讚屈原文約辭微、志潔行廉，推此忠貞之志，足以與日月爭輝光芒萬丈。",
     "Qu Yuan wrote Li Sao in grief over the ruler's blindness and slanderers' malice. His aim was so pure and conduct so upright that his spirit can vie with the sun and moon in glory!",
     "司馬遷借屈原列傳抒發自我不白之冤與高潔忠志，「與日月爭光」之評語為古代文學評論之極致至評。",
     "【漢越音考證】賈 (Giả), 讒 (Sàm), 諂 (Siểm), 離 (Ly), 騷 (Tao), 潔 (Khiết), 廉 (Liêm).",
     [{"viet": "Thôi thử chí dã, tuy dữ nhật nguyệt tranh quang khả dã!", "zh": "推此志也，雖與日月爭光可也！", "en": "Extending this noble spirit, it may vie with the sun and moon in brilliance!", "hanViet": "Tuy dữ nhật nguyệt tranh quang"}]),

    (8, "v2", "r08_05_shiji_jingke", "《史記·刺客列傳·荊軻》", "Sử Ký - Thích Khách Liệt Truyện - Kinh Kha", "Records of the Grand Historian: Jing Ke", "司馬遷", "Tư Mã Thiên", "西漢", "Tây Hán",
     "太子及賓客知其事者，皆白衣冠以送之。至易水之上，既祖，取道。高漸離擊筑，荊軻和而歌，為變徵之聲，士皆垂淚涕泣。又前而為歌曰：「風蕭蕭兮易水寒，壯士一去兮不復還！」復為慷慨羽聲，士皆瞋目，髮盡上指冠。於是荊軻遂就車而去，終已不顧。",
     "太子丹與賓客白衣冠易水送別荊軻。高漸離擊筑，荊軻悲歌：「風蕭蕭兮易水寒，壯士一去兮不復還！」滿座士人悲壯瞋目，荊軻毅然登車西去不顧。",
     "By the River Yi, Gao Jianli played the lute and Jing Ke sang: 'The wind soughs and the River Yi is cold; the brave warrior goes, never to return!'",
     "易水送別之景蕭索悲壯，荊軻視死如歸刺秦大義，千百年來傳唱為俠義與勇烈之最高象徵。",
     "【漢越音考證】刺 (Thích), 客 (Khách), 荊 (Kinh), 軻 (Kha), 易 (Dịch), 蕭 (Tiêu), 筑 (Trúc).",
     [{"viet": "Phong tiêu tiêu hề Dịch thủy hàn, tráng sĩ nhất khứ hề bất phục hoàn!", "zh": "風蕭蕭兮易水寒，壯士一去兮不復還！", "en": "The wind soughs and the River Yi is cold; the brave warrior departs, never to return!", "hanViet": "Phong tiêu tiêu hề Dịch thủy hàn"}]),

    # Round 9: 兩漢政論與漢書
    (9, "v2", "r09_01_hanshu_suwu", "《漢書·蘇武傳》", "Hán Thư - Tô Vũ Truyện", "Book of Han: Biography of Su Wu", "班固", "Ban Cố", "東漢", "Đông Hán",
     "單于使衛律召武受辭。武謂惠等：「屈節辱命，雖生，何面目以歸漢！」引佩刀自刺。單于愈益欲降之。幽武置大窖中，絕不飲食。天雨雪，武臥齧雪，與旃毛並咽之，數日不死。匈奴徙武北海上無人處，使牧羝。武杖漢節牧羊，臥起操持，節旄盡落。歷十九年，始得歸漢，鬚髮盡白。",
     "蘇武出使匈奴不屈節，自刺未死。匈奴幽禁北海牧羊十九年，手持漢節臥起不離，節旄落盡忠貞不渝，終以白首榮歸漢室。",
     "Su Wu held the Han imperial staff for nineteen years in northern wilderness, chewing snow and wool, enduring till his hair turned white without surrendering.",
     "班固以沉穩厚重筆法刻畫蘇武持節不屈之民族大義與堅貞氣節，成為古代忠臣義士之永恆典範。",
     "【漢越音考證】漢 (Hán), 書 (Thư), 蘇 (Tô), 武 (Vũ), 節 (Tiết), 旃 (Chiên), 牧 (Mục), 羊 (Dương).",
     [{"viet": "Trượng Hán tiết mục dương, ngọa khởi thao trì, tiết mao tận lạc.", "zh": "武杖漢節牧羊，臥起操持，節旄盡落。", "en": "Holding the Han staff while herding sheep, never letting go until the tassels fell.", "hanViet": "Trượng Hán tiết mục dương"}]),

    (9, "v2", "r09_02_jiayi_guoqin", "賈誼《過秦論上》", "Giả Nghị - Quá Tần Luận Thượng", "Jia Yi: The Faults of Qin", "賈誼", "Giả Nghị", "西漢", "Tây Hán",
     "秦王掃六合，席捲天下，包舉宇內，囊括四海之意，並吞八荒之心。振長策而御宇內，吞二周而亡諸侯，履至尊而制六合，執敲扑而鞭笞天下，威振四海。然而陳涉甕牖繩樞之子，揭竿為旗，天下雲集而響應，贏糧而景從。山東豪俊遂並起而亡秦族矣。一夫作難而七廟隳，身死人手，為天下笑者，何也？仁義不施而攻守之勢異也。",
     "秦滅六國統一天下威震四海，卻因陳涉揭竿起義天下雲集響應而迅速覆亡。何以至此？乃因仁義不施，攻取天下與守成天下之形勢大相徑庭也。",
     "Qin conquered the world with mighty force, yet collapsed when peasant Chen She raised the banner. Why? Because it failed to rule with benevolence when the situation shifted!",
     "賈誼《過秦論》氣勢磅礡、辭彩雄麗，論證秦朝暴虐失道速亡之歷史教訓，為漢代政論散文第一名篇。",
     "【漢越音考證】賈 (Giả), 誼 (Nghị), 過 (Quá), 秦 (Tần), 策 (Sách), 鞭 (Tiên), 笞 (Si), 仁 (Nhân), 義 (Nghĩa).",
     [{"viet": "Nhất phu tác nan nhi thất miếu hủy, thân tử nhân thủ, vi thiên hạ tiếu giả, hà dã? Nhân nghĩa bất thi nhi công thủ chi thế dị dã.", "zh": "一夫作難而七廟隳，身死人手，為天下笑者，何也？仁義不施而攻守之勢異也。", "en": "A single rebel destroyed the imperial shrines; why? Because benevolence was not practiced and tactics had to change.", "hanViet": "Nhân nghĩa bất thi"}]),

    (9, "v2", "r09_03_jiayi_zhian", "賈誼《治安策》", "Giả Nghị - Trị An Sách", "Jia Yi: Policy on National Security", "賈誼", "Giả Nghị", "西漢", "Tây Hán",
     "夫抱火厝之積薪之下而寢其上，火未及燃，因謂之安，方今之勢，何以異此！本末舛逆，首尾衡決，國制未定，藩國割據。可為痛哭者一，可為流涕者二，可為長太息者六。欲天下之治安，莫若眾建諸侯而少其力。",
     "賈誼痛陳西漢潛伏危機：如同睡在堆滿木柴火堆之上自以為安。提出眾建諸侯削弱勢力之策，為漢景帝漢武帝推恩令奠定理論先導。",
     "Like lying asleep upon a pile of firewood above a smoldering spark! To bring lasting peace, divide feudal lands to diminish their power.",
     "《治安策》洞察漢初諸侯王尾大不掉之隱患，論事切中時弊，詞氣慷慨激昂。",
     "【漢越音考證】治 (Trị), 安 (An), 薪 (Tân), 哭 (Khốc), 涕 (Thế), 藩 (Phiên).",
     [{"viet": "Dục thiên hạ chi trị an, mạc nhược chúng kiến chư hầu nhi thiểu kỳ lực.", "zh": "欲天下之治安，莫若眾建諸侯而少其力。", "en": "To secure enduring peace, divide feudal states to reduce their power.", "hanViet": "Chúng kiến chư hầu"}]),

    (9, "v2", "r09_04_chaocuo_guisu", "晁錯《論貴粟疏》", "Triều Thác - Luận Quý Túc Sớ", "Chao Cuo: Memorial on Elevating Grain", "晁錯", "Triều Thác", "西漢", "Tây Hán",
     "民貧則奸邪生。貧生於不足，不足生於不農，不農則不地著，不地著則離鄉輕家，民如鳥獸，雖有高城深池，嚴法重刑，猶不能禁也。夫珠玉金銀，饑不可食，寒不可衣；然而眾人之所貴者，以上用之故也。粟米布帛，生民之本也。故明主貴粟而重農。",
     "晁錯力陳重農貴粟之道：珠玉金銀饑不可食寒不可衣，糧食布帛才是人民生存之根本。農民安定則國家自穩。",
     "Jewels, gold and silver cannot be eaten when hungry nor worn when freezing. Grain and fabric are the true root of people's livelihood.",
     "晁錯以嚴密邏輯論述農業立國之重，批判棄農經商與奢靡之風，對古代重農抑商政策影響深遠。",
     "【漢越音考證】晁 (Triều), 錯 (Thác), 粟 (Túc), 疏 (Sớ), 貧 (Bần), 農 (Nông), 帛 (Bạch).",
     [{"viet": "Châu ngọc kim ngân, cơ bất khả thực, hàn bất khả y; túc mão sinh dân chi bản dã.", "zh": "珠玉金銀，饑不可食，寒不可衣；粟米布帛，生民之本也。", "en": "Gold and jewels cannot be eaten or worn; grain and cloth are the foundation of life.", "hanViet": "Túc mễ sinh dân chi bản"}]),

    (9, "v2", "r09_05_simaxiangru_zixu", "司馬相如《子虛賦》", "Tư Mã Tương Như - Tử Hư Phú", "Sima Xiangru: Rhapsody of Sir Vacuous", "司馬相如", "Tư Mã Tương Như", "西漢", "Tây Hán",
     "楚使子虛使於齊，齊王悉發境內之士，備車騎之眾，與使者出畋。子虛過詫齊王以楚王之遊雲夢也。左烏喙，右湯谷，緣以大江，帶以盤石。其山則九𡾲巃嵸，神木靈草，珍禽異獸，奔星合遝。誇飾雲夢澤之廣大豪奢，終歸於諷諫天子節儉之旨。",
     "司馬相如以子虛、烏有先生、亡是公三人問答，大肆鋪陳楚國雲夢澤與天子上林苑打獵遊樂之壯麗奢豪，文采斐然氣勢宏深。",
     "Sir Vacuous boasted of Chu's vast Yunmeng marsh with celestial trees and rare beasts, concluding with subtle admonition against excessive luxury.",
     "漢賦大成之作，以極致鋪陳排比、華麗辭藻展現大漢盛世帝國之雄渾氣象，首開「勸百諷一」漢大賦體制。",
     "【漢越音考證】相 (Tương), 如 (Như), 賦 (Phú), 虛 (Hư), 畋 (Điền), 澤 (Trạch), 誇 (Khoa).",
     [{"viet": "Tử Hư quá sá Tề vương dĩ Sở vương chi du Vân Mộng dã.", "zh": "子虛過詫齊王以楚王之遊雲夢也。", "en": "Sir Vacuous boasted to the King of Qi of the King of Chu's grand hunt at Yunmeng.", "hanViet": "Tử Hư phú"}]),

    # Round 10: 建安風骨與魏晉名士
    (10, "v2", "r10_01_caocao_duange", "曹操《短歌行》", "Tào Tháo - Đoản Ca Hành", "Cao Cao: Short Song", "曹操", "Tào Tháo", "東漢末", "Đông Hán Mạt",
     "對酒當歌，人生幾何！譬如朝露，去日苦多。慨當以慷，憂思難忘。何以解憂？唯有杜康。青青子衿，悠悠我心。但為君故，沉吟至今。月明星稀，烏鵲南飛。繞樹三匝，何枝可依？山不厭高，海不厭深。周公吐哺，天下歸心。",
     "對著美酒應當高歌，人生短暫如晨露。憂念時光流逝求賢若渴，唯有杜康酒能解憂。高山不嫌其高，大海不嫌其深。願效法周公禮賢下士，使天下賢才盡皆歸心！",
     "Facing wine let us sing, for how long is life? Like morning dew, its days fly fast. Mountains never tire of height, seas never tire of depth. May Zhou Gong's hospitality unite all hearts under heaven!",
     "曹操建安風骨代表作，融合生命苦短之深沉憂患與統一天下、渴求賢才之雄偉胸襟，慷慨悲涼名垂青史。",
     "【漢越音考證】曹 (Tào), 操 (Tháo), 短 (Đoản), 歌 (Ca), 露 (Lộ), 杜 (Đỗ), 康 (Kang), 衿 (Khâm), 哺 (Phụ).",
     [{"viet": "Đối tửu đương ca, nhân sinh kỷ hà! Thí như triêu lộ, khứ nhật khổ đa.", "zh": "對酒當歌，人生幾何！譬如朝露，去日苦多。", "en": "Facing the wine let us sing, how brief is human life! Like morning dew.", "hanViet": "Đối tửu đương ca"}]),

    (10, "v2", "r10_02_caocao_guancanghai", "曹操《步出夏門行·觀滄海》", "Tào Tháo - Quan Thương Hải", "Cao Cao: Gazing at the Blue Ocean", "曹操", "Tào Tháo", "東漢末", "Đông Hán Mạt",
     "東臨碣石，以觀滄海。水何澹澹，山島竦峙。樹木叢生，百草豐茂。秋風蕭瑟，洪波湧起。日月之行，若出其中；星漢燦爛，若出其裏。幸甚至哉，歌以詠志。",
     "東行登上碣石山俯瞰浩瀚滄海。海水微波蕩漾，山島高聳峙立。日月運行如同從滄海中升起，銀河璀璨如同從海中孕育。胸襟包容吞吐宇宙日月。",
     "Eastward I climb the Jieshi rock to view the vast blue ocean. The sun and moon in their courses seem to rise from it; the Milky Way in splendor seems to issue from its depths!",
     "曹操北征烏桓歸途所作，以吞吐日月星辰之宏大氣魄描繪大海，為古代山水寫景詩開山巨篇。",
     "【漢越音考證】滄 (Thương), 海 (Hải), 碣 (Kiệt), 澹 (Đạm), 竦 (Tủng), 燦 (Sán), 爛 (Lạn).",
     [{"viet": "Nhật nguyệt chi hành, nhược xuất kỳ trung; tinh hán xán lạn, nhược xuất kỳ lý.", "zh": "日月之行，若出其中；星漢燦爛，若出其裏。", "en": "The motion of sun and moon seems to rise from within it; the Milky Way seems to emerge from its depths.", "hanViet": "Nhật nguyệt chi hành"}]),

    (10, "v2", "r10_03_caopi_dianlun", "曹丕《典論·論文》", "Tào Phi - Điển Luận - Luận Văn", "Cao Pi: On Literature", "曹丕", "Tào Phi", "三國·魏", "Tam Quốc - Ngụy",
     "文人相輕，自古而然。傅毅之於班固，伯仲之間耳，而固小之。蓋文章，經國之大業，不朽之盛事。年壽有時而盡，榮樂止乎其身，二者必至之常期，未若文章之無窮。是以古之作者，寄身於翰墨，見意於篇籍，不假良史之辭，不託飛馳之勢，而聲名自傳於後。",
     "文人自古互相輕視。然而文章是治理國家的偉大事業，是流傳不朽的千秋盛事。人的生命與榮華終將終結，唯有文章能歷久彌新萬古流芳。",
     "Literature is the great deed for governing a state, an immortal achievement. Life has its end, but literature is everlasting.",
     "曹丕《典論·論文》為中國文學批評史上首篇專題文學論文，確立文章經國之大業與不朽價值。",
     "【漢越音考證】典 (Điển), 論 (Luận), 輕 (Khinh), 經 (Kinh), 朽 (Hủ), 翰 (Hàn), 墨 (Mặc).",
     [{"viet": "Cái văn chương, kinh quốc chi đại nghiệp, bất hủ chi thịnh sự.", "zh": "蓋文章，經國之大業，不朽之盛事。", "en": "Literature is a glorious enterprise for statecraft, an immortal achievement.", "hanViet": "Văn chương kinh quốc chi đại nghiệp"}]),

    (10, "v2", "r10_04_caozhi_luoshenfu", "曹植《洛神賦》", "Tào Thực - Lạc Thần Phú", "Cao Zhi: Rhapsody on the Goddess of Luo River", "曹植", "Tào Thực", "三國·魏", "Tam Quốc - Ngụy",
     "翩若驚鴻，婉若游龍。榮曜秋菊，華茂春松。髣髴兮若輕雲之蔽月，飄颻兮若流風之迴雪。遠而望之，皎若太陽升朝霞；迫而察之，灼若芙蕖出渌波。延頸秀項，皓質呈露。芳澤無加，鉛華弗御。雲髻峨峨，修眉聯娟。含辭未吐，氣若幽蘭。華容婀娜，令我忘餐。",
     "洛水女神身姿翩然如受驚鴻雁，婉轉如游龍騰空。光采如秋菊，茂盛如春松。若輕雲蔽月、流風迴雪。肌膚如白雪芳澤天然，姿態曼妙令人忘食忘神。",
     "Lightly she moves as a startled swan, gracefully as a swimming dragon. Luminous as an autumn chrysanthemum, lush as a spring pine. Glimpsed as the moon behind light clouds, drifting as snow caught in the wind.",
     "曹植以極致華美浪漫之詞采描摹洛水女神甄宓般幻美形象，駢儷精工，為中國辭賦史上審美意境最高典範。",
     "【漢越音考證】植 (Thực), 洛 (Lạc), 神 (Thần), 鴻 (Hồng), 婉 (Uyển), 菊 (Cúc), 霞 (Hà), 芙 (Phù), 蕖 (Cừ).",
     [{"viet": "Phiên nhược kinh hồng, uyển nhược du long. Vinh diệu thu cúc, hoa mậu xuân tùng.", "zh": "翩若驚鴻，婉若游龍。榮曜秋菊，華茂春松。", "en": "Light as a startled swan, graceful as a roaming dragon. Radiant as autumn chrysanthemum, lush as spring pine.", "hanViet": "Phiên nhược kinh hồng"}]),

    (10, "v2", "r10_05_caozhi_qibushi", "曹植《七步詩》", "Tào Thực - Thất Bộ Thi", "Cao Zhi: The Seven Steps Poem", "曹植", "Tào Thực", "三國·魏", "Tam Quốc - Ngụy",
     "煮豆燃豆萁，豆在釜中泣。本是同根生，相煎何太急？",
     "鍋裡煮著豆子，燃燒著豆秸作柴火，豆子在鍋中悲傷哭泣。豆與豆秸本是同一個根上生長出來的，為何要如此緊迫地互相煎熬逼迫呢？",
     "Boiling beans by burning beanstalks, the beans weep inside the pot: born of the very same root, why torture each other with such haste?",
     "相傳曹丕逼迫胞弟曹植七步內成詩，曹植借豆萁同根相煎設喻，悲愴道出骨肉相殘之慘痛，感人至深免除死劫。",
     "【漢越音考證】七 (Thất), 步 (Bộ), 煮 (Chử), 豆 (Đậu), 萁 (Kỳ), 釜 (Phủ), 泣 (Khấp), 煎 (Tiên).",
     [{"viet": "Bản thị đồng căn sinh, tương tiên hà thái cấp?", "zh": "本是同根生，相煎何太急？", "en": "Born of the very same root, why press and torture one another with such haste?", "hanViet": "Bản thị đồng căn sinh"}]),

    # Round 11: 忠節表奏
    (11, "v2", "r11_01_zhugeliang_qianshushi", "諸葛亮《前出師表》", "Gia Cát Lượng - Tiền Xuất Sư Biểu", "Zhuge Liang: Former Memorial on the Expedition", "諸葛亮", "Gia Cát Lượng", "三國·蜀", "Tam Quốc - Thục",
     "臣本布衣，躬耕於南陽，苟全性命於亂世，不求聞達於諸侯。先帝不以臣卑鄙，猥自枉屈，三顧臣於草廬之中，諮臣以當世之事，由是感激，遂許先帝以驅馳。後值傾覆，受任於敗軍之際，奉命於危難之間，爾來二十有一年矣。今當遠離，臨表涕零，不知所言。",
     "臣本是一介平民在南陽親自耕種，只想在亂世中保全性命，不求在諸侯中顯名。先帝不嫌臣下卑微，三顧草廬諮商天下大事。臣臨危受命二十一年，今出師北伐臨表涕泣不知所言。",
     "I was originally a commoner, tilling the land in Nanyang. The Late Emperor disdained not my unworthiness, visiting my humble cottage thrice. Deeply moved, I vowed my service to him. Now on the verge of departure, tears fall upon this memorial.",
     "《前出師表》為千古第一忠義誄表，字字句句飽含對劉備父子之忠貞赤誠與興復漢室之鞠躬盡瘁決心。",
     "【漢越音考證】葛 (Cát), 亮 (Lượng), 出 (Xuất), 師 (Sư), 表 (Biểu), 躬 (Cung), 耕 (Canh), 廬 (Lư), 涕 (Thế).",
     [{"viet": "Thụ nhiệm ư bại quân chi tế, phụng mệnh ư nguy nan chi gian.", "zh": "受任於敗軍之際，奉命於危難之間。", "en": "Entrusted with office at a time of defeat, receiving command amidst dire crisis.", "hanViet": "Thụ nhiệm ư bại quân chi tế"}]),

    (11, "v2", "r11_02_zhugeliang_houshushi", "諸葛亮《後出師表》", "Gia Cát Lượng - Hậu Xuất Sư Biểu", "Zhuge Liang: Latter Memorial on the Expedition", "諸葛亮", "Gia Cát Lượng", "三國·蜀", "Tam Quốc - Thục",
     "先帝慮漢、賊不兩立，王業不偏安，故託臣以討賊也。以先帝之明，量臣之才，故知臣伐賊，才弱敵強也。然不伐賊，王業亦亡。坐而待亡，孰與伐之？是故託臣而弗疑也。臣鞠躬盡瘁，死而後已；至於成敗利鈍，非臣之明所能逆睹也。",
     "先帝深知漢室與曹賊誓不兩立，王圖大業不可偏安一隅。臣明知才弱敵強，但坐以待斃不如奮力伐賊。臣願鞠躬盡瘁死而後已，成敗利鈍非臣所能預料。",
     "I will bend my back to the task with devotion until death. As for whether success or failure awaits, it is beyond human foresight.",
     "「鞠躬盡瘁，死而後已」成為中華民族忠誠盡責、死而後已崇高奉獻精神之最高座右銘。",
     "【漢越音考證】後 (Hậu), 鞠 (Cúc), 躬 (Cung), 瘁 (Tụy), 鈍 (Độn), 逆 (Nghịch).",
     [{"viet": "Thần cúc cung tận tụy, tử nhi hậu dĩ.", "zh": "臣鞠躬盡瘁，死而後已。", "en": "I shall dedicate myself with utter devotion, stopping only at death.", "hanViet": "Cúc cung tận tụy tử nhi hậu dĩ"}]),

    (11, "v2", "r11_03_limi_chenqing", "李密《陳情表》", "Lý Mật - Trần Tình Biểu", "Li Mi: Memorial Expressing My Feelings", "李密", "Lý Mật", "西晉", "Tây Tấn",
     "臣密言：臣以險釁，夙遭閔凶。生孩六月，慈父見背；行年四歲，舅奪母志。祖母劉憫臣孤弱，躬親撫養。臣無祖母，無以至今日；祖母無臣，無以終餘年。母孫二人，更相為命。是以區區不能廢遠。臣生當隕首，死當結草。聽臣微志，庶劉僥倖，卒保餘年！",
     "李密陳述自幼孤苦由祖母劉氏撫養成人。晉武帝徵召為官，李密以「臣無祖母無以至今日，祖母無臣無以終餘年」上表陳情乞留侍養祖母天年，至孝真情令晉武帝深為感動。",
     "Without my grandmother I could not have survived till today; without me she cannot live out her remaining years. Grant my humble plea to attend her till her days are done!",
     "《陳情表》以孝道至情動人，「讀諸葛亮出師表不墮淚者不忠，讀李密陳情表不墮淚者不孝」傳為千古美談。",
     "【漢越音考證】密 (Mật), 陳 (Trần), 情 (Tình), 釁 (Hấn), 憫 (Mẫn), 孤 (Cô), 隕 (Duẫn / Vẫn).",
     [{"viet": "Thần vô tổ mẫu, vô dĩ chí kim nhật; tổ mẫu vô thần, vô dĩ chung dư niên.", "zh": "臣無祖母，無以至今日；祖母無臣，無以終餘年。", "en": "Without my grandmother I could not have reached today; without me she cannot finish her remaining years.", "hanViet": "Thần vô tổ mẫu"}]),

    (11, "v2", "r11_04_jikang_shanjuyuan", "嵇康《與山巨源絕交書》", "Kê Khang - Dữ Sơn Cự Nguyên Tuyệt Giao Thư", "Ji Kang: Letter Breaking Friendship with Shan Juyuan", "嵇康", "Kê Khang", "三國·魏", "Tam Quốc - Ngụy",
     "足下舊知吾潦倒粗疏，不喜俗吏，乃欲引吾入仕。吾每讀尚子平、臺孝威傳，慨然慕之。性有所不堪，真不可強。游山澤、觀魚鳥，心甚樂之。一旦入朝，手足拘礙，動見咎尤。足下何苦以所好逼人於所惡？直陳心跡，請從此絕！",
     "嵇康抗拒好友山濤推薦入朝為官，作書直陳性情孤傲崇尚自然不耐俗禮，誓不為司馬氏政權屈志，寧自放於山林鐵鋪鍛鐵。",
     "You know my unrestrained nature, yet you seek to drag me into office. I delight in wandering mountains and observing birds. Why force me into what I despise?",
     "竹林七賢之首嵇康以此書宣告名士孤高風骨與對偽善政治之決絕反抗，展現魏晉風流極致獨立人格。",
     "【漢越音考證】嵇 (Kê), 康 (Khang), 絕 (Tuyệt), 交 (Giao), 潦 (Liêu), 拘 (Câu), 咎 (Cữu).",
     [{"viet": "Tính hữu sở bất kham, chân bất khả cưỡng.", "zh": "性有所不堪，真不可強。", "en": "My nature cannot endure it, and truly cannot be forced.", "hanViet": "Tính hữu sở bất kham"}]),

    (11, "v2", "r11_05_simagian_baorenan", "司馬遷《報任安書》", "Tư Mã Thiên - Báo Nhậm An Thư", "Sima Qian: Letter in Reply to Ren An", "司馬遷", "Tư Mã Thiên", "西漢", "Tây Hán",
     "人固有一死，或重於泰山，或輕於鴻毛，用之所趣異也。太上不辱先，其次不辱身。僕雖怯懦，欲苟活，亦頗識去就之分矣，何至自沉溺縲紲之辱哉！所以隱忍苟活，幽於糞土之中而不辭者，恨私心有所不盡，鄙陋沒世而文采不表於後也。乃發憤著《史記》。",
     "司馬遷遭李陵之禍受宮刑巨辱，含垢忍辱苟活不死，乃因《史記》草創未就。「人固有一死，或重於泰山或輕於鴻毛」，發憤著述立言不朽。",
     "A man truly dies but once; his death may be heavier than Mount Tai or lighter than a swan feather. I endured the humiliation of prison and castration only to finish the Records of the Grand Historian!",
     "司馬遷在極度屈辱中展現驚天地泣鬼神之堅韌意志，生死價值觀激勵一代代志士仁人奮發有為。",
     "【漢越音考證】報 (Báo), 任 (Nhậm), 安 (An), 泰 (Thái), 鴻 (Hồng), 毛 (Mao), 縲 (Lôi), 紲 (Tiết).",
     [{"viet": "Nhân cố hữu nhất tử, hoặc trọng ư Thái Sơn, hoặc khinh ư hồng mao.", "zh": "人固有一死，或重於泰山，或輕於鴻毛。", "en": "All men must die, but some deaths are heavier than Mount Tai, others lighter than a swan feather.", "hanViet": "Nhân cố hữu nhất tử"}]),

    # Round 12: 東晉隱逸與蘭亭
    (12, "v2", "r12_01_wangxizhi_lanting", "王羲之《蘭亭集序》", "Vương Hi Chi - Lan Đình Tập Tự", "Wang Xizhi: Preface to the Orchid Pavilion", "王羲之", "Vương Hi Chi", "東晉", "Đông Tấn",
     "永和九年，歲在癸丑，暮春之初，會於會稽山陰之蘭亭，脩禊事也。群賢畢至，少長咸集。此地有崇山峻嶺，茂林脩竹；又有清流激湍，映帶左右，引以為流觴曲水，列坐其次。仰觀宇宙之大，俯察品類之盛，所以遊目騁懷，足以極視聽之娛，信可樂也。向之所欣，俛仰之間，已為陳跡。固知一死生為虛誕，齊彭殤為妄作。後之視今，亦猶今之視昔。悲夫！",
     "東晉永和九年三月三日，王羲之與謝安等四十二名士會聚蘭亭曲水流觴。仰觀宇宙俯察萬物，感嘆韶光易逝死生亦大，後之覽者亦將有感於斯文。",
     "On the third day of the third month, we gathered at the Orchid Pavilion. Looking up at the vast cosmos and down at the richness of creation, we let our eyes roam and spirits soar. How sad to realize that later generations will view us just as we view the past!",
     "天下第一行書名篇，熔詩、書、哲理於一爐，既有春山曲水之雅趣，又有對生命逝去之崇高宇宙哲思。",
     "【漢越音考證】羲 (Hi), 之 (Chi), 蘭 (Lan), 亭 (Đình), 觴 (Thương), 癸 (Quý), 丑 (Sửu), 契 (Khế), 騁 (Sính).",
     [{"viet": "Ngưỡng quan vũ trụ chi đại, phủ sát phẩm loại chi thịnh, sở dĩ du mục sính hoài, túc dĩ cực thị thính chi ngu, tín khả lạc dã.", "zh": "仰觀宇宙之大，俯察品類之盛，所以遊目騁懷，足以極視聽之娛，信可樂也。", "en": "Looking up at the immensity of the universe, and down at the multitude of species, letting our eyes roam and spirits soar!", "hanViet": "Ngưỡng quan vũ trụ chi đại"}]),

    (12, "v2", "r12_02_taoyuanming_taohuayuan", "陶淵明《桃花源記》", "Đào Uyên Minh - Đào Hoa Nguyên Ký", "Tao Yuanming: Peach Blossom Spring", "陶淵明", "Đào Uyên Minh", "東晉", "Đông Tấn",
     "晉太元中，武陵人捕魚為業。緣溪行，忘路之遠近。忽逢桃花林，夾岸數百步，中無雜樹，芳草鮮美，落英繽紛。漁人甚異之。復前行，便得一山，山有小口，彷彿若有光。便舍船，從口入。初極狹，纔通人。復行數十步，豁然開朗。土地平曠，屋舍儼然，有良田美池桑竹之屬。阡陌交通，雞犬相聞。其中往來種作，男女衣著，悉如外人。黃髮垂髫，並怡然自樂。",
     "武陵漁人溯溪誤入桃花源，見芳草鮮美落英繽紛。村民避秦亂居此不知有漢魏，阡陌交通雞犬相聞黃髮垂髫怡然自樂。後人尋訪迷不可得。",
     "A fisherman came upon a grove of blossoming peach trees. Walking through a cave, he found a secluded utopia where people lived in harmony without knowing wars or dynasties.",
     "陶淵明虛構桃花源世外仙境，寄託對無剝削、無戰亂、自給自足和平烏托邦社會之永恆嚮往。",
     "【漢越音考證】陶 (Đào), 淵 (Uyên), 明 (Minh), 桃 (Đào), 源 (Nguyên), 繽 (Tân), 紛 (Phân), 阡 (Thiên), 陌 (Mạch).",
     [{"viet": "Hoàng phát thùy thiều, tịnh di nhiên tự lạc.", "zh": "黃髮垂髫，並怡然自樂。", "en": "The elderly and children with unbundled hair were all joyful and at ease.", "hanViet": "Hoàng phát thùy thiều"}]),

    (12, "v2", "r12_03_taoyuanming_guiqulai", "陶淵明《歸去來兮辭》", "Đào Uyên Minh - Quy Khứ Lai Hề Từ", "Tao Yuanming: Return Home", "陶淵明", "Đào Uyên Minh", "東晉", "Đông Tấn",
     "歸去來兮，田園將蕪胡不歸？既自以心為形役，奚惆悵而獨悲！悟已往之不諫，知來者之可追。實迷途其未遠，覺今是而昨非。舟遙遙以輕颺，風飄飄而吹衣。問征夫以前路，恨晨光之熹微。引壺觴以自酌，眄庭柯以怡顏。木欣欣以向榮，泉涓涓而始流。聊乘化以歸盡，樂夫天命復奚疑！",
     "回去吧！田園快荒蕪了為何不歸去？既不願為五斗米折腰，何必惆悵悲傷。覺悟過去之非，及時追尋未來之是。回歸田園飲酒賦詩，順應自然樂天知命。",
     "Return home! My fields are turning wild, why not return? Aware that past mistakes cannot be recalled, I know future pursuits can still be achieved.",
     "陶淵明毅然辭官歸隱宣言，抒發擺脫名韁利鎖後重獲心靈自由與回歸田園大自然之純粹喜悅。",
     "【漢越音考證】歸 (Quy), 蕪 (Vô), 諫 (Gián), 熹 (Hi), 觴 (Thương), 眷 (Quyến).",
     [{"viet": "Ngộ dĩ vãng chi bất gián, tri lai giả chi khả truy. Thực mê đồ kỳ vị viễn, giác kim thị nhi tạc phi.", "zh": "悟已往之不諫，知來者之可追。實迷途其未遠，覺今是而昨非。", "en": "Knowing the past cannot be changed, I know the future may still be won; truly I strayed not too far.", "hanViet": "Ngộ dĩ vãng chi bất gián"}]),

    (12, "v2", "r12_04_taoyuanming_wuliu", "陶淵明《五柳先生傳》", "Đào Uyên Minh - Ngũ Liễu Tiên Sinh Truyện", "Tao Yuanming: Biography of Master Five Willows", "陶淵明", "Đào Uyên Minh", "東晉", "Đông Tấn",
     "先生不知何許人也，亦不詳其姓字，宅邊有五柳樹，因以為號焉。閑靜少言，不慕榮利。好讀書，不求甚解；每有會意，便欣然忘食。性嗜酒，家貧不能常得。親舊知其如此，或置酒而招之；造飲輒盡，期在必醉。環堵蕭然，不蔽風日；短褐穿結，簞瓢屢空，晏如也。常著文章自娛，頗示己志。忘懷得失，以此自終。",
     "五柳先生宅邊有五柳樹因以為號。好讀書不求甚解，嗜酒率真家貧簞瓢屢空而泰然自若。著文章自娛忘懷得失，安貧樂道一生。",
     "The Master was quiet and spoke little, desiring neither fame nor fortune. Fond of reading without quibbling over details, he rejoiced whenever he grasped the inner meaning.",
     "陶淵明自畫像式名篇，以白描幽默筆觸勾勒隱士高風亮節與不汲汲於富貴之曠達人生。",
     "【漢越音考證】柳 (Liễu), 嗜 (Thị), 褐 (Hạt), 簞 (Đan), 瓢 (Biều), 晏 (Yến).",
     [{"viet": "Hảo độc thư, bất cầu thậm giải; mỗi hữu hội ý, tiện hân nhiên vong thực.", "zh": "好讀書，不求甚解；每有會意，便欣然忘食。", "en": "Fond of reading without nitpicking every word; whenever he grasped the essence, he happily forgot to eat.", "hanViet": "Hảo độc thư bất cầu thậm giải"}]),

    (12, "v2", "r12_05_taoyuanming_yinjiu", "陶淵明《飲酒·其五》", "Đào Uyên Minh - Ẩm Tửu Kỳ 5", "Tao Yuanming: Drinking Wine Poem V", "陶淵明", "Đào Uyên Minh", "東晉", "Đông Tấn",
     "結廬在人境，而無車馬喧。問君何能爾？心遠地自偏。採菊東籬下，悠然見南山。山氣日夕佳，飛鳥相與還。此中有真意，欲辨已忘言。",
     "在人世間建造茅廬，卻聽不到世俗車馬喧囂。何以能做到如此？只要心境超遠所處之地自然偏遠清幽。東籬採菊悠然望見南山，山林夕照飛鳥相伴歸巢，此中蘊含天地真意，欲加言說已忘卻語言。",
     "I built my hut within men's realm, yet hear no noise of horse and carriage. How can this be? When the heart is distant, one's place is quiet. Plucking chrysanthemums by the eastern hedge, serenely I gaze on South Mountain.",
     "中國田園詩最高峰，「採菊東籬下，悠然見南山」營造天人合一、心物兩融之極致寧靜審美境界。",
     "【漢越音考證】飲 (Ẩm), 廬 (Lư), 籬 (Ly), 悠 (Du), 辨 (Biện).",
     [{"viet": "Thải cúc đông ly hạ, du nhiên kiến Nam Sơn.", "zh": "採菊東籬下，悠然見南山。", "en": "Plucking chrysanthemums by the eastern fence, leisurely I catch sight of the Southern Mountain.", "hanViet": "Thải cúc đông ly hạ"}]),

    # Round 13: 南北朝辭賦與志怪筆記
    (13, "v2", "r13_01_baozhao_wucheng", "鮑照《蕪城賦》", "Bào Chiếu - Vũ Thành Phú", "Bao Zhao: Rhapsody on the Ruined City", "鮑照", "Bào Chiếu", "南朝·宋", "Nam Triều - Tống",
     "沵沵平原，積石連階。出有直廬，入有邃宇。當昔全盛之時，車掛轊，人駕肩，潺潺湲湲，轔轔殷殷。一朝兵火，繁華落盡。稜棱霜氣，蔌蔌風威。木葉委積，草蔓荒榛。孤蓬自振，客心自酸。富貴安在？唯餘荒壈。",
     "鮑照登廣陵廢城撫今追昔。追憶昔日繁華萬商雲集，對比今日荒草雜木孤蓬蕭條，發出興衰無常之深沉歷史喟嘆。",
     "Once prosperous with carriages touching hubs and shoulder to shoulder crowds; now fallen into ruin under frost and wind. Where are past wealth and honors?",
     "南朝駢賦悼古名篇，音律悲壯辭彩激越，深刻揭示戰亂之慘烈與歷史興亡交替之無情。",
     "【漢越音考證】鮑 (Bào), 照 (Chiếu), 蕪 (Vũ), 邃 (Thúy), 轔 (Lân), 榛 (Trăn).",
     [{"viet": "Khôi khôi hoang lũng, cô bồng tự chấn, khách tâm tự toan.", "zh": "孤蓬自振，客心自酸。富貴安在？", "en": "Lonely tumbleweeds roll in wind, the traveler's heart aches. Where is glory now?", "hanViet": "Cô bồng tự chấn"}]),

    (13, "v2", "r13_02_jiangyan_biefu", "江淹《別賦》", "Giang Yêm - Biệt Phú", "Jiang Yan: Rhapsody on Farewell", "江淹", "Giang Yêm", "南朝·梁", "Nam Triều - Lương",
     "黯然銷魂者，唯別而已矣！況秦吳兮絕國，復燕宋兮千里。或春苔兮始生，乍秋風兮暫起。征夫悵望，遊子悁邑。下有紅地，上有青天。引領長懷，愴悢何極！故別雖一體，各相萬殊：有富貴之別，有怨毒之別，有俠客之別，有死生之別。",
     "令人極度感傷銷魂者，唯有離別而已！江淹歷數遊子遠征、富貴相隔、俠客訣別、夫妻生離死別諸般情態，極寫人間離愁別緒。",
     "What causes the heart to wither with sorrow is parting and parting alone! Between green earth and blue sky, boundless grief overflows.",
     "南朝抒情駢賦之頂峰，「黯然銷魂者，唯別而已矣」成為描寫人間離別情感之千古絕唱名句。",
     "【漢越音考證】淹 (Yêm), 黯 (Ảm), 銷 (Tiêu), 魄 (Phách), 魂 (Hồn), 悵 (Trướng), 愴 (Sảng).",
     [{"viet": "Ảm nhiên tiêu hồn giả, duy biệt nhi dĩ hĩ!", "zh": "黯然銷魂者，唯別而已矣！", "en": "What drains the soul in sorrow is parting and parting alone!", "hanViet": "Ảm nhiên tiêu hồn giả"}]),

    (13, "v2", "r13_03_jiangyan_henfu", "江淹《恨賦》", "Giang Yêm - Hận Phú", "Jiang Yan: Rhapsody on Resentment", "江淹", "Giang Yêm", "南朝·梁", "Nam Triều - Lương",
     "至如秦帝按劍，楚王懷恨。高祖長枕，武帝傷魂。趙王幽閉，李陵降胡。自古皆有死，莫不含恨以終。試望料理，聊借筆端。玉顏消歇，長夜未旦。至人何有，至情何息！",
     "江淹歷述秦始皇、楚懷王、漢武帝、趙王遷、李陵等帝王將相與紅顏佳人生平未遂之憾，寫盡千古英雄長恨與命運弄人之悲情。",
     "From emperors to generals and fair maidens, all meet death carrying unfulfilled sorrows across eternity.",
     "與《別賦》雙峰並峙，鋪陳跌宕氣勢磅礴，抒寫人類面對命運局限與生死遺恨之深刻悲劇意識。",
     "【漢越音考證】恨 (Hận), 枕 (Chẩm), 幽 (U), 降 (Hàng), 顏 (Nhan).",
     [{"viet": "Tự cổ giai hữu tử, mạc bất hàm hận dĩ chung.", "zh": "自古皆有死，莫不含恨以終。", "en": "Since ancient times all must die, and none without harboring sorrow at the end.", "hanViet": "Hàm hận dĩ chung"}]),

    (13, "v2", "r13_04_ganbao_soushenji", "幹寶《搜神記·干將莫邪》", "Cán Bảo - Sưu Thần Ký - Can Tương Mạc Da", "Gan Bao: In Search of the Supernatural", "幹寶", "Cán Bảo", "東晉", "Đông Tấn",
     "楚干將、莫邪為楚王作劍，三年乃成。楚王怒，殺干將。莫邪生子名赤。赤長大，知父死因，誓報父仇。客謂赤曰：「聞王購子頭千金，將子頭與劍來，為子報之。」赤即自刎，雙手奉頭及劍以與客。客進頭於楚王，烹之湯鑊，頭沸出湯中，目瞋怒。客拔劍刺王，王頭墮沸湯，客自刎其頭，三首俱爛於湯中，不可分，遂分葬之，號曰「三王墓」。",
     "楚王殘殺鑄劍大師干將，赤兒為報父仇自刎獻頭與客。俠客設計湯鑊刺殺楚王後自刎，三首合葬號為三王墓。",
     "Chizi cut off his own head to entrust it to a brave knight to avenge his father against the tyrant king.",
     "古代志怪小說傑作，頌揚下層平民視死如歸報父仇之俠烈氣節與反抗暴君統治之悲壯抗爭。",
     "【漢越音考證】搜 (Sưu), 神 (Thần), 幹 (Cán), 寶 (Bảo), 莫 (Mạc), 邪 (Da / Tà), 鑊 (Hoạch).",
     [{"viet": "Xích tức tự vẫn, song thủ phụng đầu cập kiếm dĩ dữ khách.", "zh": "赤即自刎，雙手奉頭及劍以與客。", "en": "Chizi cut his throat and presented his head and sword with both hands to the knight.", "hanViet": "Tam vương mộ"}]),

    (13, "v2", "r13_05_liuyiqing_shishuoxinyu", "劉義慶《世說新語·詠雪》", "Lưu Nghĩa Khánh - Thế Thuyết Tân Ngữ - Vịnh Tuyết", "Liu Yiqing: A New Account of Tales of the World", "劉義慶", "Lưu Nghĩa Khánh", "南朝·宋", "Nam Triều - Tống",
     "謝太傅寒雪日內集，與兒女講論文義。俄而雪驟，公欣然曰：「白雪紛紛何所似？」兄子胡兒曰：「撒鹽空中差可擬。」兄女曰：「未若柳絮因風起。」公大笑樂。即公大兄無奕女，左將軍王凝之妻也。",
     "謝安寒雪天與子姪論文。雪下急，謝安問白雪何所似？姪兒謝朗曰「撒鹽空中」，才女謝道韞詠曰「未若柳絮因風起」，謝安大喜。",
     "Xie An asked: 'What is this fluttering snow like?' His nephew said: 'Salt tossed in air.' His niece Xie Daoyun said: 'Better say willow catkins rising in the wind!'",
     "「未若柳絮因風起」成為千古流傳之詠雪名句，謝道韞以此被譽為才女代表「詠絮之才」。",
     "【漢越音考證】義 (Nghĩa), 慶 (Khánh), 絮 (Thứ), 擬 (Nghĩ), 驟 (Sậu), 凝 (Ngưng).",
     [{"viet": "Bạch tuyết phân phân hà sở tự? Vị nhược liễu thứ nhân phong khởi.", "zh": "白雪紛紛何所似？未若柳絮因風起。", "en": "What is this whirling white snow like? Rather like willow catkins rising on the wind.", "hanViet": "Vị nhược liễu thứ nhân phong khởi"}]),

    # Round 14: 文心雕龍與水經駢儷
    (14, "v2", "r14_01_liuxie_wenxin_yuandao", "劉勰《文心雕龍·原道》", "Lưu Hiệp - Văn Tâm Điêu Long - Nguyên Đạo", "Liu Xie: The Literary Mind and the Carving of Dragons", "劉勰", "Lưu Hiệp", "南朝·梁", "Nam Triều - Lương",
     "文之為德也大矣，與天地並生者何哉？夫玄黃色雜，方圓體分，日月疊璧，以垂麗天之象；山川煥綺，以鋪理地之形。此蓋道之文也。仰觀吐曜，俯察含章，高卑定位，故兩儀既生矣。惟人參之，性靈所鍾，是謂三才。心生而言立，言立而文明，自然之道也。",
     "文章的本質是何等偉大，它與天地共生。日月星辰為天之文，山川林泉為地之文。人為萬物之靈，心有所感化為言語文章，此乃自然之大道。",
     "Literary expression is great indeed, born alongside Heaven and Earth! When heart feels, words arise; when words arise, civilization shines.",
     "劉勰《文心雕龍》開宗明義第一篇，將文學根源提升至宇宙自然大道本體高度，奠定中國文論哲學基礎。",
     "【漢越音考證】勰 (Hiệp), 雕 (Điêu), 龍 (Long), 曜 (Diệu), 璧 (Bích), 綺 (Khởi / Ỷ), 靈 (Linh).",
     [{"viet": "Tâm sinh nhi ngôn lập, ngôn lập nhi văn minh, tự nhiên chi đạo dã.", "zh": "心生而言立，言立而文明，自然之道也。", "en": "Mind generates words, words create culture: such is the way of Nature.", "hanViet": "Tâm sinh nhi ngôn lập"}]),

    (14, "v2", "r14_02_liuxie_wenxin_shensi", "劉勰《文心雕龍·神思》", "Lưu Hiệp - Văn Tâm Điêu Long - Thần Tư", "Liu Xie: The Literary Mind - Spiritual Thought", "劉勰", "Lưu Hiệp", "南朝·梁", "Nam Triều - Lương",
     "古人云：「形在江海之上，心存魏闕之下。」神思之謂也。文之思也，其神遠矣。故寂然凝慮，思接千載；悄然動容，視通萬里；吟詠之間，吐納珠玉之聲；眉睫之前，卷舒風雲之色；其思理之致乎！故思理為妙，神與物遊。",
     "創作時的藝術思維其神妙無遠弗屆。凝神靜慮時思緒接通千載歲月，悄然動情時目光通達萬里之遙，神與物遊，胸中卷舒風雲變幻。",
     "Spiritual contemplation reaches far into eternity and across ten thousand miles. When imagination flows, spirit roams free with creation.",
     "系統論述藝術想像與靈感構思（神思）規律，提出「思接千載、視通萬里、神與物遊」之經典美學範疇。",
     "【漢越音考證】凝 (Ngưng), 慮 (Lự), 睫 (Tiệp), 納 (Nạp), 珠 (Châu), 玉 (Ngọc).",
     [{"viet": "Tịch nhiên ngưng lự, tư tiếp thiên tải; tiêu nhiên động dung, thị thông vạn lý.", "zh": "寂然凝慮，思接千載；悄然動容，視通萬里。", "en": "In quiet contemplation thought spans a thousand years; in stirred emotion vision reaches ten thousand miles.", "hanViet": "Tư tiếp thiên tải thị thông vạn lý"}]),

    (14, "v2", "r14_03_zhongrong_shipin", "鍾嶸《詩品·序》", "Chung Vanh - Thi Phẩm Tự", "Zhong Rong: Evaluation of Poetry Preface", "鍾嶸", "Chung Vanh", "南朝·梁", "Nam Triều - Lương",
     "氣之動物，物之感人，故搖蕩性情，形諸舞詠。照燭三才，暉麗萬有，靈祇待之以致饗，幽微藉之以不朽。動天地，感鬼神，莫近於詩。至如春風春鳥，秋月秋蟬，夏雲暑雨，冬月祁寒，斯四時之感諸詩者也。嘉會寄詩以長歡，離群託詩以寫怨。使窮賤易安，幽居靡悶，莫尚於詩矣。",
     "大自然氣候推移萬物感發人心，動盪性情化為詩歌。詩能通鬼神動天地，寫歡寫怨，使窮者安幽居者不悶，文學力量無可比擬。",
     "Nature moves things, things stir man's emotions, expressed in song and verse. Nothing moves heaven and earth like poetry!",
     "鍾嶸《詩品》確立五言詩源流系譜與品評標準，強調「直尋自然之美、吟詠情性」，反對過度用典排偶。",
     "【漢越音考證】鍾 (Chung), 嶸 (Vanh), 品 (Phẩm), 祇 (Kỳ), 饗 (Hưởng), 蟬 (Thiền).",
     [{"viet": "Động thiên địa, cảm quỷ thần, mạc cận ư thi.", "zh": "動天地，感鬼神，莫近於詩。", "en": "To move heaven and earth and stir spirits, nothing comes closer than poetry.", "hanViet": "Động thiên địa cảm quỷ thần"}]),

    (14, "v2", "r14_04_lidaoyuan_shuijingzhu", "酈道元《水經注·三峽》", "Lệ Đạo Nguyên - Thủy Kinh Chú - Tam Hiệp", "Li Daoyuan: Commentary on the Water Classic", "酈道元", "Lệ Đạo Nguyên", "北魏", "Bắc Ngụy",
     "自三峽七百里中，兩岸連山，略無闕處。重巖疊嶂，隱天蔽日，自非亭午夜分，不見曦月。至於夏水襄陵，沿溯阻絕。或王命急宣，有時朝發白帝，暮到江陵，其間千二百里，雖乘奔御風，不以疾也。春冬之時，則素湍綠潭，迴清倒影。絕巘多生怪柏，懸泉瀑布，飛漱其間，清榮峻茂，良多趣味。",
     "三峽七百里兩岸群山連綿無闕，重巖疊嶂隱天蔽日。夏水迅疾朝發白帝暮到江陵千二百里。春冬素湍綠潭懸泉瀑布，清榮峻茂趣味無窮。",
     "Throughout the Seven Hundred Li of the Three Gorges, mountains rise unbroken on both sides. In summer water races swiftly from Baidi to Jiangling!",
     "地理巨著與山水散文之瑰寶，文字精雕細琢音韻鏗鏘，將三峽四季山川風貌刻畫得淋漓盡致。",
     "【漢越音考證】酈 (Lệ), 峽 (Hiệp), 嶂 (Chướng), 曦 (Hi), 襄 (Tương), 溯 (Tố), 湍 (Thoan).",
     [{"viet": "Tố thoan lục đàm, hồi thanh đảo ảnh. Tuyệt ngạn đa sinh quái bách, huyền tuyền bộc bố, phi sấu kỳ gian.", "zh": "素湍綠潭，迴清倒影。懸泉瀑布，飛漱其間，清榮峻茂，良多趣味。", "en": "White rapids and green pools reflect jade shadows; cascading waterfalls rush among grotesque pines.", "hanViet": "Tố thoan lục đàm"}]),

    (14, "v2", "r14_05_qiuchi_chenbozhi", "丘遲《與陳伯之書》", "Khâu Trì - Dữ Trần Bá Chi Thư", "Qiu Chi: Letter to Chen Bozhi", "丘遲", "Khâu Trì", "南朝·梁", "Nam Triều - Lương",
     "暮春三月，江南草長，雜花生樹，群鶯亂飛。見故國之旗鼓，感平生於疇日，撫弦登陴，豈不愴悢！所以廉頗思趙，吳起泣西河，人之情也。將軍獨無情哉？想早勵良規，自求多福。棄燕雀之小志，慕鴻鵠以高翔！",
     "丘遲致信投魏叛將陳伯之以情動人：暮春三月江南草長雜花生樹群鶯亂飛，故國風物豈不動心！廉頗思趙吳起泣西河，速歸梁朝自求多福。",
     "In the late spring's third month, grass grows lush in Jiangnan, diverse blossoms mantle the trees and orioles flutter in chorus. How can you not long for home?",
     "南朝駢文勸降第一名篇，「暮春三月，江南草長，雜花生樹，群鶯亂飛」傳誦千古，陳伯之見信即刻率眾歸降。",
     "【漢越音考證】遲 (Trì), 伯 (Bá), 陴 (Tì), 廉 (Liêm), 頗 (Pha), 鶯 (Oanh), 鵠 (Hộc).",
     [{"viet": "Mộ xuân tam nguyệt, Giang Nam thảo trường, tạp hoa sinh thụ, quần oanh loạn phi.", "zh": "暮春三月，江南草長，雜花生樹，群鶯亂飛。", "en": "In late spring's third month, grass grows tall in Jiangnan, flowers bloom across trees and orioles fly in flock.", "hanViet": "Mộ xuân tam nguyệt"}]),
]

print(f"Volume 2 items ready: {len(vol2_items)}")
