# -*- coding: utf-8 -*-
"""Volume 5: 明清散文、小品與古典小說名著精華 (Rounds 29-35, 35 works)"""

vol5_items = [
    # Round 29: 明代散文與小品
    (29, "v5", "r29_01_guiyouguang_xiangjixuan", "歸有光《項脊軒志》", "Quy Hữu Quang - Hạng Tích Hiên Chí", "Gui Youguang: Records of Xiangji Pavilion", "歸有光", "Quy Hữu Quang", "明代", "Minh",
     "項脊軒，舊南閣子也。室僅方丈，可容一人居。百年老屋，塵泥滲漉，雨澤下注；每移案，顧視無可置者。余稍為修葺，使不上漏。前闢四窗，垣牆周庭，以當南日，日影反照，室始洞然。借書滿架，偃仰嘯歌，冥然兀坐，萬籟有聲；而庭階寂寂，小鳥時來啄食，人至不去。三五之夜，明月半牆，桂影斑駁，風移影動，珊珊可愛。後五年，吾妻來歸，時至軒中，從余問古事，或憑几學書。吾妻歸寧，述諸小妹語曰：「聞姊家有閣子，且何謂閣子也？」其後六年，吾妻死，室壞不修。其後二年，余久臥病無聊，乃使人復葺南閣子，其制稍異於前。然自後余多在外，不常居。庭有枇杷樹，吾妻死之年所手植也，今已亭亭如蓋矣。",
     "項脊軒一室之內寄託對祖母、母親與亡妻深沉思念。庭院借書滿架明月半牆桂影斑駁。結尾「庭有枇杷樹，吾妻死之年所手植也，今已亭亭如蓋矣」言有盡而意無窮，成千古悼亡絕唱。",
     "In the courtyard stands a loquat tree, planted by my wife with her own hands the year she died; today it has grown tall and graceful, overarching like a green canopy.",
     "明代散文大家歸有光以平易細膩之筆記家常細故，情真意切動人心魄，開闢明清抒情散文最高殿堂。",
     "【漢越音考證】歸 (Quy), 軒 (Hiên), 葺 (Thấp), 籟 (Lại), 斑 (Ban), 駁 (Bác), 枇 (Tì), 杷 (Bà).",
     [{"viet": "Đình hữu tỳ bà thụ, ngô thê tử chi niên sở thủ thực dã, kim dĩ đình đình như cái hĩ.", "zh": "庭有枇杷樹，吾妻死之年所手植也，今已亭亭如蓋矣。", "en": "In the courtyard stands a loquat tree, planted by my wife's hand in the year she passed away; today it stands tall and graceful like an open canopy.", "hanViet": "Đình hữu tỳ bà thụ"}]),

    (29, "v5", "r29_02_zhangdai_huxinting", "張岱《陶庵夢憶·湖心亭看雪》", "Trương Đại - Đào Am Mộng Ức - Hồ Tâm Đình Khán Tuyết", "Zhang Dai: Viewing Snow at Mid-Lake Pavilion", "張岱", "Trương Đại", "明末清初", "Minh Mạt Thanh Sơ",
     "崇禎五年十二月，余住西湖。大雪三日，湖中人鳥聲俱絕。是日更定矣，余拏一小舟，擁毳衣爐火，獨往湖心亭看雪。霧凇沆碭，天與雲與山與水，上下一白。湖上影子，惟長堤一痕、湖心亭一點、與余舟一芥、舟中人兩三粒而已。到亭上，有兩人鋪氈對坐，一童子燒酒爐正沸。見余，大喜曰：「湖中焉得更有此人！」拉余同飲。余強飲三大白而別。問其姓氏，是金陵人，客此。及下船，舟子喃喃曰：「莫說相公癡，更有癡似相公者！」",
     "崇禎五年大雪三日西湖萬籟俱寂。張岱深夜獨舟往湖心亭看雪。霧凇沆碭天地一白，長堤一痕湖心亭一點舟一芥人兩三粒。遇金陵客偶會暢飲，舟子嘆「莫說相公癡，更有癡似相公者！」",
     "The mist-frost was thick and boundless: sky, clouds, mountains, and water were all one vast expanse of white. On the lake the only shadows were the long causeway as a faint line, the Pavilion as a dot, my boat as a mustard seed, and the two or three men inside as specks of grain!",
     "晚明小品文最高傑作，白描如水墨大寫意，寄託故國殘夢之深沉亡國遺民孤憤情懷。",
     "【漢越音考證】岱 (Đại), 庵 (Am), 拏 (Nao), 毳 (Thúy), 凇 (Tùng), 沆 (Hãng), 碭 (Đãng), 芥 (Giới).",
     [{"viet": "Vụ tùng hãng đãng, thiên dữ vân dữ sơn dữ thủy, thượng hạ nhất bạch. Hồ thượng ảnh tử, duy trường đê nhất ngân, hồ tâm đình nhất điểm, dữ dư chu nhất giới, chu trung nhân lưỡng tam lạp nhi dĩ.", "zh": "霧凇沆碭，天與雲與山與水，上下一白。湖上影子，惟長堤一痕、湖心亭一點、與余舟一芥、舟中人兩三粒而已。", "en": "Mist-frost was vast; sky, clouds, mountains and water merged into pure white. Shadows on the lake were merely a trace of the long dike, a dot of the pavilion, a mustard seed of my boat, and two or three grains of people within.", "hanViet": "Vụ tùng hãng đãng thượng hạ nhất bạch"}]),

    (29, "v5", "r29_03_yuanhongdao_wanxiang", "袁宏道《晚遊六橋待月記》", "Viên Hoằng Đạo - Vãn Du Lục Kiều Đãi Nguyệt Ký", "Yuan Hongdao: Evening Walk on Six Bridges", "袁宏道", "Viên Hoằng Đạo", "明代", "Minh",
     "西湖最盛，為春為月。一日之盛，為朝煙，為夕嵐。今歲春雪甚盛，梅花為寒所勒，與杏桃相次開發，尤為奇觀。石簣數為余言：「傅金吾園中梅，張功甫家故物也，急往觀之！」余時為桃花所戀，竟不忍去。湖上由斷橋至蘇堤一帶，綠煙紅霧，彌漫二十餘里。歌吹為風，粉汗為雨，羅紈之盛，多於堤畔之草，艷冶極矣。然杭人遊湖，止午、未、申三時；其實湖光染翠之工，山嵐設色之妙，皆在朝日始出，夕舂未下，始極其濃媚。月景尤不可言，花態柳情，山容水意，別是一種趣味。此樂留與山僧遊客受用，安可為俗士道哉！",
     "公安派袁宏道獨賞西湖春夜美景：綠煙紅霧瀰漫二十里。杭人遊湖止於午後喧囂，唯有朝日夕嵐與深夜月景花態柳情別具幽趣，留與山僧雅士獨享。",
     "West Lake is at its most magnificent in spring and under moonlight. The morning mist and evening glow, the moon over blossoms and willows possess a transcendent charm reserved for enlightened souls, not for worldly minds!",
     "晚明「公安派」性靈說代表作，倡導「獨抒性靈，不拘格套」，呈現擺脫理學束縛之自由清新審美情趣。",
     "【漢越音考證】宏 (Hoằng), 嵐 (Lam), 簣 (Quỹ), 紈 (Hoàn), 冶 (Dã), 舂 (Dung).",
     [{"viet": "Tây Hồ tối thịnh, vi xuân vi nguyệt. Nhất nhật chi thịnh, vi triêu yên, vi tịch lam.", "zh": "西湖最盛，為春為月。一日之盛，為朝煙，為夕嵐。", "en": "West Lake is at its fullest glory in spring and under moonlight. A single day's finest hours are in morning mist and evening vapor.", "hanViet": "Tây Hồ tối thịnh vi xuân vi nguyệt"}]),

    (29, "v5", "r29_04_liuji_maiganzhe", "劉基《郁離子·賣柑者言》", "Lưu Cơ - Úc Ly Tử - Mại Cam Giả Ngôn", "Liu Ji: Words of the Citrus Seller", "劉基", "Lưu Cơ", "元末明初", "Nguyên Mạt Minh Sơ",
     "杭有賣果者，善藏柑，涉寒暑不潰。出之燁然，玉質而金色。置於市，賈十倍，人爭鬻之。予買而觀之，剖其中，乾若敗絮。予怪而問之曰：「若所市於人者，將以實籩豆，奉祭祀，供賓客乎？將衒外以惑愚瞽也？甚矣哉，為欺也！」賣者笑曰：「吾業是有年矣。今當世之武將，佩虎符坐白虎節，果能效孫吳之略乎？文臣端委佩紫，果能建伊皋之業乎？觀其坐高堂，騎大馬，醉醇醴而飫肥鮮者，孰不巍巍乎可畏，赫赫乎可象也？又何往而不金玉其外，敗絮其中也哉！今子是之不察，而以察吾柑！」予默然無以應。",
     "杭州賣柑者所藏柑橘外表光鮮金黃，剖開內裡如腐爛棉絮。賣柑者反唇相譏：今之文臣武將身居高位食厚祿，何嘗不是「金玉其外，敗絮其中」！劉基默然深省。",
     "The citrus looked golden and splendid outside, but cut open it was rotten cotton! The seller laughed: 'Look at today's generals and ministers: which of them is not golden jade without, but rotten fluff within!'",
     "「金玉其外，敗絮其中」為千古諷刺名言，劉伯溫借寓言深刻揭露元末統治者虛有其表腐朽無能之社會本質。",
     "【漢越音考證】基 (Cơ), 郁 (Úc), 柑 (Cam), 燁 (Diệp), 鬻 (Dục), 絮 (Thứ), 瞽 (Cổ).",
     [{"viet": "Kim ngọc kỳ ngoại, bại thứ kỳ trung.", "zh": "金玉其外，敗絮其中。", "en": "Golden jade on the outside, rotten lint on the inside.", "hanViet": "Kim ngọc kỳ ngoại bại thứ kỳ trung"}]),

    (29, "v5", "r29_05_songlian_songdongyang", "宋濂《送東陽馬生序》", "Tống Liêm - Tống Đông Dương Mã Sanh Tự", "Song Lian: Preface for Student Ma of Dongyang", "宋濂", "Tống Liêm", "明代", "Minh",
     "余幼時即嗜學。家貧，無從致書以觀，每假借於藏書之家，手自筆錄，計日以還。天大寒，硯冰堅，手指不可屈伸，弗之怠。錄畢，走送之，不敢稍踰約。以是人多以書假余，余因得遍觀群書。既加冠，益慕聖賢之道。又患無碩師名人與遊，嘗趨百里外從鄉之先達執經叩問。先達德隆望尊，門人弟子填其室，未嘗稍降辭色。余立侍左右，援疑質理，俯身傾耳以請；或遇其叱咄，色愈恭，禮愈至，不敢出一言以復；俟其欣悅，則又請焉。故余雖愚，卒獲有所聞。今諸生學於太學，衣食豐足，無凍餒之患，無奔走之勞，若業有不精，德有不成，非天質之卑，則心不若余之專耳，豈他人之過哉！",
     "明初大儒宋濂回顧早年求學刻苦艱辛：家貧抄書硯冰指僵不敢逾期，負篋跋涉百里求教名師立侍恭謹。勉勵太學諸生珍惜優越環境專心向學。",
     "In youth I hungered for learning. Borrowing books and copying by hand when ink froze solid, walking a hundred miles through blizzards to consult master scholars with utmost humility.",
     "古代勉學名篇，宋濂以親身求學經歷感召後進，展現勤勉堅毅、尊師重道、刻苦自礪之崇高治學精神。",
     "【漢越音考證】濂 (Liêm), 嗜 (Thị), 硯 (Nghiên), 冠 (Quan), 碩 (Thạc), 叱 (Sất), 咄 (Đốt), 餒 (Nỗi).",
     [{"viet": "Dư ấu thời tức thị học. Gia bần, vô tòng trí thư dĩ quan, mỗi giả tá ư tàng thư chi gia, thủ tự bút lục, kế nhật dĩ hoàn.", "zh": "余幼時即嗜學。家貧，無從致書以觀，每假借於藏書之家，手自筆錄，計日以還。", "en": "Since youth I loved learning; being poor with no books, I borrowed from collectors, transcribing with my own brush and returning on promised days.", "hanViet": "Dư ấu thời tức thị học"}]),

    # Round 30: 三國演義
    (30, "v5", "r30_01_sanguo_juan首", "羅貫中《三國演義·卷首詞(臨江仙)》", "La Quán Trung - Tam Quốc Diễn Nghĩa - Lâm Giang Tiên", "Romance of the Three Kingdoms: Opening Ode", "楊慎 / 羅貫中", "La Quán Trung / Dương Thận", "明代", "Minh",
     "滾滾長江東逝水，浪花淘盡英雄。是非成敗轉頭空。青山依舊在，幾度夕陽紅。白髮漁樵江渚上，慣看秋月春風。一壺濁酒喜相逢。古今多少事，都付笑談中。",
     "滾滾長江東流浪花淘盡無數三國英雄。是非成敗轉頭皆成空，唯青山依舊落日夕陽幾度染紅。白髮漁夫樵夫慣看秋月春風，相逢一壺濁酒，古今萬千興亡事盡付笑談之中。",
     "The surging Yangtze River flows east, its waves scouring away all heroic souls. Right and wrong, success and defeat turn to void in a fleeting turn. Green hills remain as before; how many times have evening suns glowed red? How many affairs of past and present are all shared over smiling conversation!",
     "三國演義卷首詞，以博大蒼茫之宇宙歷史情懷總結三國英雄興亡，為中國古典小說史上最著名之開篇名曲。",
     "【漢越音考證】演 (Diễn), 義 (Nghĩa), 逝 (Thệ), 樵 (Tiều), 渚 (Chử), 濁 (Trục).",
     [{"viet": "Cổn cổn Trường Giang đông thệ thủy, lãng hoa đào tận anh hùng. Thị phi thành bại chuyển đầu không. Thanh sơn y cựu tại, kỷ độ tịch dương hồng.", "zh": "滾滾長江東逝水，浪花淘盡英雄。是非成敗轉頭空。青山依舊在，幾度夕陽紅。", "en": "The surging Yangtze rolls eastward, its waves washing away all heroes. Right and wrong, victory and defeat vanish in a turn. Green hills remain as ever; how many crimson sunsets have passed!", "hanViet": "Cổn cổn Trường Giang đông thệ thủy"}]),

    (30, "v5", "r30_02_sanguo_taoyuan", "羅貫中《三國演義·桃園三結義》", "La Quán Trung - Đào Viên Tam Kết Nghĩa", "Three Kingdoms: Oath of the Peach Garden", "羅貫中", "La Quán Trung", "明代", "Minh",
     "劉焉出榜招軍。玄德看了長嘆，張飛厲聲曰：「大丈夫不與國家出力，何故長嘆？」玄德遂言心志。三人入村店飲酒，關羽亦至。三人志同道合，張飛曰：「吾莊後有一桃園，花開正盛。明日當於園中祭告天地，我三人結為兄弟，協力同心，然後可圖大事。」次日，於桃園中，備黑牛白馬祭禮等項，三人焚香再拜而說誓曰：「念劉備、關羽、張飛，雖然異姓，既結為兄弟，則同心協力，救困扶危；上報國家，下安黎庶。不求同年同月同日生，只願同年同月同日死。皇天后土，實鑒此心，背義忘恩，天人共戮！」誓畢，拜玄德為兄，關羽次之，張飛為弟。",
     "劉備關羽張飛桃園焚香結義：同心協力救困扶危上報國家下安黎庶。不求同年同月同日生只願同年同月同日死。忠肝義膽萬古流芳。",
     "Liu Bei, Guan Yu and Zhang Fei swore brotherhood in the Peach Garden: 'We three, of different surnames, unite as brothers with one heart to rescue the distressed and protect the state. We seek not to be born on the same day, but vow to die on the same day!'",
     "「桃園結義」確立《三國演義》崇尚「義」字之精神靈魂，成為東亞忠義結拜文化與民間信仰之最高原型典範。",
     "【漢越音考證】備 (Bị), 羽 (Vũ), 飛 (Phi), 桃 (Đào), 誓 (Thệ), 戮 (Lục).",
     [{"viet": "Bất cầu đồng niên đồng nguyệt đồng nhật sinh, chỉ nguyện đồng niên đồng nguyệt đồng nhật tử.", "zh": "不求同年同月同日生，只願同年同月同日死。", "en": "We ask not to have been born on the same day, but we vow to die together on the same day.", "hanViet": "Bất cầu đồng niên đồng nguyệt đồng nhật sinh"}]),

    (30, "v5", "r30_03_sanguo_zhujiulun", "羅貫中《三國演義·煮酒論英雄》", "La Quán Trung - Chử Tửu Luận Anh Hùng", "Three Kingdoms: Discussing Heroes over Warm Wine", "羅貫中", "La Quán Trung", "明代", "Minh",
     "操引玄德至小亭，青梅已熟，煮酒正沸。二人對坐暢飲。操指天外龍雲曰：「龍能大能小，能升能隱；大則興雲吐霧，小則隱介藏形；升則飛騰於宇宙之間，隱則潛伏於波濤之內。方今春深，龍乘時變化，猶人得志而縱橫四海。龍之為物，可比世之英雄。玄德久歷四方，必知當世英雄。請試指言之。」玄德歷數袁術、袁紹、劉表、孫策、劉璋、張繡等人。操皆撫掌笑曰：「塚中枯骨，何足道哉！」玄德曰：「舍此之外，備實不知。」操以手指玄德，後自指，曰：「今天下英雄，惟使君與操耳！」玄德聞言，吃了一驚，手中所執匙箸，不覺落於地下。時正值天雨將至，雷聲大作。玄德乃從容俯首拾箸曰：「一震之威，乃至於此。」操笑曰：「丈夫亦畏雷乎？」玄德曰：「聖人迅雷風烈必變，安得不畏？」將聞言失箸緣由，輕輕掩飾過了。操遂不疑玄德。",
     "曹操煮酒論英雄，以神龍騰雲為喻，否定袁紹袁術諸侯為塚中枯骨，斷言「今天下英雄惟使君與操耳！」劉備驚落匙箸借雷聲巧妙掩飾，深沉大智。",
     "Cao Cao warmed green plum wine and said: 'Dragon rises soaring across cosmos like a hero fulfilling ambition. Today's true heroes under Heaven are only you and I!' Liu Bei dropped his chopsticks in shock, deftly covering with fear of thunder.",
     "古典小說性格對話與心理博弈之巔峰神來之筆，曹操霸氣雄才與劉備韜光養晦刻畫得入木三分。",
     "【漢越音考證】煮 (Chử), 塚 (Trủng), 枯 (Khô), 箸 (Trợ), 匙 (Thì), 霆 (Đình).",
     [{"viet": "Kim thiên hạ anh hùng, duy Sử quân dữ Tháo nhĩ!", "zh": "今天下英雄，惟使君與操耳！", "en": "Today, the only heroes under Heaven are you, Sir, and I!", "hanViet": "Kim thiên hạ anh hùng duy Sử quân dữ Tháo nhĩ"}]),

    (30, "v5", "r30_04_sanguo_caochuan", "羅貫中《三國演義·草船借箭》", "La Quán Trung - Thảo Thuyền Tá Tiễn", "Three Kingdoms: Borrowing Arrows with Straw Boats", "羅貫中", "La Quán Trung", "明代", "Minh",
     "周瑜妒孔明之才，命十日內造十萬支箭。孔明立軍令狀三日可就。向魯肅借二十隻快船，每船以草人束縛，青布幔覆蓋。第三夜大霧垂江，孔明邀魯肅同舟往曹營取箭。船至曹軍水寨擂鼓吶喊，曹操疑有伏兵命萬弩齊發。草船一側受滿箭，孔明令調轉船頭受箭。霧散箭畢，每船獲箭五六千，二十隻船共得十餘萬支。孔明笑令軍士齊高呼：「謝曹丞相賜箭！」周瑜得知長嘆：「孔明神機妙算，吾不如也！」",
     "諸葛亮神機妙算知天文識地理，趁長江大霧駕草船受曹軍十萬雕翎箭。周瑜自嘆弗如徹底折服。",
     "Zhuge Liang sailed twenty straw-covered boats in dense river fog to Cao Cao's water fort, drumming and shouting. Cao Cao shot countless arrows into the straw, yielding over 100,000 arrows. Zhou Yu sighed: 'Kongming's divine intellect is far beyond mine!'",
     "草船借箭將諸葛亮通曉天文、洞悉敵情、神機妙算智絕天下之形象展現得淋漓盡致，千古傳為智謀美談。",
     "【漢越音考證】草 (Thảo), 船 (Thuyền), 借 (Tá), 箭 (Tiễn), 弩 (Nỏ / Nỗ), 霧 (Vụ).",
     [{"viet": "Khổng Minh thần cơ diệu toán, ngô sở bất như dã!", "zh": "孔明神機妙算，吾不如也！", "en": "Kongming's divine foresight and calculation are far beyond my reach!", "hanViet": "Khổng Minh thần cơ diệu toán"}]),

    (30, "v5", "r30_05_sanguo_kongcheng", "羅貫中《三國演義·空城計》", "La Quán Trung - Không Thành Kế", "Three Kingdoms: The Empty City Stratagem", "羅貫中", "La Quán Trung", "明代", "Minh",
     "孔明分撥已定，先引五千兵退守西城。忽報司馬懿引大軍十五萬蜂擁而來。孔明身邊無大將，城中止有二千五百軍士，眾官盡皆失色。孔明登城望之，傳令藏匿旗幟，大開四門，每一門用二十軍士扮作百姓，灑掃街道。孔明乃披鶴氅，戴綸巾，引二小童攜琴一張，憑欄而坐，焚香操琴。司馬懿前軍來到城下，見此模樣，不敢進。懿自策馬望之，見孔明坐於城樓之上，笑容可掬，焚香操琴，左有一童子手捧寶劍，右有一童子手執塵尾。城門內外，有二十餘百姓，低頭灑掃，旁若無人。懿看畢大疑，便教後軍作前軍，前軍作後軍，盡皆退去。次子司馬昭曰：「莫非諸葛亮無軍，故作此態？父親何故便退兵？」懿曰：「亮平生謹慎，不曾弄險。今大開城門，必有埋伏。我兵若進，中其計也。汝輩豈知？宜速退。」",
     "司馬懿率十五萬大軍壓境，西城兵微將寡。諸葛亮大開四門扮民灑掃，城樓焚香撫琴笑容可掬。司馬懿疑平生謹慎之孔明必有伏兵，倉皇退兵。孔明撫掌笑退大軍。",
     "With 150,000 enemy troops outside the gate, Zhuge Liang sat atop the open city wall wearing crane-feather cloak, playing his zither serenely. Sima Yi suspected an ambush and retreated in haste!",
     "空城計以膽識智慧退千軍萬馬，心理戰藝術之極致演繹，刻畫諸葛亮羽扇綸巾超凡入聖之神采。",
     "【漢越音考證】空 (Không), 城 (Thành), 計 (Kế), 氅 (Xưởng), 謹 (Cẩn), 慎 (Thận).",
     [{"viet": "Lượng bình sinh cẩn thận, bất tằng lộng hiểm. Kim đại khai thành môn, tất hữu mai phục.", "zh": "亮平生謹慎，不曾弄險。今大開城門，必有埋伏。", "en": "Zhuge Liang is cautious all his life and never takes rash risks. Now opening the gates wide, there must be an ambush!", "hanViet": "Lượng bình sinh cẩn thận"}]),
]

# Complete rounds 31-35
vol5_items.extend([
    # Round 31: 水滸傳
    (31, "v5", "r31_01_shuihu_yinshou", "施耐庵《水滸傳·引首》", "Thi Nại Am - Thủy Hử Truyện - Dẫn Thủ", "Water Margin: Opening Introduction", "施耐庵", "Thi Nại Am", "元末明初", "Nguyên Mạt Minh Sơ",
     "朱雀橋邊野草花，烏衣巷口夕陽斜。舊時王謝堂前燕，飛入尋常百姓家。試看書林隱處，幾多俊逸儒流。虛名薄利不需求，一卷梁山好漢傳，千載英雄俠義留！紛紛五代亂離間，一旦雲開復見天。草木蒙恩天雨露，梁山聚義英雄傳。",
     "水滸傳引首道出世態炎涼與歷史興亡。宋江等一百單八條梁山好漢替天行道、扶危濟困之宏偉英雄傳奇。",
     "Looking into the secluded forests of literature, heroes seek neither hollow fame nor petty profit, leaving behind timeless tales of Liangshan righteous brotherhood!",
     "《水滸傳》為中國英雄傳奇章回小說鼻祖，揭示「官逼民反、替天行道」之反封建壓迫深刻主題。",
     "【漢越音考證】水 (Thủy), 滸 (Hử), 施 (Thi), 庵 (Am), 梁 (Lương), 豪 (Hào), 俠 (Hiệp).",
     [{"viet": "Thế thiên hành đạo, cứu khốn phò nguy.", "zh": "替天行道，救困扶危。", "en": "Enforcing the Way on behalf of Heaven, rescuing the distressed and aiding the imperiled.", "hanViet": "Thế thiên hành đạo"}]),

    (31, "v5", "r31_02_shuihu_lutixia", "施耐庵《水滸傳·魯提轄拳打鎮關西》", "Thi Nại Am - Lỗ Đề Hạt Quyền Đả Trấn Quan Tây", "Water Margin: Lu Da Punishes Zheng the Butcher", "施耐庵", "Thi Nại Am", "元末明初", "Nguyên Mạt Minh Sơ",
     "魯提轄大踏步走入肉舖，戲弄鄭屠切碎肉、寸金軟骨。鄭屠大怒提刀撲來。魯達搶先一步，一拳正打在鼻子上，打得鮮血迸流，鼻子歪在半邊，卻便似開了個油醬鋪：鹹的、酸的、辣的一發都滾出來。第二拳打在眼眶際眉梢，打得眼棱縫裂，烏珠迸出，也似開了個彩帛鋪：紅的、黑的、紫的都綻將出來。第三拳正打在太陽穴上，卻似做了一個全堂水陸的道場：磬兒、鈸兒、鐃兒一齊響。見鄭屠挺在地上氣絕，魯達拔步便走，回頭指罵：「你詐死，灑家慢慢跟你理會！」大踏步揚長而去。",
     "魯智深打抱不平拳打惡霸鎮關西。三拳比喻絕妙（油醬鋪、彩帛鋪、水陸道場），除暴安良見義勇為，豪爽俠烈之氣躍然紙上。",
     "Lu Da struck the bully butcher with three mighty punches like opening a sauce shop, a silk shop, and a temple orchestra of cymbals! Seeing the bully dead, he strode away boldly shouting: 'You play dead, I shall settle with you later!'",
     "中國白話小說人物動作描寫最高範例，以生動詼諧之三度通感比喻刻畫魯智深豪俠正義性格。",
     "【漢越音考證】提 (Đề), 轄 (Hạt), 拳 (Quyền), 屠 (Đồ), 眶 (Khuông), 磬 (Khánh).",
     [{"viet": "Lỗ Đề hạt quyền đả Trấn Quan Tây, cứu khốn phò nguy trừ bạo ác.", "zh": "魯提轄拳打鎮關西，見義勇為除暴安良。", "en": "Lu Da punished Zheng the Butcher with righteous fists, eliminating evil to protect the innocent.", "hanViet": "Lỗ Đề hạt quyền đả Trấn Quan Tây"}]),

    (31, "v5", "r31_03_shuihu_wusong", "施耐庵《水滸傳·武松打虎》", "Thi Nại Am - Vũ Tùng Đả Hổ", "Water Margin: Wu Song Fights the Tiger", "施耐庵", "Thi Nại Am", "元末明初", "Nguyên Mạt Minh Sơ",
     "武松吃了十八碗透瓶香，不信景陽岡有吊額白睛大蟲，提梢棒上岡。酒力發作，臥在大石上欲睡。只聽得一聲狂風呼嘯，大蟲從半空撲下來。武松一驚，一閃閃在大蟲背後。大蟲一撲、一掀、一剪，氣力衰竭。武松雙手按住大蟲頂花皮，按在地上，提起鐵錘般大小拳頭，使盡平生力氣，連打五七十拳，打得大蟲眼裏口裏鼻裏鮮血迸出，動彈不得。名震天下景陽岡打虎英雄！",
     "武松景陽岡飲十八碗酒醉上山岡。赤手空拳大戰吊額白睛猛虎，避其一撲一掀一剪，連揮鐵拳斃虎成名，千古傳揚豪俠神勇。",
     "Wu Song drank eighteen bowls of wine and met the fierce white-browed tiger on Jingyang Ridge. Dodging its three leaps, he pinned its neck down with iron fists, striking until the beast lay slain!",
     "家喻戶曉之英雄神話，以緊湊動態節奏與寫實拳棒動作刻畫武松天神般之勇武與過人膽略。",
     "【漢越音考證】松 (Tùng), 岡 (Cương), 梢 (Shao / Tiêu), 錘 (Chùy), 額 (Ngạch).",
     [{"viet": "Vũ Tùng Cảnh Dương Cương đả hổ, anh danh cái thế vạn cổ truyền.", "zh": "武松景陽岡打虎，英名蓋世萬古傳。", "en": "Wu Song slew the tiger on Jingyang Ridge, his heroic fame echoing across ten thousand generations.", "hanViet": "Vũ Tùng đả hổ"}]),

    (31, "v5", "r31_04_shuihu_linchong", "施耐庵《水滸傳·林教頭風雪山神廟》", "Thi Nại Am - Lâm Giáo Đầu Phong Tuyết Sơn Thần Miếu", "Water Margin: Lin Chong at Snowstorm Temple", "施耐庵", "Thi Nại Am", "元末明初", "Nguyên Mạt Minh Sơ",
     "正是嚴冬，彤雲密布，朔風漸緊，紛紛揚揚捲下一天大雪來。林沖到草料場，見草廳被雪壓倒，借宿山神廟。將大石擋住廟門。忽聞門外陸謙、富安三人密謀放火燒草料場謀害林沖。林沖大怒，推開大石，手提花槍大喝一聲跳出廟門，搠倒陸謙，直取仇人首級！踏著漫天風雪，投奔梁山泊而去。",
     "八十萬禁軍教頭林沖屢遭陷害發配滄州。風雪夜草料場被焚，山神廟前手刃陸謙等奸賊，逼上梁山雪夜投奔義軍。",
     "Heavy blizzard collapsed the thatch hut. Inside the Mountain Spirit Temple, Lin Chong overheard the assassins' plot to burn him alive; furious, he thrust open the doors with his spear, slain the traitors, and embarked onto Mount Liang amidst the snowstorm!",
     "「逼上梁山」之最高藝術寫照，風雪景物與英雄從隱忍求全到怒火爆發手刃仇敵之心理轉折契合無間。",
     "【漢越音考證】沖 (Trùng), 彤 (Đồng), 朔 (Sóc), 廟 (Miếu), 搠 (Sóc), 槍 (Thương).",
     [{"viet": "Phong tuyết sơn thần miếu, bức thượng Lương Sơn.", "zh": "林教頭風雪山神廟，逼上梁山雪夜投奔。", "en": "Lin Chong at the Mountain Spirit Temple in blizzard: forced to ascend Mount Liang.", "hanViet": "Bức thượng Lương Sơn"}]),

    (31, "v5", "r31_05_shuihu_zhiqu", "施耐庵《水滸傳·智取生辰綱》", "Thi Nại Am - Trí Thủ Sinh Thần Cương", "Water Margin: Winning the Birthday Convoy", "施耐庵", "Thi Nại Am", "元末明初", "Nguyên Mạt Minh Sơ",
     "赤日炎炎似火燒，野田禾稻半枯焦。農夫心內如湯煮，公子王孫把扇搖。黃泥岡上晁蓋、吳用、白勝等扮作販棗客商與賣酒漢，智用蒙汗藥麻倒楊志等押運官兵，神不知鬼不覺智取十萬貫生辰綱財寶，劫富濟貧大快人心！",
     "晁蓋吳用七星聚義，黃泥岡炎天智用蒙汗藥取十萬貫搜刮民脂民膏之生辰綱，劫富濟貧揭開梁山聚義大幕。",
     "Under scorching summer sun, Chao Gai and Wu Yong disguised as wine and date peddlers, using sleeping herbs to capture the birthday convoy of corrupt wealth without shedding blood!",
     "計謀環環相扣引人入勝，農夫心焦與權貴扇搖之詩深刻揭露階級對立本質。",
     "【漢越音考證】晁 (Triều), 蓋 (Cái), 智 (Trí), 綱 (Cương), 暑 (Thử), 棗 (Táo).",
     [{"viet": "Xích nhật viêm viêm tự hỏa thiêu, dã điền hòa đạo bán khô tiêu. Nông phu tâm nội như thang chử, công tử vương tôn bả phiến dao.", "zh": "赤日炎炎似火燒，野田禾稻半枯焦。農夫心內如湯煮，公子王孫把扇搖。", "en": "The blazing red sun burns like fire, paddy rice half-scorched in fields. The farmer's heart boils like broth, while noble princes gently wave fans.", "hanViet": "Xích nhật viêm viêm tự hỏa thiêu"}]),

    # Round 32: 西遊記
    (32, "v5", "r32_01_xiyouji_shihou", "吳承恩《西遊記·第一回·石猴出世》", "Ngô Thừa Ân - Tây Du Ký - Thạch Hầu Xuất Thế", "Journey to the West: Birth of the Monkey King", "吳承恩", "Ngô Thừa Ân", "明代", "Minh",
     "混沌未分天地亂，茫茫渺渺無人見。自從盤古破鴻濛，開闢從茲清濁辨。海外有一國，名曰傲來國。國近大海，海中有一座名山，喚為花果山。那座山頂上，有一塊仙石。受日精月華，感脆有通靈之意。一日產一石卵，化作一個石猴。五官俱備，四肢皆全。便就學爬學走，拜了四方。目運兩道金光，射衝斗府。闖水簾洞稱美猴王，訪菩提祖師得名孫悟空。",
     "花果山仙石受日月精華化作通靈石猴。勇闖水簾洞稱美猴王。為求解脫生死雲遊海外，拜菩提祖師得賜名孫悟空學七十二變。",
     "From the immortal stone atop Flower Fruit Mountain nurtured by sun and moon, a divine stone monkey was born, eyes shooting golden beams to the heavens! He plunged through the Waterfall Cave to become the Handsome Monkey King.",
     "《西遊記》開宗明義，石猴誕生象徵人性追求自由與打破束縛之純真本性發軔。",
     "【漢越音考證】承 (Thừa), 恩 (Ân), 猴 (Hầu), 沌 (Độn), 濛 (Mông), 簾 (Liêm).",
     [{"viet": "Hỗn độn vị phân thiên địa loạn, mang mang miểu miểu vô nhân kiến. Hoa Quả sơn thạch hầu xuất thế.", "zh": "混沌未分天地亂，茫茫渺渺無人見。花果山仙石產卵化作石猴。", "en": "Ere chaos separated and Earth was formed, a stone monkey was born atop Flower Fruit Mountain.", "hanViet": "Thạch hầu xuất thế"}]),

    (32, "v5", "r32_02_xiyouji_danaotiangong", "吳承恩《西遊記·大鬧天宮》", "Ngô Thừa Ân - Tây Du Ký - Đại Náo Thiên Cung", "Journey to the West: Havoc in Heaven", "吳承恩", "Ngô Thừa Ân", "明代", "Minh",
     "齊天大聖孫悟空大鬧蟠桃盛會，偷飲御酒，盜食太上老君金丹，重返水簾洞。玉帝遣十萬天兵天將天羅地網下界擒拿。悟空大顯神通，一條如意金箍棒打得九曜星閉門閉戶，四大天王無影無蹤。太上老君八卦爐鍛鍊四十九日，煉成火眼金睛。破爐而出大鬧靈霄寶殿，高呼：「皇帝輪流做，明年到我家！」",
     "孫悟空偷蟠桃金丹鬧瑤池，戰十萬天兵。八卦爐煉出火眼金睛，棒打靈霄寶殿，宣稱「皇帝輪流做明年到我家」，展現頂天立地之反抗神威。",
     "Sun Wukong rebelled against Heaven, fighting 100,000 heavenly soldiers with the Golden Cudgel. Forged in Laozi's furnace for 49 days, he leaped out with Fiery Eyes and Golden Pupils, demanding: 'Emperorship rotates in turn, next year it is my turn!'",
     "中國古典浪漫主義文學反抗封建神權統治之最高神話讚歌，展現孫悟空桀驁不馴、敢教日月換新天之大無畏精神。",
     "【漢越音考證】鬧 (Náo), 宮 (Cung), 蟠 (Bàn), 丹 (Đan), 箍 (Cô), 霄 (Tiêu).",
     [{"viet": "Hoàng đế luân lưu tác, minh niên đáo ngã gia!", "zh": "皇帝輪流做，明年到我家！", "en": "Emperorship rotates by turns, next year it shall be my turn!", "hanViet": "Hoàng đế luân lưu tác"}]),

    (32, "v5", "r32_03_xiyouji_sandabaigujing", "吳承恩《西遊記·三打白骨精》", "Ngô Thừa Ân - Tây Du Ký - Tam Đả Bạch Cốt Tinh", "Journey to the West: Three Battles with White Bone Demon", "吳承恩", "Ngô Thừa Ân", "明代", "Minh",
     "白骨夫人為吃唐僧肉，先後化身妙齡村姑、年邁老嫗、白髮老翁行騙。孫悟空火眼金睛辨明妖魔，連揮金箍棒三度將其斃命，白骨精化為一堆骷髏白骨。唐僧肉眼凡胎誤信八戒挑唆，斥悟空濫殺無辜，念動緊箍咒逐走齊天大聖。悟空拜別師父淚灑西行路。",
     "白骨精三變村姑老婦老翁惑唐僧，悟空火眼金睛三打白骨現原形。唐僧受蒙蔽念緊箍咒驅逐悟空，悟空拜別師父情深義重。",
     "The White Bone Demon transformed thrice into village maiden, old mother, and grandfather. Sun Wukong saw through the disguises with Fiery Eyes and struck her dead. Tang Monk, blinded by deception, banished Wukong in tragic misunderstanding.",
     "刻畫正義與妖邪之較量，展示心魔惑人、肉眼難辨真偽與西行取經團隊歷經磨難建立信任之艱辛歷程。",
     "【漢越音考證】骨 (Cốt), 髏 (Lâu), 嫗 (Ẩu), 骷 (Khô), 咒 (Chú).",
     [{"viet": "Hỏa nhãn kim tinh biện yêu ma, tam đả Bạch Cốt Tinh.", "zh": "火眼金睛辨妖魔，三打白骨精顯忠心。", "en": "With Fiery Eyes and Golden Pupils discerning demons, striking the White Bone Spirit thrice with unswerving loyalty.", "hanViet": "Hỏa nhãn kim tinh"}]),

    (32, "v5", "r32_04_xiyouji_zhenjiameihouwang", "吳承恩《西遊記·真假美猴王》", "Ngô Thừa Ân - Tây Du Ký - Chân Giả Mỹ Hầu Vương", "Journey to the West: Two Monkey Kings", "吳承恩", "Ngô Thừa Ân", "明代", "Minh",
     "六耳獼猴化身孫悟空奪行囊打傷唐僧。真假悟空相貌、武藝、兵器、緊箍咒全無二致。自南海觀音、天宮玉帝、幽冥地府諦聽皆不能辨。直打至西天雷音寺，如來佛祖指出：「此乃六耳獼猴，善聆音，能察理，知前後，萬物皆明。」悟空一棒絕此二心，師徒重歸於好。",
     "六耳獼猴假扮悟空難分真假，天地神祇皆莫能辨。西天如來佛祖指出乃六耳獼猴善知前後。悟空一棒除妖，喻示降伏心魔二心歸一。",
     "The Six-Eared Macaque copied Sun Wukong completely: none could distinguish the two across Heaven and Underworld. Tathagata Buddha revealed the impostor as the shadow self (two minds), enabling Wukong to vanquish it.",
     "「二心相爭」為全書精妙之心理哲學隱喻，表明求道者唯有破除內在心魔妄念方能成就心性正果。",
     "【漢越音考證】假 (Giả), 獼 (Di), 猴 (Hầu), 諦 (Đế), 如 (Như), 來 (Lai).",
     [{"viet": "Lưỡng tâm tương tranh thần ma hoặc, Như Lai chỉ điểm phân chân giả.", "zh": "二心相爭神魔惑，如來指點分真偽。", "en": "When two minds contend, even gods are perplexed; Tathagata Buddha points out the true from false.", "hanViet": "Chân giả mỹ hầu vương"}]),

    (32, "v5", "r32_05_xiyouji_qudezhenjing", "吳承恩《西遊記·取得真經》", "Ngô Thừa Ân - Tây Du Ký - Đắc Chân Kinh", "Journey to the West: Attaining the True Sutras", "吳承恩", "Ngô Thừa Ân", "明代", "Minh",
     "師徒歷經十四寒暑，九九八十一難，終達靈山雷音寺參謁如來佛祖。初取無字真經，燃燈古佛點化重取有字大乘三藏真經五千零四十八卷。乘老黿渡通天河經歷最後一難。返抵長安太宗迎謁，師徒功德圓滿，唐僧封旃檀功德佛，悟空封鬥戰勝佛，八戒封淨壇使者，沙僧封金身羅漢，白龍馬封八部天龍。",
     "師徒歷九九八十一難終抵雷音寺取得大乘真經五千零四十八卷歸長安。孫悟空封鬥戰勝佛，功德圓滿。",
     "After fourteen years and eighty-one trials, Tang Monk and his disciples arrived at Thunder Monastery, retrieving 5,048 scrolls of True Sutras. Sun Wukong was crowned the Victorious Fighting Buddha!",
     "象徵歷經人生千難萬險修心克己、昇華人性、達致圓滿自覺與大智大勇之至高境界。",
     "【漢越音考證】經 (Kinh), 旃 (Chiên), 檀 (Đàn), 黿 (Nguyên), 羅 (La), 漢 (Hán).",
     [{"viet": "Cửu cửu bát thập nhất nan công đức viên mãn, đắc chân kinh độ hóa chúng sinh.", "zh": "九九八十一難功德圓滿，得真經普度眾生。", "en": "Eighty-one trials endured with perfection of merit, securing true scriptures to enlighten all living beings.", "hanViet": "Cửu cửu bát thập nhất nan"}]),

    # Round 33: 紅樓夢
    (33, "v5", "r33_01_hongloumeng_haoliaoge", "曹雪芹《紅樓夢·好了歌與甄士隱註》", "Tào Tuyết Cần - Hồng Lâu Mộng - Hảo Liễu Ca", "Dream of the Red Chamber: Song of All Good Things", "曹雪芹", "Tào Tuyết Cần", "清代", "Thanh",
     "世人都曉神仙好，惟有功名忘不了！古來將相在何方？荒塚一堆草沒了。世人都曉神仙好，只有金銀忘不了！終朝只恨聚無多，及到多時眼閉了。世人都曉神仙好，只有姣妻忘不了！君生日日說恩愛，君死又隨人去了。世人都曉神仙好，只有兒孫忘不了！痴心父母古來多，孝順兒孫誰見了？士隱註曰：陋室空堂，當年笏滿床；衰草枯楊，曾為歌舞場。蛛絲兒結滿雕梁，綠紗今又糊在蓬窗上。因嫌紗帽小，致使鎖枷扛；昨憐破襖寒，今嫌紫蟒長。亂烘烘你方唱罷我登場，反認他鄉是故鄉。甚荒唐，到頭來都是為他人作嫁衣裳！",
     "瘋道人作《好了歌》，甄士隱解註：世人皆迷戀功名、金銀、嬌妻、兒孫。富貴榮華轉眼空堂衰草蛛網雕梁。亂烘烘你方唱罷我登場，到頭來都是為他人作嫁衣裳！",
     "All men know that immortals are happy, yet fame and wealth they cannot forget! Empty halls once filled with jade tallies; overgrown weeds where courtyards danced. In wild frenzy you sing your exit as I enter: all in the end was merely weaving bridal gowns for others!",
     "《紅樓夢》哲學總綱，以極深沉佛道哲理道破封建貴族盛極必衰與世態無常之千古幻滅感。",
     "【漢越音考證】芹 (Cần), 塚 (Trủng), 笏 (Hốt), 蟒 (Mãng), 荒 (Hoang), 唐 (Đường).",
     [{"viet": "Loạn hồng hồng nhĩ phương xướng bãi ngã đăng tràng, phản nhận tha hương thị cố hương. Thậm hoang đường, đáo đầu lai đô thị vi tha nhân tác giá y thường!", "zh": "亂烘烘你方唱罷我登場，反認他鄉是故鄉。甚荒唐，到頭來都是為他人作嫁衣裳！", "en": "In noisy confusion, you sing your exit as I take the stage, mistaking foreign land for homeland. How absurd, in the end it was all weaving bridal robes for others!", "hanViet": "Vi tha nhân tác giá y thường"}]),

    (33, "v5", "r33_02_hongloumeng_taixuhuanjing", "曹雪芹《紅樓夢·賈寶玉夢遊太虛幻境》", "Tào Tuyết Cần - Giả Bảo Ngọc Mộng Du Thái Hư Huyễn Cảnh", "Dream of the Red Chamber: Illusory Realm", "曹雪芹", "Tào Tuyết Cần", "清代", "Thanh",
     "賈寶玉夢至太虛幻境，見石牌坊上書「太虛幻境」，兩邊對聯：「假作真時真亦假，無為有處有還無。」警幻仙姑引看金陵十二釵圖冊判詞。開闢鴻蒙，誰為情種？都只為風月情濃。趁著這奈何天，傷懷日，寂寥時，試遣愚衷。因此上，演出這懷金悼玉的《紅樓夢》。字字看來皆是血，十年辛苦不尋常！滿紙荒唐言，一把辛酸淚！都雲作者痴，誰解其中味？",
     "賈寶玉夢遊太虛幻境見十二釵圖冊判詞。「假作真時真亦假，無為有處有還無」。滿紙荒唐言一把辛酸淚，都雲作者痴誰解其中味！",
     "Truth becomes fiction when fiction is true; real becomes unreal where unreal exists. A sheet full of absurd words, a handful of bitter tears! All say the author is mad, who can fathom its inner flavor?",
     "小說藝術預敘與象徵體系核心，確立紅樓夢「懷金悼玉、大旨談情」之悲劇宿命主題。",
     "【漢越音考證】釵 (Thoa), 幻 (Huyễn), 警 (Cảnh), 姑 (Cô), 蒙 (Mông), 辛 (Tân).",
     [{"viet": "Giả tác chân thời chân diệc giả, vô vi hữu xứ hữu hoàn vô. Mãn chỉ hoang đường ngôn, nhất bả tân toan lệ!", "zh": "假作真時真亦假，無為有處有還無。滿紙荒唐言，一把辛酸淚！", "en": "Truth becomes fiction when fiction is real; nothing becomes something where being is naught. A page filled with absurd words, a handful of bitter tears!", "hanViet": "Giả tác chân thời chân diệc giả"}]),

    (33, "v5", "r33_03_hongloumeng_daiyuzanghua", "曹雪芹《紅樓夢·黛玉葬花》", "Tào Tuyết Cần - Đại Ngọc Táng Hoa", "Dream of the Red Chamber: Daiyu Buries Blossoms", "曹雪芹", "Tào Tuyết Cần", "清代", "Thanh",
     "花謝花飛花滿天，紅消香斷有誰憐？遊絲軟繫飄春榭，落絮輕沾撲繡簾。閨中女兒惜春暮，愁緒滿懷無釋處。手把花鋤出繡閨，忍踏落花來復去。柳絲榆莢自芳菲，不管桃飄與李飛。桃李明年能再發，明年閨中知有誰？三月香巢已壘成，梁間燕子太無情！一年三百六十日，風刀霜劍嚴相逼。明媚鮮妍能幾時，一朝漂泊難尋覓。花開易見落難尋，階前愁殺葬花人。獨倚花鋤淚暗灑，灑上空枝見血痕。杜鵑無語正黃昏，荷鋤歸去掩重門。青燈照壁人初睡，冷雨敲窗被未溫。怪奴底事倍傷神？半為憐春半惱春。憐春忽至惱忽去，至又無言去不聞。昨宵庭外悲歌發，知是花魂與鳥魂？花魂鳥魂總難留，鳥自無言花自羞。願儂此日生雙翼，隨花飛到天盡頭。天盡頭，何處有香丘？未若錦囊收艷骨，一抔淨土掩風流。質本潔來還潔去，強於污淖陷渠溝。爾今死去儂收葬，未卜儂身何日喪？儂今葬花人笑痴，他年葬儂知是誰？試看春殘花落日，便是紅顏老死時。一朝春盡紅顏老，花落人亡兩不知！",
     "林黛玉肩荷花鋤攜花囊落淚葬花，吟唱千古《葬花吟》：「花謝花飛花滿天，紅消香斷有誰憐？質本潔來還潔去，強於污淖陷渠溝。一朝春盡紅顏老，花落人亡兩不知！」",
     "Flowers fade and fly across the sky, red fades and perfume breaks—who weeps for them? Pure in essence you came, pure you depart, never falling into filthy ditch. Today I bury flowers, when shall I die? When spring ends and petals fall, flower fallen and maiden dead, neither knows the other!",
     "林黛玉悲劇命運之詩意自白，將高潔品性、寄人籬下之哀傷與對生命尊嚴之堅守抒發至絕美至悲之境。",
     "【漢越音考證】黛 (Đại), 葬 (Táng), 鋤 (Trừ), 淖 (Náo), 抔 (Phôi), 囊 (Nang).",
     [{"viet": "Chất bản khiết lai hoàn khiết khứ, cường ư ô xước hãm cừ câu. Nhất triêu xuân tận hồng nhan lão, hoa lạc nhân vong lưỡng bất tri!", "zh": "質本潔來還潔去，強於污淖陷渠溝。一朝春盡紅顏老，花落人亡兩不知！", "en": "Pure in essence you arrived, pure in essence you depart, better than falling into filthy mire. One day when spring is spent and rosy youth grows old, flowers fallen and maiden dead—neither shall know of the other!", "hanViet": "Chất bản khiết lai hoàn khiết khứ"}]),

    (33, "v5", "r33_04_hongloumeng_liulaolao", "曹雪芹《紅樓夢·劉姥姥進大觀園》", "Tào Tuyết Cần - Lưu Lão Lão Tiến Đại Quan Viên", "Dream of the Red Chamber: Granny Liu Visits the Grand View Garden", "曹雪芹", "Tào Tuyết Cần", "清代", "Thanh",
     "鳳姐便故意拿一雙老年四楞象牙鑲金的筷子與劉姥姥。劉姥姥見了，說道：「這叉巴子比我們那裏的鐵杴還沉，哪裏拿得動它！」賈母便說：「請。」劉姥姥便站起身來，高聲說道：「老劉，老劉，食量大如牛，吃一個老母豬不抬頭！」說完，卻鼓著腮幫子，兩眼直視，一聲不語。眾人先是發怔，後來一齊大笑起來。湘雲掌不住，一口茶都噴了出來；黛玉笑岔了氣，扶著桌子叫「哎喲」；寶玉滾到賈母懷裏，賈母笑得摟著寶玉叫「心肝」；王夫人笑得用手指著鳳姐，只說不出話來；薛姨媽也掌不住，口裏的茶噴了探春一裙子；惜春離了座位，拉著奶母叫揉揉腸子。地下一干婆子丫鬟無一個不彎腰屈背笑得前仰後合。劉姥姥卻面不改色，自顧吃喝。",
     "劉姥姥二進榮國府進大觀園，鳳姐鴛鴦巧設席筵。劉姥姥裝瘋賣傻逗笑賈母眾人滿堂絕倒，刻畫貴族豪門生活與底層農村老婦世故大智。",
     "Granny Liu stood up and shouted: 'Old Liu, Old Liu, eating like a cow, devouring a whole sow without looking up!' The whole room erupted into uncontrollable roars of laughter!",
     "中國古典小說喜劇世態場面描寫之絕品，以鮮活細節寫盡大觀園各色人物性格姿態與貧富相映之世相。",
     "【漢越音考證】姥 (Lão / Mỗ), 象 (Tượng), 牙 (Nha), 箸 (Trợ), 噴 (Phún), 怔 (Chinh).",
     [{"viet": "Lão Lưu, lão Lưu, thực lượng đại như ngưu, thực nhất cá lão mẫu trư bất đao đầu!", "zh": "老劉，老劉，食量大如牛，吃一個老母豬不抬頭！", "en": "Old Liu, Old Liu, eats as big as a cow, devouring a whole sow without raising her brow!", "hanViet": "Lão Lưu thực lượng đại như ngưu"}]),

    (33, "v5", "r33_05_hongloumeng_baoyuaida", "曹雪芹《紅樓夢·寶玉挨打》", "Tào Tuyết Cần - Bảo Ngọc Nhai Đả", "Dream of the Red Chamber: Baoyu Beaten by His Father", "曹雪芹", "Tào Tuyết Cần", "清代", "Thanh",
     "賈政見寶玉結交琪官、金釧跳井投河，大怒喝令：「拿寶玉來！今日堵死嘴痛打一頓！」命門役狠命下板子，打得皮開肉綻。王夫人聞訊抱哭，賈母拄拐趕到，厲聲怒斥賈政：「先打死我，再打死他！」寶玉重傷臥床，黛玉哭得兩眼桃子一般，抽抽噎噎道：「你都改了吧！」寶玉咬牙強忍劇痛低聲道：「你放心，別說打死，就是為這些人死了，我也是情願的！」",
     "賈政嚴厲毒打寶玉。黛玉探視淚流滿面勸改，寶玉堅貞無悔：「便為這些人死了也是情願的！」凸顯叛逆反封建禮教之傲骨。",
     "Beaten black and blue by his Confucian father, Baoyu whispered to weeping Daiyu: 'Rest easy; even if beaten to death for love and understanding, I am wholly willing!'",
     "封建衛道士父權與追求個性解放叛逆叛徒之激烈衝突，彰顯寶玉至情至性無怨無悔之純真靈魂。",
     "【漢越音考證】杖 (Trượng), 撻 (Thát), 笞 (Si), 枷 (Gia), 噎 (Yết).",
     [{"viet": "Nhĩ phóng tâm, biệt thuyết đả tử, tựu thị vi giá gia nhân tử liễu, ngã dã thị tình nguyện đích!", "zh": "你放心，別說打死，就是為這些人死了，我也是情願的！", "en": "Rest your heart; let alone beaten, even if I die for love of them, I am entirely willing!", "hanViet": "Tình nguyện dĩ tử"}]),

    # Round 34: 聊齋與儒林
    (34, "v5", "r34_01_liaozhai_zixu", "蒲松齡《聊齋志異·自序》", "Bồ Tùng Linh - Liêu Trai Chí Dị - Tự Tự", "Strange Tales from a Chinese Studio: Author's Preface", "蒲松齡", "Bồ Tùng Linh", "清代", "Thanh",
     "披蘿帶荔，三閭氏感而為《騷》；牛鬼蛇神，長爪郎懷窮而作詩。集腋為裘，妄續幽冥之錄；浮白載筆，僅成孤憤之書：寄託如此，亦足悲矣！嗟乎！霜夜螢火，空壁燈花，松精狐魅，各具至情。知我者，其在青林黑塞間乎！",
     "蒲松齡窮愁潦倒作《聊齋志異》。以狐鬼幽冥托興寄情，「集腋成裘，僅成孤憤之書」，感嘆唯有青林黑塞之幽魂方為知己。",
     "Gathering fox furs into coats, writing records of spirits and shades to express my solitary indignation. Those who understand me are perhaps among dark forests and ghostly frontiers!",
     "清代文言短篇小說巔峰《聊齋志異》之序文，藉狐鬼花妖諷刺人間貪殘，抒發一代文人孤憤落魄情懷。",
     "【漢越音考證】蒲 (Bồ), 齡 (Linh), 齋 (Trai), 狐 (Hồ), 魅 (Mị), 螢 (Huỳnh).",
     [{"viet": "Tập dịch vi cừu, vọng tục u minh chi lục; phù bạch tải bút, cẩn thành cô phẫn chi thư.", "zh": "集腋為裘，妄續幽冥之錄；浮白載筆，僅成孤憤之書。", "en": "Gathering fox bits into fur coats to continue records of the underworld; pen in hand, creating a book of solitary indignation.", "hanViet": "Tập dịch vi cừu"}]),

    (34, "v5", "r34_02_liaozhai_laoshan", "蒲松齡《聊齋志異·勞山道士》", "Bồ Tùng Linh - Lao Sơn Đạo Sĩ", "Strange Tales: The Taoist of Mount Lao", "蒲松齡", "Bồ Tùng Linh", "清代", "Thanh",
     "王生慕仙訪勞山道士。道士授以穿牆之術，戒其「歸宜潔持，否則不驗」。王生自矜法術，歸家向妻炫耀，驀直奔牆衝去，頭觸硬壁，頓然跌僕，額上隆起如巨卵。妻扶起哂笑，王生慚忿詛罵老道士無良。異史氏曰：聞道易而行道難，自矜衒術者，鮮有不觸壁破頭者也！",
     "王生入勞山學穿牆法術，心術不正回家炫耀撞得頭破血流巨卵隆起。諷刺投機取巧、自欺欺人妄求捷徑者必碰壁慘敗。",
     "Wang boasted of his wall-walking magic to his wife, but charged straight into the solid wall, crashing down with a giant egg-sized lump on his head!",
     "膾炙人口之幽默諷刺名篇，警示世人切勿投機取巧、自吹自擂，唯有真才實學腳踏實地。",
     "【漢越音考證】勞 (Lao), 術 (Thuật), 炫 (Huyễn), 卵 (Noãn), 詛 (Trớ).",
     [{"viet": "Đầu xúc ngạnh bích, đốn nhiên điệt bộc, ngạch thượng long khởi như cự noãn.", "zh": "頭觸硬壁，頓然跌僕，額上隆起如巨卵。", "en": "Head crashing into solid wall, falling headlong with a lump swelling like a giant egg upon his forehead.", "hanViet": "Lao Sơn đạo sĩ"}]),

    (34, "v5", "r34_03_liaozhai_cuzhi", "蒲松齡《聊齋志異·促織》", "Bồ Tùng Linh - Xúc Chức", "Strange Tales: The Cricket", "蒲松齡", "Bồ Tùng Linh", "清代", "Thanh",
     "宣德間宮中尚促織之戲，歲徵民間。成名以捕蟋蟀破家，逼於嚴刑。幸得一神駿蟋蟀，幼子好奇誤斃之，驚懼投井。後化為小蟋蟀，鬥無不勝，獻入宮中。成名因此暴富得官。異史氏曰：「天子一跬步，皆關民命。一人飛升，仙及雞犬。天子偶愛一蟲，小民傾家蕩產！」",
     "宮廷好鬥蟋蟀逼得成名家破人亡，子投井化蟋蟀搏鬥獲勝成巨富。痛斥「天子一跬步皆關民命，一人飛升仙及雞犬」之荒誕現實。",
     "The Emperor loved cricket fighting, driving families to ruin. An innocent boy transformed into a champion cricket. What is an emperor's fleeting whim is life and death to the common people!",
     "深刻批判封建宮廷荒淫徵歛對無辜小民之殘酷摧殘，具強烈現實主義批判震撼力。",
     "【漢越音考證】促 (Xúc), 織 (Chức), 蟀 (Suất), 蟋 (Tất), 徵 (Trưng).",
     [{"viet": "Thiên tử nhất khuể bộ, giai quan dân mệnh. Nhất nhân phi thăng, tiên cập kê khuyển.", "zh": "天子一跬步，皆關民命。一人飛升，仙及雞犬。", "en": "Every step of the Emperor decides common people's lives; when one man ascends, his chickens and dogs join the immortals.", "hanViet": "Tiên cập kê khuyển"}]),

    (34, "v5", "r34_04_rulinwaishi_fanjin", "吳敬梓《儒林外史·范進中舉》", "Ngô Kính Tử - Nho Lâm Ngoại Sử - Phạm Tiến Trúng Cử", "The Scholars: Fan Jin Passes the Imperial Exam", "吳敬梓", "Ngô Kính Tử", "清代", "Thanh",
     "范進年五十四歲，連考三十五年始中秀才，受盡岳父胡屠戶唾罵羞辱。及省城鄉試中第七名亞元，捷報傳來，范進看罷，拍手大笑道：「噫！好了！我中了！」手舞足蹈，歡喜得一口痰湧上來，往後一交跌倒，牙關咬緊，不省人事。瘋跑到集市上大喊大叫跌在泥塘裏。眾人無法，請胡屠戶狠狠打了一個大嘴巴，方才清醒過來。鄰里官紳立刻送銀送房，前倨後恭世態炎涼極致盡顯！",
     "老童生范進中舉喜極發瘋，胡屠戶由唾罵爛忠厚窮鬼轉為奉承天上下凡文曲星。入木三分諷刺科舉制度對文人靈魂之毒害與世態炎涼。",
     "Fifty-four-year-old Fan Jin passed the examination after decades of humiliation. Reading the bulletin, he clapped hands and went completely mad with joy, shrieking: 'Aha! I passed!'",
     "諷刺小說最高巔峰，以白描誇張手法無情剖析八股科舉制度摧殘人性之癲狂病態。",
     "【漢越音考證】梓 (Tử), 儒 (Nho), 屠 (Đồ), 捷 (Tiệp), 亞 (Á).",
     [{"viet": "Y! Hảo liễu! Ngã trúng liễu! Phạm Tiến trúng cử cuồng hỉ.", "zh": "噫！好了！我中了！范進中舉狂喜發瘋。", "en": "Aha! Wonderful! I have passed! Fan Jin went mad with ecstasy upon passing the exam.", "hanViet": "Phạm Tiến trúng cử"}]),

    (34, "v5", "r34_05_rulinwaishi_yanjiansheng", "吳敬梓《儒林外史·嚴監生臨終》", "Ngô Kính Tử - Nho Lâm Ngoại Sử - Nghiêm Giám Sanh Lâm Chung", "The Scholars: Death of Overseer Yan", "吳敬梓", "Ngô Kính Tử", "清代", "Thanh",
     "嚴監生喉嚨裏痰響得一進一出，一聲不倒一聲的，總不得斷氣，還把手從被單裏拿出來，伸著兩個指頭。大姪子、二姪子、奶媽紛紛猜是問兩個人、兩筆銀子、兩處田地，嚴監生把頭搖了又搖。趙氏走近前看時，看著燈盞裏點著兩莖燈草，心裡明白，便忙走上前挑掉了一莖。眾人看嚴監生時，點一點頭，把手垂下，登時就沒了氣。",
     "大富翁嚴監生臨終喉中痰響氣絕不下，伸出兩個指頭。眾人猜問皆非，妾趙氏挑掉油燈中多點的一根燈草，嚴監生方點頭嚥氣。極致刻畫守財奴形象。",
     "Dying Overseer Yan refused to breathe his last, holding up two fingers. None understood until his wife removed the extra burning wick from the oil lamp; he nodded and passed away immediately!",
     "世界文學史上最傳神之守財奴吝嗇鬼細節刻畫，兩個指頭與一莖燈草神來之筆千古絕倒。",
     "【漢越音考證】監 (Giám), 莖 (Cọng / Hành), 燈 (Đăng), 盞 (Trản), 吝 (Lận), 嗇 (Sắc).",
     [{"viet": "Nghiêm Giám sanh lâm chung thân lưỡng cá chỉ đầu, thiêu khước nhất cọng đăng thảo phương khẳng yết khí.", "zh": "嚴監生臨終伸著兩個指頭，挑掉一莖燈草方肯嚥氣。", "en": "Overseer Yan raised two fingers on deathbed, refusing to die until one lamp wick was put out.", "hanViet": "Nghiêm Giám sanh lâm chung"}]),

    # Round 35: 清代古文與龔自珍
    (35, "v5", "r35_01_fangbao_yuzhongzaji", "方苞《獄中雜記》", "Phương Bao - Ngục Trung Tạp Ký", "Fang Bao: Notes from Prison", "方苞", "Phương Bao", "清代", "Thanh",
     "康熙四十八年，余在刑部獄。見獄中蠹吏胥徒，殘酷敲詐。情節同者，賂多者生，賂少者死。胥吏指囚犯為貨物，巧立名目勒索無算。富者居寬室溫衾，貧者死於疫癘械梏。方苞目睹黑獄人間慘相，據實直書揭露清代司法制度黑暗腐敗。",
     "桐城派宗師方苞記錄獄中黑幕：官吏獄卒將犯人視為奇貨敲詐勒索，貧富殊死司法黑暗。文章嚴謹洗鍊義法並重。",
     "In prison, corrupt jailers extorted inmates like commodities; those who bribed lived, those without perished. A searing exposé of feudal injustice.",
     "桐城派散文紀實名篇，貫徹「義理、考據、辭章」三者統一之寫作原則。",
     "【漢越音考證】苞 (Bao), 獄 (Ngục), 胥 (Tư), 梏 (Cốc), 疫 (Dịch).",
     [{"viet": "Thư lại thị tù phạm vi hóa vật, tư pháp hủ bại kỳ cực.", "zh": "胥吏指囚犯為貨物，司法腐敗至極。", "en": "Jailers treated inmates as trading goods, showing the depths of judicial corruption.", "hanViet": "Ngục trung tạp ký"}]),

    (35, "v5", "r35_02_yaonai_dengtaishan", "姚鼐《登泰山記》", "Diêu Nãi - Đăng Thái Sơn Ký", "Yao Nai: Climbing Mount Tai", "姚鼐", "Diêu Nãi", "清代", "Thanh",
     "泰山之陽，汶水西流；其陰，濟水東流。戊子十二月，余自京師乘風雪，歷齊河、長清，穿泰山西北谷，越長城之限，至於泰安。日觀峰登臨，極天雲一線異色，須臾成五彩。日上，正赤如丹，下有紅光動搖承之。世皆曰此四十七盤之景也。",
     "姚鼐寒冬雪霽登泰山日觀峰觀日出奇景。紅白相間雲霧飄渺，山川雄偉壯麗，文字典雅簡潔，桐城派山水散文之最高代表。",
     "Climbing Mount Tai in midwinter blizzards: standing atop Sun-Viewing Peak, the sky's edge turned to five-color brilliance as the crimson sun rose majestically!",
     "桐城派大師姚鼐名作，結構嚴謹，語言清麗雅潔，刻畫名山日出神韻氣象萬千。",
     "【漢越音考證】鼐 (Nãi), 泰 (Thái), 陽 (Dương), 陰 (Âm), 霽 (Tễ).",
     [{"viet": "Cực thiên vân nhất tuyến dị sắc, tu du thành ngũ thái. Nhật thượng, chính xích như đan.", "zh": "極天雲一線異色，須臾成五彩。日上，正赤如丹。", "en": "At sky's horizon a line of strange color formed, turning in moments to five radiant hues as the sun rose red as cinnabar.", "hanViet": "Đăng Thái Sơn ký"}]),

    (35, "v5", "r35_03_yuanmei_jimei", "袁枚《祭妹文》", "Viên Mai - Tế Muội Văn", "Yuan Mei: Elegy for My Younger Sister", "袁枚", "Viên Mai", "清代", "Thanh",
     "乾隆四十四年，長兄枚以文告於素文妹之靈：嗚呼！汝生於斯，病於斯，死於斯。自汝受聘非人，茹苦含辛三十餘年。憶童稚之時，汝牽衣隨我，笑語在耳。今空室無人，孤影自憐。紙灰化蝶，淚血成珠。嗚呼哀哉！尚饗！",
     "袁枚痛悼苦命胞妹素文。回憶童年手足相伴歡樂，痛惜妹妹誤嫁不良之徒含辛茹苦抱恨終生，字字血淚至情動地。",
     "Mourning my sweet sister Suwen: Remembering childhood days when you held my robe with laughter. Now facing empty rooms and swirling ash, my tears turn to blood!",
     "清代性靈派祭文名篇，突破傳統駢體束縛，以純真白描傾瀉至深骨肉之愛與悲傷。",
     "【漢越音考證】枚 (Mai), 妹 (Muội), 稚 (Trĩ), 茹 (Như), 聘 (Phính).",
     [{"viet": "Chỉ hôi hóa điệp, lệ huyết thành châu. Ô hô ai tai!", "zh": "紙灰化蝶，淚血成珠。嗚呼哀哉！", "en": "Paper ashes turn to butterflies, tears of blood form pearls. Alas, what profound grief!", "hanViet": "Tế muội văn"}]),

    (35, "v5", "r35_04_gongzizhen_bingmeiguan", "龔自珍《病梅館記》", "Cung Tự Trân - Bệnh Mai Quán Ký", "Gong Zizhen: Hall of Sick Plums", "龔自珍", "Cung Tự Trân", "清代", "Thanh",
     "江寧之通判，蘇州之文人，以梅之曲為美，直則無姿；以其欹為美，正則無景；以其疏為美，密則無態。文人畫士縛其枝條，剪其生氣，謂之病梅。予買得病梅三百盆，泣之三日，乃誓療之：縱之順之，毀其盆，悉埋於地，解其棕縛；以五年為期，必復之全之！",
     "文人畫士病態審美以曲欹疏為美摧殘梅樹天性。龔自珍痛斥桎梏，誓療病梅毀盆鬆綁。藉梅諷世痛斥封建思想專制摧殘人才，呼喚個性自由解放。",
     "Scholars tied plum branches into sickly shapes calling deformity beauty. I bought three hundred sick plums, broke their pots, replanted them in fertile soil to restore natural vigor!",
     "近代啟蒙思想先驅名篇，借病梅象徵封建專制對人才心靈之束縛摧殘，吹響時代改革求變之號角。",
     "【漢越音考證】龔 (Cung), 珍 (Trân), 欹 (Kha / Y), 棕 (Tông), 縛 (Phược).",
     [{"viet": "Hủy kỳ bồn, tất mai ư địa, giải kỳ tông phược; tất phục chi toàn chi!", "zh": "毀其盆，悉埋於地，解其棕縛；必復之全之！", "en": "Destroy their pots, plant them in earth, untie their bonds, and restore their full natural vitality!", "hanViet": "Bệnh mai quán ký"}]),

    (35, "v5", "r35_05_gongzizhen_jihai", "龔自珍《己亥雜詩·九州生氣恃風雷》", "Cung Tự Trân - Kỷ Hợi Tạp Thi", "Gong Zizhen: Jihai Miscellaneous Poems", "龔自珍", "Cung Tự Trân", "清代", "Thanh",
     "九州生氣恃風雷，萬馬齊喑究可哀。我勸天公重抖擻，不拘一格降人才！浩蕩離愁白日斜，吟鞭東指即天涯。落紅不是無情物，化作春泥更護花。",
     "九州大地活力依賴風雷變革，萬馬齊喑沉悶局面終究可哀。我勸上天重新抖擻精神，不拘規格廣降各方英才！落花並非無情之物，化作春泥更滋養護衛新花。",
     "China's vitality relies on storm and thunder; all horses falling silent in fear is truly sorrowful. I urge Heaven to stir anew and bestow great talents without rigid bounds! Fallen red petals are not heartless things; turning to spring soil, they nourish next season's flowers.",
     "近代愛國啟蒙詩歌先聲，「萬馬齊喑、不拘一格降人才」與「落紅不是無情物，化作春泥更護花」激勵近代無數仁人志士變法救國。",
     "【漢越音考證】己 (Kỷ), 亥 (Hợi), 喑 (Âm), 抖 (Đẩu), 擻 (Tẩu), 泥 (Nê).",
     [{"viet": "Cửu châu sinh khí thị phong lôi, vạn mã tề âm cứu khả ai. Ngã khuyến thiên công trùng đẩu tẩu, bất câu nhất cách giáng nhân tài!", "zh": "九州生氣恃風雷，萬馬齊喑究可哀。我勸天公重抖擻，不拘一格降人才！", "en": "China's vitality relies on storm and thunder; all horses silenced in mute dread is deep sorrow. I urge Heaven to stir anew, bestowing talent beyond rigid mold!", "hanViet": "Bất câu nhất cách giáng nhân tài"}])
])

print(f"Volume 5 items ready: {len(vol5_items)}")
