# -*- coding: utf-8 -*-
"""Volume 4: 唐詩宋詞元曲經典與聲律考釋 (Rounds 22-28, 35 works)"""

vol4_items = [
    # Round 22: 李白豪放詩篇
    (22, "v4", "r22_01_libai_jiangjinjiu", "李白《將進酒》", "Lý Bạch - Tương Tiến Tửu", "Li Bai: Bring in the Wine", "李白", "Lý Bạch", "唐代", "Đường",
     "君不見黃河之水天上來，奔流到海不復回！君不見高堂明鏡悲白髮，朝如青絲暮成雪！人生得意須盡歡，莫使金樽空對月。天生我材必有用，千金散盡還復來。烹羊宰牛且為樂，會須一飲三百杯。岑夫子，丹丘生，將進酒，杯莫停！與君歌一曲，請君為我傾耳聽。鐘鼓饌玉不足貴，但願長醉不願醒。古來聖賢皆寂寞，惟有飲者留其名。陳王昔時宴平樂，斗酒十千恣歡謔。主人何為言少錢，徑須沽取對君酌。五花馬、千金裘，呼兒將出換美酒，與爾同銷萬古愁！",
     "君不見黃河之水天際奔騰入海不復返，高堂明鏡朝如青絲暮成雪。人生得意須盡歡，天生我材必有用千金散盡還復來！五花馬千金裘呼兒換美酒，與爾同銷萬古愁！",
     "See you not the Yellow River waters rushing from heaven down to the sea? Heaven created my talent for great purpose; thousands in gold spent will return anew. Let us drink away eternal sorrows!",
     "李白七言歌行之冠，大開大闔氣吞山河，以萬丈豪情反抗懷才不遇之苦悶，體現盛唐詩歌至高浪漫氣魄。",
     "【漢越音考證】李 (Lý), 白 (Bạch), 樽 (Tôn), 饌 (Soạn), 裘 (Cừu), 銷 (Tiêu), 愁 (Sầu).",
     [{"viet": "Thiên sinh ngã tài tất hữu dụng, thiên kim tán tận hoàn phục lai.", "zh": "天生我材必有用，千金散盡還復來。", "en": "Heaven endowed me with talent, it must be of use; thousands in gold scattered away will return again.", "hanViet": "Thiên sinh ngã tài tất hữu dụng"}]),

    (22, "v4", "r22_02_libai_xinglunan", "李白《行路難·其一》", "Lý Bạch - Hành Lộ Nan", "Li Bai: Hard Roads in Travel", "李白", "Lý Bạch", "唐代", "Đường",
     "金樽清酒斗十千，玉盤珍羞直萬錢。停杯投箸不能食，拔劍四顧心茫然。欲渡黃河冰塞川，將登太行雪滿山。閒來垂釣碧溪上，忽復乘舟夢日邊。行路難，行路難，多歧路，今安在？長風破浪會有時，直掛雲帆濟滄海！",
     "金樽清酒玉盤珍羞難以下咽，拔劍四顧茫然。黃河冰塞川太行雪滿山。然終信長風破浪會有時，直掛雲帆濟滄海！",
     "I stop my cup and drop my chopsticks, sword drawn looking around in confusion. Roads are hard, full of forks; yet a time will come to ride the wind and cleave the waves, hoisting cloud-sails across the vast sea!",
     "「長風破浪會有時，直掛雲帆濟滄海」充滿對理想追求之頑強自信，為激勵無數後人勇闖難關之千古名句。",
     "【漢越音考證】箸 (Trợ), 歧 (Kỳ), 帆 (Phàm), 滄 (Thương), 濟 (Tế).",
     [{"viet": "Trường phong phá lãng hội hữu thời, trực quải vân phàm tế thương hải.", "zh": "長風破浪會有時，直掛雲帆濟滄海！", "en": "A time will surely come to ride the winds and cleave the waves, hoisting cloud-sails high to cross the vast sea!", "hanViet": "Trường phong phá lãng hội hữu thời"}]),

    (22, "v4", "r22_03_libai_shudaonan", "李白《蜀道難》", "Lý Bạch - Thục Đạo Nan", "Li Bai: The Perilous Road to Shu", "李白", "Lý Bạch", "唐代", "Đường",
     "噫吁嚱，危乎高哉！蜀道之難，難於上青天！蠶叢及魚鳧，開國何茫然！爾來四萬八千歲，不與秦塞通人煙。西當太白有鳥道，可以橫絕峨嵋巔。地崩山摧壯士死，然後天梯石棧相鉤連。上有六龍回日之高標，下有衝波逆折之回川。黃鶴之飛尚不得過，猿猱欲度愁攀援。青泥何盤盤，百步九折縈巖巒。問君西遊何時還？畏途巉巖不可攀。但見悲鳥號古木，雄飛雌從繞林間。又聞子規啼夜月，愁空山。蜀道之難，難於上青天，使人聽此凋朱顏！",
     "蜀道之難難於上青天！開闢道路地崩山摧天梯石棧鉤連。太白高標六龍回日猿猱愁攀。子規啼夜月愁空山，使人聽此凋朱顏！",
     "Alas, how steep, how high! The road to Shu is harder than scaling the blue sky! Earth shattered, mountains crumbled, brave warriors perished before cliff ladders were linked.",
     "李白運用神話傳說與極致誇張筆法，將蜀道山川之險阻奇峻刻畫得驚心動魄，展現盛唐詩仙超凡之藝術奇想。",
     "【漢越音考證】蜀 (Thục), 鳧 (Phù), 峨 (Nga), 嵋 (Mi), 棧 (Sạn), 猱 (Nao), 巉 (Sàm).",
     [{"viet": "Thục đạo chi nan, nan ư thượng thanh thiên!", "zh": "蜀道之難，難於上青天！", "en": "The road to Shu is perilous, harder than ascending to the blue skies!", "hanViet": "Thục đạo chi nan"}]),

    (22, "v4", "r22_04_libai_tianmushan", "李白《夢遊天姥吟留別》", "Lý Bạch - Mộng Du Thiên Mỗ Ngâm Lưu Biệt", "Li Bai: Dream Journey to Mount Tianmu", "李白", "Lý Bạch", "唐代", "Đường",
     "海客談瀛洲，煙濤微茫信難求；越人語天姥，雲霞明滅或可睹。天姥連天向天橫，勢拔五嶽掩赤城。天台四萬八千丈，對此欲倒東南傾。我欲因之夢吳越，一夜飛度鏡湖月。湖月照我影，送我至剡溪。謝公宿處今尚在，淥水蕩漾清猿啼。腳著謝公屐，身登青雲梯。半壁見海日，空中聞天雞。千巖萬轉路不定，迷花倚石忽已暝。熊咆龍吟殷岩泉，慄深林兮驚層巔。雲青青兮欲雨，水澹澹兮生煙。列缺霹靂，丘巒崩摧。洞天石扉，訇然中開。青冥浩蕩不見底，日月照耀金銀臺。霓為衣兮風為馬，雲之君兮紛紛而來下。忽魂悸以魄動，恍驚起而長嗟。惟覺時之枕席，失向來之煙霞。世間行樂亦如此，古來萬事東流水。別君去兮何時還？且放白鹿青崖間，須行即騎訪名山。安能摧眉折腰事權貴，使我不得開心顏！",
     "李白夢遊天姥仙山，霓為衣風為馬仙人盛會。夢醒發出千古浩嘆：世間行樂如東流水，安能摧眉折腰事權貴，使我不得開心顏！",
     "Waking from the paradise dream: How can I bow and scrape before the rich and powerful, losing the joy of my heart and countenance!",
     "「安能摧眉折腰事權貴，使我不得開心顏」彰顯李白蔑視權貴、追求精神傲岸與自由獨立之人格光輝。",
     "【漢越音考證】姥 (Mỗ), 瀛 (Doanh), 剡 (Diệm), 屐 (Kịch), 霓 (Nghê), 悸 (Quý), 摧 (Tồi).",
     [{"viet": "An năng thôi mi chiết yêu sự quyền quý, sử ngã bất đắc khai tâm nhan!", "zh": "安能摧眉折腰事權貴，使我不得開心顏！", "en": "How can I bend my brow and bow my waist to serve the rich and powerful, robbing myself of a cheerful face!", "hanViet": "An năng thôi mi chiết yêu sự quyền quý"}]),

    (22, "v4", "r22_05_libai_yuexiaduzhuo", "李白《月下獨酌四首·其一》", "Lý Bạch - Nguyệt Hạ Độc Chước", "Li Bai: Drinking Alone Beneath the Moon", "李白", "Lý Bạch", "唐代", "Đường",
     "花間一壺酒，獨酌無相親。舉杯邀明月，對影成三人。月既不解飲，影徒隨我身。暫伴月將影，行樂須及春。我歌月徘徊，我舞影凌亂。醒時同交歡，醉後各分散。永結無情遊，相期邈雲漢。",
     "花間獨酌舉杯邀明月，對影成三人。月既不解飲影徒隨我身，我歌月徘徊我舞影凌亂。永結無情遊，相期於縹緲銀河仙境。",
     "A pot of wine among flowers, drinking alone with no companion. I raise my cup to invite the bright moon; with my shadow we make three. Let us pledge an immortal bond across the Milky Way!",
     "以奇特構思將孤獨化為浪漫歡狂，展現李白曠世之孤獨與超塵絕俗之仙風道骨。",
     "【漢越音考證】酌 (Chước), 邀 (Yêu), 徒 (Đồ), 徘 (Bồi), 徊 (Hồi), 邈 (Mạc).",
     [{"viet": "Cử bôi yêu minh nguyệt, đối ảnh thành tam nhân.", "zh": "舉杯邀明月，對影成三人。", "en": "I raise my cup to invite the bright moon; facing my shadow we make three.", "hanViet": "Cử bôi yêu minh nguyệt"}]),

    # Round 23: 杜甫沉鬱律絕
    (23, "v4", "r23_01_dufu_chunwang", "杜甫《春望》", "Đỗ Phủ - Xuân Vọng", "Du Fu: Spring View", "杜甫", "Đỗ Phủ", "唐代", "Đường",
     "國破山河在，城春草木深。感時花濺淚，恨別鳥驚心。烽火連三月，家書抵萬金。白頭搔更短，渾欲不勝簪。",
     "長安淪陷國破山河依舊，城春草木叢生。感傷時局花開落淚，怨恨離別鳥鳴驚心。安史之亂戰火連綿三月，一封家書勝抵萬金。愁白頭髮愈搔愈稀短，簡直插不上簪子。",
     "The nation shattered, mountains and rivers remain; spring in the city, grass and trees grow thick. Beholding the times, flowers draw tears; grieving over separation, birds startle the heart. Beacon fires burn for three continuous months; a letter from home is worth ten thousand pieces of gold.",
     "詩聖杜甫五言律詩巔峰名篇，沉鬱頓挫，「國破山河在」與「家書抵萬金」寫盡戰亂中人民深重苦難與憂國深情。",
     "【漢越音考證】杜 (Đỗ), 甫 (Phủ), 烽 (Phong), 抵 (Đế), 搔 (Tao), 簪 (Trâm).",
     [{"viet": "Quốc phá sơn hà tại, thành xuân thảo mộc thâm. Phong hỏa liên tam nguyệt, gia thư để vạn kim.", "zh": "國破山河在，城春草木深。烽火連三月，家書抵萬金。", "en": "The nation is shattered, mountains and rivers remain; beacon fires have burned for months, a letter from home is worth ten thousand gold.", "hanViet": "Quốc phá sơn hà tại"}]),

    (23, "v4", "r23_02_dufu_denggao", "杜甫《登高》", "Đỗ Phủ - Đăng Cao", "Du Fu: Climbing High", "杜甫", "Đỗ Phủ", "唐代", "Đường",
     "風急天高猿嘯哀，渚清沙白鳥飛迴。無邊落木蕭蕭下，不盡長江滾滾來。萬里悲秋常作客，百年多病獨登臺。艱難苦恨繁霜鬢，潦倒新停濁酒杯。",
     "風急天高猿啼淒哀，江渚清冷沙洲泛白鳥飛旋。無邊落葉蕭蕭飄落，滾滾長江奔騰不息。萬里漂泊悲秋常年客居，暮年多病獨自登上高臺。鬢髮斑白潦倒新停濁酒。",
     "Wind is fierce, sky high, apes lament sorrowfully. Boundless falling leaves rustle down; the endless Yangtze River rolls on and on. Wandering ten thousand miles in autumn grief, plagued by illnesses in old age I climb this terrace alone.",
     "被譽為「古今七言律詩第一」，對仗工整無懈可擊，將個人衰老多病之悲與國家山河之動盪融為渾茫蒼涼之宇宙大悲憫。",
     "【漢越音考證】渚 (Chử), 蕭 (Tiêu), 滾 (Cổn), 鬢 (Mấn), 潦 (Liêu).",
     [{"viet": "Vô biên lạc mộc tiêu tiêu hạ, bất tận Trường Giang cổn cổn lai.", "zh": "無邊落木蕭蕭下，不盡長江滾滾來。", "en": "Boundless leaves rustle endlessly down; the infinite Yangtze River rolls on forever.", "hanViet": "Vô biên lạc mộc tiêu tiêu hạ"}]),

    (23, "v4", "r23_03_dufu_maowu", "杜甫《茅屋為秋風所破歌》", "Đỗ Phủ - Mao Ốc Vi Thu Phong Sở Phá Ca", "Du Fu: My Thatched Hut Torn by Autumn Wind", "杜甫", "Đỗ Phủ", "唐代", "Đường",
     "八月秋高風怒號，卷我屋上三重茅。俄頃風定雲墨色，秋天漠漠向昏黑。布衾多年冷似鐵，嬌兒惡臥踏裏裂。床頭屋漏無乾處，雨腳如麻未斷絕。自經喪亂少睡眠，長夜沾濕何由徹！安得廣廈千萬間，大庇天下寒士俱歡顏！風雨不動安如山。嗚呼！何時眼前突兀見此屋，吾廬獨破受凍死亦足！",
     "秋風吹破草屋屋漏床濕。杜甫在極度寒凍困苦中推己及人發出宏願：安得廣廈千萬間大庇天下寒士俱歡顏，吾廬獨破受凍死亦足！",
     "How could we obtain ten thousand grand mansions to shelter all poor scholars under Heaven with joyful faces, standing firm as mountains in wind and rain! If this house could appear before my eyes, I would gladly freeze to death in my broken hut alone!",
     "杜甫民胞物與、捨己為人之博大胸襟震撼千古，體現儒家最高仁愛博愛精神。",
     "【漢越音考證】衾 (Khâm), 裂 (Liệt), 廈 (Hạ), 庇 (Tí), 廬 (Lư), 兀 (Ngột).",
     [{"viet": "An đắc quảng hạ thiên vạn gian, đại tí thiên hạ hàn sĩ câu hoan nhan!", "zh": "安得廣廈千萬間，大庇天下寒士俱歡顏！", "en": "How can we obtain tens of thousands of spacious mansions, to shelter all impoverished scholars under heaven with joyful faces!", "hanViet": "An đắc quảng hạ thiên vạn gian"}]),

    (23, "v4", "r23_04_dufu_wenguanjun", "杜甫《聞官軍收河南河北》", "Đỗ Phủ - Văn Quan Quân Thu Hà Nam Hà Bắc", "Du Fu: Hearing of Imperial Forces Retaking Henan and Hebei", "杜甫", "Đỗ Phủ", "唐代", "Đường",
     "劍外忽傳收薊北，初聞涕淚滿衣裳。卻看妻子愁何在，漫卷詩書喜欲狂。白日放歌須縱酒，青春作伴好還鄉。即從巴峽穿巫峽，便下襄陽向洛陽。",
     "劍門關外忽傳官軍收復失地捷報，初聞激動涕淚橫流。妻子愁容盡散，喜極欲狂收拾詩書。白日高歌縱情飲酒，趁著明媚春光作伴還鄉！",
     "News arrived of the north retaken; tears soaked my clothes. Turning to see my wife, where was sorrow now? Roll up the books in mad joy! Singing aloud in daylight with wine, escorted by green spring we return home!",
     "杜甫平生第一首「生平第一快詩」，將收復國土之狂喜與還鄉期盼寫得節奏飛揚一氣呵成。",
     "【漢越音考證】薊 (Kế), 裳 (Thường), 漫 (Mạn), 峽 (Hiệp), 襄 (Tương).",
     [{"viet": "Bạch nhật phóng ca tu túng tửu, thanh xuân tác bạn hảo hoàn hương.", "zh": "白日放歌須縱酒，青春作伴好還鄉。", "en": "Singing aloud in daylight with free-flowing wine, returning home companioned by blooming spring!", "hanViet": "Bạch nhật phóng ca tu túng tửu"}]),

    (23, "v4", "r23_05_dufu_bingchexing", "杜甫《兵車行》", "Đỗ Phủ - Binh Xa Hành", "Du Fu: Ballad of the War Carts", "杜甫", "Đỗ Phủ", "唐代", "Đường",
     "車轔轔，馬蕭蕭，行人弓箭各在腰。爺娘妻子走相送，塵埃不見咸陽橋。牽衣頓足攔道哭，哭聲直上干雲霄。道旁過者問行人，行人但云點行頻。邊庭流血成海水，武皇開邊意未已。君不見，青海頭，古來白骨無人收。新鬼煩冤舊鬼哭，天陰雨濕聲啾啾！",
     "戰車轔轔戰馬蕭蕭，出征士卒弓箭在腰。父母妻兒哭送咸陽橋哭聲震天。邊庭征戰流血成海，青海古戰場白骨無人收，新鬼煩冤舊鬼夜哭天陰雨濕。",
     "War carts rumble, horses neigh, conscripts march with bows at waist. Weeping families stomp feet blocking the road, cries piercing the clouds. Along Qinghai shores, ancient bleached bones lie unburied!",
     "杜甫即事名篇，大膽揭露統治者窮兵黷武給廣大百姓帶來的家破人亡深重災難。",
     "【漢越音考證】轔 (Lân), 霄 (Tiêu), 頻 (Tần), 冤 (Oan), 啾 (Thu).",
     [{"viet": "Biên đình lưu huyết thành hải thủy, Vũ hoàng khai biên ý vị dĩ. Quân bất kiến, Thanh Hải đầu, cổ lai bạch cốt vô nhân thu.", "zh": "邊庭流血成海水，武皇開邊意未已。君不見，青海頭，古來白骨無人收。", "en": "Blood flows at the frontier into seas, yet imperial ambitions cease not. See you not by Qinghai shores, ungathered white bones lie since antiquity!", "hanViet": "Biên đình lưu huyết thành hải thủy"}]),

    # Round 24: 王維禪意與白居易琵琶行
    (24, "v4", "r24_01_wangwei_shanjui", "王維《山居秋暝》", "Vương Duy - Sơn Cư Thu Minh", "Wang Wei: Autumn Evening in the Mountains", "王維", "Vương Duy", "唐代", "Đường",
     "空山新雨後，天氣晚來秋。明月松間照，清泉石上流。竹喧歸浣女，蓮動下漁舟。隨意春芳歇，王孫自可留。",
     "空曠群山新雨過後，傍晚秋氣清涼。明月自松林間灑下清輝，清澈泉水在山石上淙淙流淌。竹林喧笑洗衣女子歸來，荷葉搖動漁舟順流而下。任憑春花凋謝，山中秋景自可長留隱居。",
     "After fresh rain in the empty hills, autumn air cools the evening. Bright moon shines among pines, clear spring flows over stones. Bamboo rustles as washer girls return; lotus moves as fishing boats glide downstream.",
     "詩佛王維山水田園詩之絕品，「明月松間照，清泉石上流」詩中有畫畫中有詩，空靈澄澈禪意盎然。",
     "【漢越音考證】維 (Duy), 暝 (Minh), 浣 (Hoán), 蓮 (Liên), 歇 (Hiết).",
     [{"viet": "Minh nguyệt tùng gian chiếu, thanh tuyền thạch thượng lưu.", "zh": "明月松間照，清泉石上流。", "en": "The bright moon shines through pines, the crystal spring flows over stones.", "hanViet": "Minh nguyệt tùng gian chiếu"}]),

    (24, "v4", "r24_02_wangwei_shizisaishang", "王維《使至塞上》", "Vương Duy - Sứ Chí Tái Thượng", "Wang Wei: Mission to the Frontier", "王維", "Vương Duy", "唐代", "Đường",
     "單車欲問邊，屬國過居延。征蓬出漢塞，歸雁入胡天。大漠孤煙直，長河落日圓。蕭關逢候騎，都護在燕然。",
     "輕車前往邊塞慰問，走過屬國居延要塞。如飄飛蓬草出漢塞，如北歸大雁入胡天。浩瀚大漠上一縷烽煙直上，滔滔長河盡頭一輪落日渾圓。塞外雄奇風光歷歷在目。",
     "A solitary carriage heads to border posts. A tumbleweed blown beyond Han frontiers, flying geese entering Tartar skies. Vast desert, a single plume of smoke rises straight; over the long river, the setting sun glows round.",
     "名句「大漠孤煙直，長河落日圓」被王國維譽為「千古壯觀」，以極致雄渾幾何構圖刻畫塞外蒼茫宏大意境。",
     "【漢越音考證】塞 (Tái), 蓬 (Bồng), 漠 (Mạc), 騎 (Kỵ), 燕 (Yên).",
     [{"viet": "Đại mạc cô yên trực, trường hà lạc nhật viên.", "zh": "大漠孤煙直，長河落日圓。", "en": "In the vast desert, a solitary plume of smoke rises straight; over the long river, the setting sun is round.", "hanViet": "Đại mạc cô yên trực"}]),

    (24, "v4", "r24_03_wangwei_zhuliguan", "王維《輞川集·竹里館》", "Vương Duy - Trúc Lý Quán", "Wang Wei: Bamboo Lodge", "王維", "Vương Duy", "唐代", "Đường",
     "獨坐幽篁裏，彈琴復長嘯。深林人不知，明月來相照。",
     "獨自坐在幽深茂密的竹林之中，撫弄琴弦又長聲吟嘯。竹林幽深無人知曉，唯有空中明月灑下清輝默默相照。",
     "Sitting alone in the secluded bamboo grove, strumming my lute and whistling aloud. Deep in the forest where no one knows, the bright moon arrives to shine upon me.",
     "短短二十字將幽居隱者之心靈純淨、琴聲明月與物我相印之禪境融為一體，為唐詩絕句空靈藝術之極致。",
     "【漢越音考證】篁 (Hoàng), 嘯 (Khiếu), 幽 (U), 照 (Chiếu).",
     [{"viet": "Độc tọa u hoàng lý, đàn cầm phục trường khiếu. Thâm lâm nhân bất tri, minh nguyệt lai tương chiếu.", "zh": "獨坐幽篁裏，彈琴復長嘯。深林人不知，明月來相照。", "en": "Sitting alone in deep bamboo groves, strumming the lute and chanting aloud. Deep in the woods where none know, bright moonlight comes to shine.", "hanViet": "Độc tọa u hoàng lý"}]),

    (24, "v4", "r24_04_baijuyi_pipaxing", "白居易《琵琶行》", "Bạch Cư Dị - Tỳ Bà Hành", "Bai Juyi: Song of the Pipa", "白居易", "Bạch Cư Dị", "唐代", "Đường",
     "潯陽江頭夜送客，楓葉荻花秋瑟瑟。忽聞水上琵琶聲，主人忘歸客不發。尋聲暗問彈者誰？琵琶聲停欲語遲。移船相近邀相見，添酒回燈重開宴。千呼萬喚始出來，猶抱琵琶半遮面。轉軸撥弦三兩聲，未成曲調先有情。大絃嘈嘈如急雨，小絃切切如私語。嘈嘈切切錯雜彈，大珠小珠落玉盤。間關鶯語花底滑，幽咽泉流冰下難。冰泉冷澀弦凝絕，凝絕不通聲暫歇。別有幽愁暗恨生，此時無聲勝有聲。銀瓶乍破水漿迸，鐵騎突出刀槍鳴。曲終收撥當心畫，四絃一聲如裂帛。東船西舫悄無言，唯見江心秋月白。感同身受同是天涯淪落人，相逢何必曾相識！座中泣下誰最多？江州司馬青衫濕。",
     "潯陽江頭夜送客，偶遇長安琵琶女。琵琶女演奏高超大珠小珠落玉盤，此時無聲勝有聲。白居易深感同病相憐發出千古同鳴：同是天涯淪落人，相逢何必曾相識！",
     "Big strings rustled like sudden rain; small strings murmured like intimate whispers. Pearls large and small falling upon a jade plate! We are both wanderers drifting at the world's end; meeting thus, why must we have known each other before?",
     "中國古代描寫音樂演奏之最高神作，將無形之音樂化為色彩斑斕之具象畫面，融天涯淪落之悲情於潯陽江月。",
     "【漢越音考證】琶 (Bà), 荻 (Địch), 嘈 (Tào), 切 (Thiết), 迸 (Bính), 衫 (Sam).",
     [{"viet": "Đồng thị thiên nhai luân lạc nhân, tương phùng hà tất tằng tương thức!", "zh": "同是天涯淪落人，相逢何必曾相識！", "en": "Both of us are wanderers stranded at the world's edge; meeting by chance, what need is there to have known each other before!", "hanViet": "Đồng thị thiên nhai luân lạc nhân"}]),

    (24, "v4", "r24_05_baijuyi_changhenge", "白居易《長恨歌(節選)》", "Bạch Cư Dị - Trường Hận Ca", "Bai Juyi: Song of Everlasting Regret", "白居易", "Bạch Cư Dị", "唐代", "Đường",
     "回眸一笑百媚生，六宮粉黛無顏色。馬嵬坡下泥土中，不見玉顏空死處。君臣相顧盡霑衣，東望都門信馬歸。行宮見月傷心色，夜雨聞鈴腸斷聲。臨邛道士客蜀州，能以精誠致魂魄。七月七日長生殿，夜半無人私語時。在天願作比翼鳥，在地願為連理枝。天長地久有時盡，此恨綿綿無絕期。",
     "唐玄宗與楊貴妃長恨愛情悲劇。馬嵬坡兵變玉顏香消。蓬萊仙境尋魂魄，長生殿七夕誓言：「在天願作比翼鳥，在地願為連理枝。天長地久有時盡，此恨綿綿無絕期！」",
     "On the seventh of the seventh month in the Palace of Longevity, whispering when none were near: 'In heaven we would be twin-wing birds flying together; on earth, twin branches intertwined.' Heaven and earth enduring may have an end, but this regret stretches forever without close!",
     "白居易長篇敘事詩巔峰之作，宛轉動人流暢如歌，「在天願作比翼鳥，此恨綿綿無絕期」成為千古愛情詠嘆傳唱之絕唱。",
     "【漢越音考證】恨 (Hận), 眸 (Mâu), 黛 (Đại), 嵬 (Ngôi), 翼 (Dực), 連 (Liên), 枝 (Chi).",
     [{"viet": "Tại thiên nguyện tác bỉ dực điểu, tại địa nguyện vi liên lý chi. Thiên trường địa cửu hữu thời tận, thử hận miên miên vô tuyệt kỳ.", "zh": "在天願作比翼鳥，在地願為連理枝。天長地久有時盡，此恨綿綿無絕期。", "en": "In heaven may we fly as twin-winged birds, on earth grow as intertwined branches. Heaven and earth may end, but this regret goes on forever.", "hanViet": "Tại thiên nguyện tác bỉ dực điểu"}]),

    # Round 25: 晚唐綺麗與李商隱
    (25, "v4", "r25_01_lishangyin_jinse", "李商隱《錦瑟》", "Lý Thương Ẩn - Cẩm Sắt", "Li Shangyin: The Inlaid Zither", "李商隱", "Lý Thương Ẩn", "晚唐", "Vãn Đường",
     "錦瑟無端五十絃，一絃一柱思華年。莊生曉夢迷蝴蝶，望帝春心託杜鵑。滄海月明珠有淚，藍田日暖玉生煙。此情可待成追憶，只是當時已惘然。",
     "華美的錦瑟無端生出五十根琴弦，每一弦每一柱都令人追憶逝去的青春華年。莊周夢蝶空靈迷茫，望帝春心寄託杜鵑啼血。滄海水底明月照耀鮫人落淚成珠，藍田暖日升起良玉煙嵐。這般深情豈待今日才成追憶，早在當年身歷其境時便已迷惘悵惘！",
     "The patterned zither has fifty strings for no reason, each string and bridge recalls prime years. Zhuangzi's dawn dream confused with butterflies, King Wang's spring heart entrusted to cuckoos. Could this deep love wait to become a memory? Even then I was already lost in melancholy.",
     "李商隱無題詩之代表作，朦朧多義辭采淒美，被譽為唐代抒情詩最幽微深邃之象徵主義絕品。",
     "【漢越音考證】瑟 (Sắt), 絃 (Huyền), 杜 (Đỗ), 鵑 (Quyên), 滄 (Thương), 惘 (Võng).",
     [{"viet": "Thử tình khả đãi thành truy ức, chỉ thị đương thời dĩ võng nhiên.", "zh": "此情可待成追憶，只是當時已惘然。", "en": "Could such deep love wait only to become a memory? Even at that moment I was already lost in melancholy.", "hanViet": "Thử tình khả đãi thành truy ức"}]),

    (25, "v4", "r25_02_lishangyin_wuti", "李商隱《無題·相見時難》", "Lý Thương Ẩn - Vô Đề", "Li Shangyin: Untitled (Hard to Meet)", "李商隱", "Lý Thương Ẩn", "晚唐", "Vãn Đường",
     "相見時難別亦難，東風無力百花殘。春蠶到死絲方盡，蠟炬成灰淚始乾。曉鏡但愁雲鬢改，夜吟應覺月光寒。蓬山此去無多路，青鳥殷勤為探看。",
     "相聚艱難離別亦難，東風無力殘花飄零。春蠶直到死亡吐絲方盡，蠟燭燃燒成灰淚痕才乾。蓬萊仙山路途雖遠，祈請青鳥殷勤前往探望慰問。",
     "Hard to meet, and hard to part as well! The spring silkworm spins silk until death; the candle burns to ash before its tears run dry.",
     "「春蠶到死絲方盡，蠟炬成灰淚始乾」以至死不渝之比喻寫盡愛之執著與奉獻，成為千古傳誦之至情警句。",
     "【漢越音考證】蠶 (Tàm), 絲 (Ti",
     [{"viet": "Xuân tàm đáo tử ty phương tận, lạp cự thành hôi lệ thủy can.", "zh": "春蠶到死絲方盡，蠟炬成灰淚始乾。", "en": "The spring silkworm weaves silk until death; the candle turns to ashes before tears run dry.", "hanViet": "Xuân tàm đáo tử ty phương tận"}])
]

# Complete remainder of volume 4
vol4_items.extend([
    (25, "v4", "r25_03_dumu_epangfu", "杜牧《阿房宮賦》", "Đỗ Mục - A Phòng Cung Phú", "Du Mu: Rhapsody on Epang Palace", "杜牧", "Đỗ Mục", "晚唐", "Vãn Đường",
     "六王畢，四海一，蜀山兀，阿房出。覆壓三百餘里，隔離天日。戍卒叫，函谷舉，楚人一炬，可憐焦土！滅六國者六國也，非秦也；族秦者秦也，非天下也。嗟乎！使六國各愛其人，則足以拒秦；使秦復愛六國之人，則遞三世可至萬世而為君，誰得而族滅也？秦人不暇自哀，而後人哀之；後人哀之而不鑑之，亦使後人而復哀後人也！",
     "阿房宮宏偉奢靡覆壓三百里，耗盡天下民力。戍卒陳勝一呼楚人項羽一炬化為焦土。滅六國者六國自身也，滅秦者秦之暴虐也。後人哀秦若不以秦為鑑，必使後世復哀後人！",
     "Six kings fell, four seas were unified; Mount Shu was stripped bare, Epang Palace arose! Those who destroyed the Six States were the Six States themselves, not Qin; what annihilated Qin was Qin itself, not the world!",
     "杜牧借秦朝奢靡速亡之歷史教訓，諷諫晚唐統治者切勿重蹈覆轍，氣勢如虹議論警闢。",
     "【漢越音考證】房 (Phòng), 兀 (Ngột), 炬 (Cự), 焦 (Tiêu), 鑑 (Giám).",
     [{"viet": "Hậu nhân ai chi nhi bất giám chi, diệc sử hậu nhân nhi phục ai hậu nhân dã!", "zh": "後人哀之而不鑑之，亦使後人而復哀後人也！", "en": "If later generations lament without taking warning from it, they will only cause future generations to lament for them in turn!", "hanViet": "Hậu nhân ai chi nhi bất giám chi"}]),

    (25, "v4", "r25_04_dumu_boqinhuai", "杜牧《泊秦淮》", "Đỗ Mục - Bạc Tần Hoài", "Du Mu: Mooring at Qinhuai River", "杜牧", "Đỗ Mục", "晚唐", "Vãn Đường",
     "煙籠寒水月籠沙，夜泊秦淮近酒家。商女不知亡國恨，隔江猶唱後庭花。",
     "如煙迷濛的水氣籠罩著冰冷的河水，清冷月光籠罩著白沙，夜晚停泊在秦淮河畔靠近酒家之處。賣唱的歌女不懂得亡國破滅之遺恨，隔著江水依然高唱陳後主亡國淫靡之曲《玉樹後庭花》。",
     "Mist veils cold waters, moonlight carpets the sands; moored at night on Qinhuai by taverns near. The singing girl knows nothing of fallen nations' grief, still singing 'Courtyard Flowers' across the stream.",
     "杜牧借景抒懷，批評晚唐達官貴人沉湎於紙醉金迷不知大難將臨，諷刺深刻筆力千鈞。",
     "【漢越音考證】泊 (Bạc), 淮 (Hoài), 籠 (Lung), 唱 (Xướng).",
     [{"viet": "Thương nữ bất tri vong quốc hận, cách giang do xướng Hậu đình hoa.", "zh": "商女不知亡國恨，隔江猶唱後庭花。", "en": "The singing girl knows nothing of fallen nations' grief, still singing Courtyard Flowers across the stream.", "hanViet": "Thương nữ bất tri vong quốc hận"}]),

    (25, "v4", "r25_05_liyu_yumeiren", "李煜《虞美人·春花秋月何時了》", "Lý Dục - Ngu Mỹ Nhân", "Li Yu: Beautiful Lady Yu", "李煜", "Lý Dục", "五代·南唐", "Ngũ Đại - Nam Đường",
     "春花秋月何時了？往事知多少。小樓昨夜又東風，故國不堪回首月明中。雕欄玉砌應猶在，只是朱顏改。問君能有幾多愁？恰似一江春水向東流。",
     "春花秋月歲月流轉何時才了結？往昔錦繡往事知多少。昨夜小樓又吹東風，故國明月中不堪回首回望。雕欄玉砌宮殿應猶在，只是紅顏青春已凋零。要問心中有多少憂愁？恰如滿江春水滾滾向東流淌！",
     "Spring flowers and autumn moon, when will they cease? How much of the past is known? Carved railings and jade masonry must still remain, only rosy cheeks have changed. If asked how much sorrow I bear: Just like a river of spring water flowing east!",
     "詞中之帝李煜亡國絕筆，「問君能有幾多愁，恰似一江春水向東流」將抽象愁緒化為磅礴春江，為千古詞壇第一哀怨名句。",
     "【漢越音考證】煜 (Dục), 虞 (Ngu), 砌 (Thế), 雕 (Điêu), 欄 (Lan).",
     [{"viet": "Vấn quân năng hữu kỷ đa sầu? Kháp tự nhất giang xuân thủy hướng đông lưu.", "zh": "問君能有幾多愁？恰似一江春水向東流。", "en": "Ask how much sorrow one can bear? Just like a river of spring waters rolling east!", "hanViet": "Kháp tự nhất giang xuân thủy hướng đông lưu"}])
])

# Round 26, 27, 28 definitions
vol4_items.extend([
    # Round 26
    (26, "v4", "r26_01_sushi_shuidiaogetou", "蘇軾《水調歌頭·明月幾時有》", "Tô Thức - Thủy Điệu Ca Đầu", "Su Shi: Water Song Melody", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "明月幾時有？把酒問青天。不知天上宮闕，今夕是何年。我欲乘風歸去，又恐瓊樓玉宇，高處不勝寒。起舞弄清影，何似在人間！轉朱閣，低綺戶，照無眠。不應有恨，何事長向別時圓？人有悲歡離合，月有陰晴圓缺，此事古難全。但願人長久，千里共嬋娟。",
     "中秋望月懷子由。把酒問天欲乘風歸去，起舞弄清影何似在人間。月照無眠，人有悲歡離合月有陰晴圓缺此事古難全。但願人長久千里共嬋娟！",
     "Raising my wine cup, I ask the blue sky: When did the bright moon first arise? Men have grief and joy, parting and reunion; the moon has darkness and brightness, waxing and waning. May we live long and share this lovely moon across a thousand miles!",
     "胡仔《苕溪漁隱叢話》評：「中秋詞自東坡《水調歌頭》一出，餘詞盡廢。」豪放灑脫與曠達博愛輝映千古。",
     "【漢越音考證】闕 (Khuyết), 瓊 (Quỳnh), 宇 (Vũ), 嬋 (Thiền), 娟 (Quyên).",
     [{"viet": "Nhân hữu bi hoan ly hợp, nguyệt hữu âm tình viên khuyết, thử sự cổ nan toàn. Đãn nguyện nhân trường cửu, thiên lý cộng thiền quyên.", "zh": "人有悲歡離合，月有陰晴圓缺，此事古難全。但願人長久，千里共嬋娟。", "en": "Humans know grief, joy, parting and reunion; the moon waxes and wanes—perfection was rare since ancient times. May we endure and share this lovely moon across a thousand miles.", "hanViet": "Đãn nguyện nhân trường cửu thiên lý cộng thiền quyên"}]),

    (26, "v4", "r26_02_sushi_niannujiao", "蘇軾《念奴嬌·赤壁懷古》", "Tô Thức - Niệm Nô Kiều - Xích Bích Hoài Cổ", "Su Shi: Remembering Red Cliff", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "大江東去，浪淘盡，千古風流人物。故壘西邊，人道是，三國周郎赤壁。亂石崩雲，驚濤裂岸，捲起千堆雪。江山如畫，一時多少豪傑！遙想公瑾當年，小喬初嫁了，雄姿英發。羽扇綸巾，談笑間，檣櫓灰飛煙滅。故國神遊，多情應笑我，早生華髮。人生如夢，一尊還酹江月。",
     "長江滾滾東逝浪淘盡千古風流豪傑。遙想周瑜赤壁英姿雄發談笑間強敵檣櫓灰飛煙滅。人生如夢，舉杯灑酒敬江中明月。",
     "The great river surges east, its waves washing away all heroic figures across millennia. Life is like a dream; let me pour a libation to the river's moon!",
     "宋代豪放派詞第一里程碑，壯麗江山與英雄懷古交相輝映，開創宋詞豪邁雄渾之美學新境界。",
     "【漢越音考證】奴 (Nô), 嬌 (Kiều), 壘 (Lũy), 瑾 (Cẩn), 綸 (Luân), 櫓 (Lỗ), 酹 (Lỗi).",
     [{"viet": "Đại giang đông khứ, lãng đào tận, thiên cổ phong lưu nhân vật.", "zh": "大江東去，浪淘盡，千古風流人物。", "en": "The great river flows eastward, its waves washing away all heroic souls of a thousand ages.", "hanViet": "Đại giang đông khứ"}]),

    (26, "v4", "r26_03_liuyong_yulinling", "柳永《雨霖鈴·寒蟬淒切》", "Liễu Vĩnh - Vũ Lâm Linh", "Liu Yong: Bells in the Rain", "柳永", "Liễu Vĩnh", "北宋", "Bắc Tống",
     "寒蟬淒切，對長亭晚，驟雨初歇。都門帳飲無緒，留戀處，蘭舟催發。執手相看淚眼，竟無語凝噎。念去去，千里煙波，暮靄沉沉楚天闊。多情自古傷離別，更那堪，冷落清秋節！今宵酒醒何處？楊柳岸，曉風殘月。此去經年，應是良辰好景虛設。便縱有千種風情，更與何人說？",
     "長亭送別寒蟬淒切執手相看淚眼無語凝噎。千里煙波暮靄沉沉楚天闊。多情自古傷離別，今宵酒醒何處？楊柳岸曉風殘月。千種風情更與何人說！",
     "Lover holding hands in tearful silence. Boundless mists over southern skies. Since ancient times the tender-hearted grieve over parting; where shall I wake tonight? By willow banks beneath dawn's breeze and fading moon!",
     "柳永婉約詞頂峰，「楊柳岸，曉風殘月」為古代抒寫離愁別恨之最高藝術標誌，「凡有井水處，皆能歌柳詞」。",
     "【漢越音考證】霖 (Lâm), 蟬 (Thiền), 靄 (Ái), 凝 (Ngưng), 噎 (Yết).",
     [{"viet": "Đa tình tự cổ thương ly biệt, cánh na kham, lãnh lạc thanh thu tiết! Kim tiêu tửu tỉnh hà xứ? Dương liễu ngạn, hiểu phong tàn nguyệt.", "zh": "多情自古傷離別，更那堪，冷落清秋節！今宵酒醒何處？楊柳岸，曉風殘月。", "en": "Since antiquity the tender-hearted grieve at parting; where will I wake from wine tonight? By willow banks beneath dawn's breeze and a waning moon.", "hanViet": "Dương liễu ngạn hiểu phong tàn nguyệt"}]),

    (26, "v4", "r26_04_yanshu_huanxisha", "晏殊《浣溪沙·一曲新詞》", "Yến Thù - Hoán Khê Sa", "Yan Shu: Sand of Washing Stream", "晏殊", "Yến Thù", "北宋", "Bắc Tống",
     "一曲新詞酒一杯，去年天氣舊亭臺。夕陽西下幾時回？無可奈何花落去，似曾相識燕歸來。小園香徑獨徘徊。",
     "新詞一曲美酒一杯，去年天氣舊日亭臺。夕陽西下幾時能回？無可奈何春花凋落，似曾相識燕子歸來。獨自在落花小徑上漫步徘徊。",
     "A cup of wine to a new song, last year's weather by the old pavilion. Helplessly blossoms fall away; like old acquaintances, swallows return.",
     "「無可奈何花落去，似曾相識燕歸來」對仗天造地設，蘊含時光流逝與生命輪迴之深沉哲思，被譽為「天然奇偶」。",
     "【漢越音考證】浣 (Hoán), 溪 (Khê), 殊 (Thù), 燕 (Yến), 徑 (Kính).",
     [{"viet": "Vô khả nại hà hoa lạc khứ, tự tằng tương thức yến quy lai.", "zh": "無可奈何花落去，似曾相識燕歸來。", "en": "Helplessly flowers fall away; like old acquaintances swallows return.", "hanViet": "Vô khả nại hà hoa lạc khứ"}]),

    (26, "v4", "r26_05_qinguan_queqiaoxian", "秦觀《鵲橋仙·纖雲弄巧》", "Tần Quán - Thước Kiều Tiên", "Qin Guan: Immortals at the Magpie Bridge", "秦觀", "Tần Quán", "北宋", "Bắc Tống",
     "纖雲弄巧，飛星傳恨，銀漢迢迢暗度。金風玉露一相逢，便勝卻人間無數。柔情似水，佳期如夢，忍顧鵲橋歸路！兩情若是久長時，又豈在朝朝暮暮？",
     "牛郎織女七夕相逢，金風玉露一相逢便勝卻人間無數恩愛夫妻。柔情似水佳期如夢，兩情若是久長時，又豈在朝朝暮暮！",
     "Meeting once amidst autumn wind and jade dew surpasses countless reunions in mortal realm! If love between both hearts endures forever, why must they cling to day-in, day-out presence?",
     "秦觀打破傳統七夕詞哀怨悲嘆格調，立論「兩情若是久長時，又豈在朝朝暮暮」，將愛情昇華至崇高精神永恆境界。",
     "【漢越音考證】鵲 (Thước), 橋 (Kiều), 迢 (Điều), 露 (Lộ), 暮 (Mộ).",
     [{"viet": "Kim phong ngọc lộ nhất tương phùng, tiện thắng khước nhân gian vô số. Lưỡng tình nhược thị cửu trường thời, hựu khởi tại triêu triêu mộ mộ?", "zh": "金風玉露一相逢，便勝卻人間無數。兩情若是久長時，又豈在朝朝暮暮？", "en": "Meeting once in golden breeze and jade dew surpasses countless unions in mortal realm. If true love endures across time, what need is there to cling together day and night?", "hanViet": "Lưỡng tình nhược thị cửu trường thời"}]),

    # Round 27
    (27, "v4", "r27_01_xinqiji_pozhentzi", "辛棄疾《破陣子·為陳同甫賦壯詞》", "Tân Khí Tật - Phá Trận Tử", "Xin Qiji: Dance of the Cavalry", "辛棄疾", "Tân Khí Tật", "南宋", "Nam Tống",
     "醉裏挑燈看劍，夢回吹角連營。八百里分麾下炙，五十絃翻塞外聲，沙場秋點兵。馬作的盧飛快，弓如霹靂弦驚。了卻君王天下事，贏得生前身後名。可憐白髮生！",
     "醉中挑亮燈芯拔劍觀看，夢裡重回軍營號角連天。烤牛肉犒賞部下，五十絃奏塞外邊聲秋日沙場點兵。戰馬飛馳霹靂弦驚，誓了卻收復中原天下事贏得千秋英名，可憐英雄白髮已生！",
     "Drunk, I trim the lamp to examine my sword; dreaming of bugles echoing across encampments. Settling affairs for the Emperor and winning glory through all ages—alas, gray hair has already sprouted!",
     "稼軒詞豪放雄傑代表作，慷慨殺敵豪情與收復中原未遂壯志難酬之深悲巨慟形成強烈反差，沉鬱激昂。",
     "【漢越音考證】辛 (Tân), 棄 (Khí), 疾 (Tật), 麾 (Huy), 炙 (Chích), 霹 (Phách), 靂 (Lịch).",
     [{"viet": "Liễu khước quân vương thiên hạ sự, doanh đắc sinh tiền thân hậu danh. Khả liên bạch phát sinh!", "zh": "了卻君王天下事，贏得生前身後名。可憐白髮生！", "en": "Fulfilling the Emperor's grand enterprise, winning renown in life and after death—alas that white hairs have sprouted!", "hanViet": "Liễu khước quân vương thiên hạ sự"}]),

    (27, "v4", "r27_02_xinqiji_qingyuan", "辛棄疾《青玉案·元夕》", "Tân Khí Tật - Thanh Ngọc Án - Nguyên Tịch", "Xin Qiji: Lantern Festival Eve", "辛棄疾", "Tân Khí Tật", "南宋", "Nam Tống",
     "東風夜放花千樹，更吹落、星如雨。寶馬雕車香滿路。鳳簫聲動，玉壺光轉，一夜魚龍舞。蛾兒雪柳黃金縷，笑語盈盈暗香去。眾裏尋他千百度；驀然回首，那人卻在，燈火闌珊處。",
     "元宵節花燈如火樹銀花星落如雨，寶馬雕車遊人如織魚龍起舞。仕女盛裝笑語盈盈。在人海中千百次尋覓所思念之人，驀然回首，那人卻孤高獨立在燈火零落冷清之處！",
     "A thousand lights bloom like trees in night breeze; carriages and horses leave fragrance. Searching for her thousands of times among the crowd; suddenly turning back, there she is, standing where lights are dim!",
     "王國維《人間詞話》以此詞「眾裏尋他千百度，驀然回首，那人卻在燈火闌珊處」比喻古今成大事業大學問者之最高第三境界。",
     "【漢越音考證】案 (Án), 夕 (Tịch), 闌 (Lan), 珊 (San), 驀 (Mạch), 縷 (Lũ).",
     [{"viet": "Chúng lý tầm tha thiên bách độ; mạch nhiên hồi thủ, na nhân khước tại, đăng hỏa lan san xứ.", "zh": "眾裏尋他千百度；驀然回首，那人卻在，燈火闌珊處。", "en": "Seeking her thousands of times in the crowd; turning back suddenly, there she stands where lanterns are sparse and dim.", "hanViet": "Chúng lý tầm tha thiên bách độ"}]),

    (27, "v4", "r27_03_liqingzhao_shengshengman", "李清照《聲聲慢·尋尋覓覓》", "Lý Thanh Chiếu - Thanh Thanh Mạn", "Li Qingzhao: Slow, Slow Tune", "李清照", "Lý Thanh Chiếu", "南宋", "Nam Tống",
     "尋尋覓覓，冷冷清清，淒淒慘慘戚戚。乍暖還寒時候，最難將息。三杯兩盞淡酒，怎敵他、晚來風急！雁過也，正傷心，卻是舊時相識。滿地黃花堆積，憔悴損，如今有誰堪摘？守著窗兒，獨自怎生得黑！梧桐更兼細雨，到黃昏、點點滴滴。這次第，怎一個愁字了得！",
     "尋尋覓覓冷冷清清淒淒慘慘戚戚，十四疊字開篇寫盡國破夫亡孑然一身之淒楚孤苦。滿地殘菊梧桐細雨黃昏點點滴滴，這般苦痛豈是一個愁字所能道盡！",
     "Searching, seeking, cool and quiet, dreary, painful and forlorn! Drizzling rain on paulownia leaves at dusk—how can the single word 'sorrow' embrace it all!",
     "易安詞晚期絕唱，開頭連用十四疊字冠絕詞史，音韻哀婉淒絕，將家國身世之痛書寫得淋漓盡致。",
     "【漢越音考證】清 (Thanh), 照 (Chiếu), 覓 (Mịch), 慘 (Thảm), 戚 (Thích), 憔 (Tiều), 悴 (Tụy).",
     [{"viet": "Tầm tầm mịch mịch, lãnh lãnh thanh thanh, thê thê thảm thảm thích thích. Giá thứ đệ, chẩm nhất cá sầu tự liễu đắc!", "zh": "尋尋覓覓，冷冷清清，淒淒慘慘戚戚。這次第，怎一個愁字了得！", "en": "Searching and seeking, chilly and clear, dreary, mournful, and forlorn. How could a single word 'sorrow' ever capture this state!", "hanViet": "Tầm tầm mịch mịch lãnh lãnh thanh thanh"}]),

    (27, "v4", "r27_04_liqingzhao_yijianmei", "李清照《一剪梅·紅藕香殘》", "Lý Thanh Chiếu - Nhất Tiễn Mai", "Li Qingzhao: A Spray of Plum Blossoms", "李清照", "Lý Thanh Chiếu", "北宋", "Bắc Tống",
     "紅藕香殘玉簟秋。輕解羅裳，獨上蘭舟。雲中誰寄錦書來？雁字回時，月滿西樓。花自飄零水自流。一種相思，兩處閒愁。此情無計可消除，才下眉頭，卻上心頭。",
     "荷花凋謝竹席清涼秋意漸濃，獨登蘭舟望雲中雁字錦書。落花流水各自流淌，一種相思兩地同生愁緒。這份相思無計消除，剛從緊鎖的眉頭散開，又悄然湧上心頭。",
     "Red lotus fragrance fades, the jade mat turns cool. Flowers drift, water flows. One single longing stirs idle grief in two distant places; no way to banish this feeling: barely off the brows, it rises in the heart again!",
     "易安早期相思名篇，「一種相思，兩處閒愁。才下眉頭，卻上心頭」白描純真，將相思相憶之微妙心態寫入化境。",
     "【漢越音考證】剪 (Tiễn), 藕 (Ngẫu), 簟 (Điệm), 裳 (Thường), 愁 (Sầu).",
     [{"viet": "Hoa tự phiêu linh thủy tự lưu. Nhất chủng tương tư, lưỡng xứ nhàn sầu. Thử tình vô kế khả tiêu trừ, tài hạ mi đầu, khước thượng tâm đầu.", "zh": "花自飄零水自流。一種相思，兩處閒愁。此情無計可消除，才下眉頭，卻上心頭。", "en": "Blossoms drift and water flows on. One love longing brings quiet grief to two distant places; scarcely cleared from eyebrows, it surges in the heart again.", "hanViet": "Tài hạ mi đầu khước thượng tâm đầu"}]),

    (27, "v4", "r27_05_luyou_chaitoufeng", "陸游《釵頭鳳·紅酥手》", "Lục Du - Thoa Đầu Phụng", "Lu You: Phoenix Hairpin", "陸游", "Lục Du", "南宋", "Nam Tống",
     "紅酥手，黃縢酒，滿城春色宮牆柳。東風惡，歡情薄。一懷愁緒，幾年離索。錯！錯！錯！春如舊，人空瘦，淚痕紅浥鮫綃透。桃花落，閒池閣。山盟雖在，錦書難託。莫！莫！莫！",
     "陸游被迫休棄前妻唐婉，沈園重逢感舊傷懷題詞。東風殘酷歡情薄，幾年離索鑄成大錯。山盟海誓雖在錦書難通，滿腹悲痛只能咽淚連呼「錯！錯！錯！莫！莫！莫！」",
     "Red soft hands, yellow-sealed wine, city walls blooming with willows. The east wind was cruel, joy was fleeting! Years of parting: Wrong! Wrong! Wrong! Vows remain, but letters are hard to send: Cease! Cease! Cease!",
     "沈園題壁千古愛情悲劇絕唱，字字如杜鵑啼血，將封建禮教拆散恩愛夫妻之錐心劇痛抒寫得哀慟動地。",
     "【漢越音考證】釵 (Thoa), 鳳 (Phụng), 酥 (Tô), 縢 (Đằng), 綃 (Tiêu), 盟 (Minh).",
     [{"viet": "Sơn minh tuy tại, cẩm thư nan thác. Mạc! Mạc! Mạc!", "zh": "山盟雖在，錦書難託。莫！莫！莫！", "en": "Though our sacred vows endure, silk letters can scarce be sent. No more! No more! No more!", "hanViet": "Sơn minh tuy tại cẩm thư nan thác"}]),

    # Round 28
    (28, "v4", "r28_01_mazhiyuan_tianjingsha", "馬致遠《天淨沙·秋思》", "Mã Trí Viễn - Thiên Tịnh Sa - Thu Tứ", "Ma Zhiyuan: Autumn Thoughts", "馬致遠", "Mã Trí Viễn", "元代", "Nguyên",
     "枯藤老樹昏鴉，小橋流水人家，古道西風瘦馬。夕陽西下，斷腸人在天涯。",
     "枯藤纏繞著老樹，黃昏群鴉棲息，小橋流水旁坐落著溫馨人家，蕭瑟古道上迎著西風走著疲憊瘦馬。夕陽西沉墜入山下，極度傷感思鄉的遊子孤身漂泊在天涯海角。",
     "Withered vines, old trees, evening crows; small bridge, flowing water, rustic cottages; ancient path, west wind, lean horse. The evening sun sinks west: heartbroken wanderer at the edge of the world.",
     "被譽為「秋思之祖」，全篇僅二十八字，前三句純用九個名詞意象精巧疊加，烘托出旅人天涯漂泊之孤寂淒涼意境。",
     "【漢越音考證】致 (Trí), 遠 (Viễn), 藤 (Đằng), 鴉 (Nha), 腸 (Tràng), 涯 (Nhai).",
     [{"viet": "Khô đằng lão thụ hôn nha, tiểu kiều lưu thủy nhân gia, cổ đạo tây phong sấu mã. Tịch dương tây hạ, đoạn tràng nhân tại thiên nhai.", "zh": "枯藤老樹昏鴉，小橋流水人家，古道西風瘦馬。夕陽西下，斷腸人在天涯。", "en": "Withered vines, old trees, evening crows; small bridge, flowing brook, a peaceful cottage; ancient road, west wind, a lean horse. The sun sinks in the west: a heartbroken traveler at world's edge.", "hanViet": "Khô đằng lão thụ hôn nha"}]),

    (28, "v4", "r28_02_zhangyanghao_shanpoyang", "張養浩《山坡羊·潼關懷古》", "Trương Dưỡng Hạo - Sơn Pha Dương - Đồng Quan Hoài Cổ", "Zhang Yanghao: Meditations on Tongguan", "張養浩", "Trương Dưỡng Hạo", "元代", "Nguyên",
     "峰巒如聚，波濤如怒，山河表裏潼關路。望西都，意躊躇。傷心秦漢經行處，宮闕萬間都做了土。興，百姓苦；亡，百姓苦！",
     "群山峰巒匯聚波濤洶湧如怒，潼關山河險固。遠望西都長安感慨萬千，秦漢故都萬間宮殿盡化焦土。道破千古歷史興亡規律：國家興盛，百姓受苦勞役；國家滅亡，百姓受兵火之苦！",
     "Peaks converge like crowds, waves roar in rage along Tongguan pass. Looking upon the Western Capital, ten thousand palaces have turned to dust. When kingdoms rise, people suffer; when kingdoms fall, people suffer!",
     "元曲懷古名篇，「興，百姓苦；亡，百姓苦」以極大民本悲憫深刻揭穿封建王朝興亡循環中底層百姓之苦難。",
     "【漢越音考證】養 (Dưỡng), 浩 (Hạo), 巒 (Loan), 濤 (Đào), 潼 (Đồng), 躊 (Trù), 躇 (Trừ).",
     [{"viet": "Hưng, bách tính khổ; vong, bách tính khổ!", "zh": "興，百姓苦；亡，百姓苦！", "en": "When dynasties rise, the common people suffer; when dynasties fall, the common people suffer!", "hanViet": "Hưng bách tính khổ vong bách tính khổ"}]),

    (28, "v4", "r28_03_guanhanqing_doueyuan", "關漢卿《感天動地竇娥冤·滾繡球》", "Quan Hán Khanh - Đậu Nga Oan", "Guan Hanqing: The Injustice to Dou E", "關漢卿", "Quan Hán Khanh", "元代", "Nguyên",
     "有日月朝暮懸，有鬼神掌著生死權。天地也！只合把清濁分，可怎生糊突了盜跖、顏淵？為善的受貧窮更命短，造惡的享富貴又壽延。天地也！做得個怕硬欺軟，卻原來也這般順水推船！地也，你不分好歹何為地！天也，你錯勘賢愚枉做天！哎，只落得兩淚漣漣。",
     "善良貧女竇娥遭陷害受冤判斬。刑場指斥天地日月不分善惡顛倒清濁，發下三大誓願：血濺白練、六月飛雪、大旱三年以證清白。",
     "Heaven and Earth, you fear the strong and oppress the weak, drifting with the tide! Earth, if you cannot tell good from evil, why be called Earth? Heaven, if you mistake virtue for wickedness, in vain are you called Heaven!",
     "元雜劇悲劇之冠，竇娥臨刑之憤怒控訴天地不公，迸發出底層人民反抗腐朽司法與封建黑暗之震撼力量。",
     "【漢越音考證】竇 (Đậu), 娥 (Nga), 冤 (Oan), 跖 (Chích), 勘 (Khám), 漣 (Liên).",
     [{"viet": "Địa dã, nhĩ bất phân hảo đãi hà vi địa! Thiên dã, nhĩ thác khám hiền ngu uổng tác thiên!", "zh": "地也，你不分好歹何為地！天也，你錯勘賢愚枉做天！", "en": "Earth, if you tell not good from bad, why be the Earth! Heaven, if you mistake virtue for vice, in vain are you Heaven!", "hanViet": "Thiên dã nhĩ thác khám hiền ngu"}]),

    (28, "v4", "r28_04_baipu_tianjingsha", "白樸《天淨沙·秋》", "Bạch Phác - Thiên Tịnh Sa - Thu", "Bai Pu: Autumn", "白樸", "Bạch Phác", "元代", "Nguyên",
     "孤村落日殘霞，輕煙老樹寒鴉，一點飛鴻影下。青山綠水，白草紅葉黃花。",
     "孤落的村莊籠罩在落日與晚霞之中，炊煙輕裊老樹上棲著寒鴉，一隻孤鴻掠過晴空投下剪影。青山綠水相映，白草紅葉黃菊斑斕絢麗。",
     "A solitary village in sunset's residual clouds, light smoke, old trees and roosting crows, a single wild goose casts its fleeting shadow. Green mountains and blue streams, white grass, red leaves and yellow blossoms.",
     "白樸以鮮明色彩筆觸描繪秋景，明麗清朗擺脫傳統秋思之純然蕭瑟，色彩斑斕詩情如畫。",
     "【漢越音考證】樸 (Phác), 殘 (Tàn), 霞 (Hà), 鴻 (Hồng), 斑 (Ban).",
     [{"viet": "Thanh sơn lục thủy, bạch thảo hồng diệp hoàng hoa.", "zh": "青山綠水，白草紅葉黃花。", "en": "Green mountains and emerald waters, white grass, crimson leaves and golden blossoms.", "hanViet": "Thanh sơn lục thủy"}]),

    (28, "v4", "r28_05_wangshifu_xixiangji", "王實甫《西廂記·長亭送別》", "Vương Thực Phủ - Tây Sương Ký - Trường Đình Tống Biệt", "Wang Shifu: Romance of the Western Chamber", "王實甫", "Vương Thực Phủ", "元代", "Nguyên",
     "碧雲天，黃花地，西風緊，北雁南飛。曉來誰染霜林醉？總是離人淚。恨相見得遲，怨歸去得疾。柳絲長玉驄難繫，恨不倩疏林掛住斜暉。聽得一聲「去也」，鬆了金釧；遙望見十里長亭，減了玉肌。此恨誰知！",
     "十里長亭鶯鶯送別張生赴京應試。碧雲天黃花地西風緊北雁南飛，霜葉如醉皆是離人血淚所染。千般不捨萬般依戀。",
     "Azure clouds in the sky, yellow petals on the earth, west wind blowing sharp as northern geese fly south. Who dyed the frost-laden forest drunk at dawn? Always it is the parting lovers' tears!",
     "元曲文采最秀麗之名劇，「曉來誰染霜林醉，總是離人淚」化用范仲淹詩句，情景交融達到曲詞美學極峰。",
     "【漢越音考證】廂 (Sương), 驄 (Thông), 釧 (Xuyến), 染 (Nhiễm), 醉 (Túy).",
     [{"viet": "Bích vân thiên, hoàng hoa địa, tây phong khẩn, bắc nhạn nam phi. Hiểu lai thùy nhiễm sương lâm túy? Tổng thị ly nhân lệ.", "zh": "碧雲天，黃花地，西風緊，北雁南飛。曉來誰染霜林醉？總是離人淚。", "en": "Azure skies, yellow-flowered ground, autumn west wind keen, northern wild geese flying south. Who dyed the frosted forest with drunk crimson at dawn? It is always the tears of parting lovers.", "hanViet": "Hiểu lai thùy nhiễm sương lâm túy"}]),
])

print(f"Volume 4 items ready: {len(vol4_items)}")
