# -*- coding: utf-8 -*-
"""Volume 1: 先秦諸子哲學與儒道源流 (Rounds 1-7, 35 works)"""

vol1_items = [
    # Round 1
    (1, "v1", "r01_01_analects_xueer", "《論語·學而篇》", "Luận Ngữ - Thiên Học Nhi", "The Analects: Xue Er", "孔子及弟子", "Khổng Tử & Môn Đệ", "春秋", "Xuân Thu",
     "子曰：「學而時習之，不亦說乎？有朋自遠方來，不亦樂乎？人不知而不慍，不亦君子乎？」有子曰：「君子務本，本立而道生。孝弟也者，其為仁之本與！」",
     "孔子說：「學習知識並按時溫習實踐，不也很快樂喜悅嗎？有朋友從遠方前來交流，不也很高興嗎？別人不了解自己卻不怨恨，不也是有涵養的君子嗎？」有若說：「君子專心致力於根本，根本確立了道德原則就會自然產生。孝順父母敬愛兄長，這正是實行仁德的根本啊！」",
     "Confucius said: 'Is it not pleasant to learn with constant perseverance and practice? Is it not delightful to have friends coming from distant quarters?'",
     "《學而篇》為《論語》首篇，確立儒家修己、安人、好學與孝悌為仁之本的倫理政治體系。",
     "【漢越音考證】學 (Học), 而 (Nhi), 時 (Thời), 習 (Tập), 之 (Chi), 朋 (Bằng), 遠 (Viễn), 樂 (Lạc), 君 (Quân), 子 (Tử), 孝 (Hiếu), 弟 (Đệ), 仁 (Nhân).",
     [{"viet": "Học nhi thời tập chi, bất diệc duyệt hồ.", "zh": "學而時習之，不亦說乎。", "en": "To learn and practice constantly, is it not pleasant?", "hanViet": "Học nhi thời tập chi"}]),
    
    (1, "v1", "r01_02_analects_weizheng", "《論語·為政篇》", "Luận Ngữ - Thiên Vi Chính", "The Analects: Wei Zheng", "孔子及弟子", "Khổng Tử & Môn Đệ", "春秋", "Xuân Thu",
     "子曰：「為政以德，譬如北辰，居其所而眾星共之。」子曰：「吾十有五而志於學，三十而立，四十而不惑，五十而知天命，六十而耳順，七十而從心所欲，不踰矩。」",
     "孔子說：「用道德教化治理政事，就如同北極星穩居其位而眾星環繞拱衛。」孔子回顧人生修養進程：十五志於學，三十而立，四十不惑，五十知天命，六十耳順，七十從心所欲不踰矩。",
     "Confucius said: 'He who exercises government by virtue may be compared to the north polar star. At thirty I stood firm, at forty had no doubts, at fifty knew Heaven's decree.'",
     "《為政篇》闡述德治思想與士人人格修養階段境界，是東亞儒家社會政治哲學的核心基石。",
     "【漢越音考證】政 (Chính), 德 (Đức), 辰 (Thần), 志 (Chí), 立 (Lập), 惑 (Hoặc), 命 (Mệnh), 順 (Thuận), 矩 (Củ).",
     [{"viet": "Vi chính dĩ đức, thí như bắc thần, cư kỳ sở nhi chúng tinh củng chi.", "zh": "為政以德，譬如北辰，居其所而眾星共之。", "en": "Governing by virtue is like the North Star.", "hanViet": "Vi chính dĩ đức"}]),

    (1, "v1", "r01_03_mencius_lianghuiwang", "《孟子·梁惠王上》", "Mạnh Tử - Lương Huệ Vương Thượng", "Mencius: King Hui of Liang", "孟子及弟子", "Mạnh Tử", "戰國", "Chiến Quốc",
     "孟子見梁惠王。王曰：「叟！不遠千里而來，亦將有以利吾國乎？」孟子對曰：「王何必曰利？亦有仁義而已矣。上下交征利而國危矣！」",
     "孟子拜見梁惠王。王問何以利吾國，孟子答以何必言利，但求仁義而已。上下交相爭利則國家危殆。",
     "Mencius saw King Hui of Liang. When the king asked how to profit the kingdom, Mencius replied: 'Why must your Majesty speak of profit? There is only benevolence and righteousness.'",
     "孟子發揚孔子儒學，開篇以義利之辨立論，奠定民本王道與道德功利主義之批判。",
     "【漢越音考證】梁 (Lương), 惠 (Huệ), 王 (Vương), 利 (Lợi), 義 (Nghĩa), 國 (Quốc), 危 (Nguy).",
     [{"viet": "Vương hà tất viết lợi? Diệc hữu nhân nghĩa nhi dĩ hĩ.", "zh": "王何必曰利？亦有仁義而已矣。", "en": "Why speak of profit? There is only benevolence and righteousness.", "hanViet": "Vương hà tất viết lợi"}]),

    (1, "v1", "r01_04_daxue_daode", "《大學·經一章》", "Đại Học - Kinh Nhất Chương", "The Great Learning: Opening", "曾子 (傳)", "Tăng Tử", "先秦", "Tiên Tần",
     "大學之道，在明明德，在親民，在止於至善。物格而后知至，知至而后意誠，意誠而后心正，心正而后身修，身修而后家齊，家齊而后國治，國治而后天下平。",
     "大學宗旨在大明德性、親愛人民、止於至善。由格物致知、誠意正心、修身齊家，終至治國平天下。",
     "The Great Learning teaches illustrating illustrious virtue, renovating people, and resting in the highest excellence.",
     "《大學》架構儒家修齊治平三綱八條目，為東亞士人立身處世與治國之終極藍圖。",
     "【漢越音考證】大 (Đại), 學 (Học), 明 (Minh), 德 (Đức), 善 (Thiện), 格 (Cách), 物 (Vật), 齊 (Tề), 治 (Trị), 平 (Bình).",
     [{"viet": "Đại học chi đạo, tại minh minh đức, tại thân dân, tại chỉ ư chí thiện.", "zh": "大學之道，在明明德，在親民，在止於至善。", "en": "Great learning teaches illustrating virtue and resting in supreme good.", "hanViet": "Đại học chi đạo"}]),

    (1, "v1", "r01_05_zhongyong_tianming", "《中庸·首章》", "Trung Dung - Thủ Chương", "The Doctrine of the Mean: Chapter 1", "子思 (傳)", "Tử Tư", "先秦", "Tiên Tần",
     "天命之謂性，率性之謂道，修道之謂教。道也者，不可須臾離也。莫見乎隱，莫顯乎微，故君子慎其獨也。致中和，天地位焉，萬物育焉。",
     "天賦稟性為性，循性為道，修治為教。君子戒慎不睹、恐懼不聞而慎獨。達致中和，則天地各得其位，萬物化育生長。",
     "What Heaven confers is Nature; following nature is the Path; regulating the Path is Instruction. Equilibrium and harmony foster all life under Heaven.",
     "《中庸》建立儒家天人合一形上學，慎獨存養與致中和為至高心性修養體系。",
     "【漢越音考證】中 (Trung), 庸 (Dung), 命 (Mệnh), 性 (Tính), 道 (Đạo), 慎 (Thận), 獨 (Độc), 和 (Hòa), 育 (Dục).",
     [{"viet": "Thiên mệnh chi vị tính, suất tính chi vị đạo, tu đạo chi vị giáo.", "zh": "天命之謂性，率性之謂道，修道之謂教。", "en": "What Heaven confers is nature; following nature is the Path.", "hanViet": "Thiên mệnh chi vị tính"}]),

    # Round 2
    (2, "v1", "r02_01_daodejing_01", "《道德經·第一章》", "Đạo Đức Kinh - Chương 1", "Tao Te Ching: Chapter 1", "老子", "Lão Tử", "春秋", "Xuân Thu",
     "道可道，非常道；名可名，非常名。無名天地之始；有名萬物之母。故常無欲，以觀其妙；常有欲，以觀其徼。玄之又玄，眾妙之門。",
     "可用言語表述之道非永恆常道；可定義之名非永恆常名。無名為天地始，有名為萬物母。玄妙深邃，為探求萬物奧妙之門。",
     "The Tao that can be spoken is not the eternal Tao. The nameless is the origin of Heaven and Earth.",
     "老子破除世俗概念局限，揭示大道本體之深邃幽玄與超驗自然。",
     "【漢越音考證】道 (Đạo), 德 (Đức), 名 (Danh), 常 (Thường), 無 (Vô), 有 (Hữu), 妙 (Diệu), 玄 (Huyền).",
     [{"viet": "Đạo khả đạo, phi thường đạo; danh khả danh, phi thường danh.", "zh": "道可道，非常道；名可名，非常名。", "en": "The Tao that can be spoken is not the eternal Tao.", "hanViet": "Đạo khả đạo"}]),

    (2, "v1", "r02_02_daodejing_08", "《道德經·第八章》", "Đạo Đức Kinh - Chương 8", "Tao Te Ching: Chapter 8", "老子", "Lão Tử", "春秋", "Xuân Thu",
     "上善若水。水善利萬物而不爭，處眾人之所惡，故幾於道。居善地，心善淵，與善仁，言善信，正善治，事善能，動善時。夫唯不爭，故無尤。",
     "最崇高的善德如同水。水利萬物而不與物爭，居眾人厭惡之下位，故近於道。唯其不爭，故無怨尤過失。",
     "Highest excellence is like water, benefiting all things without striving, staying in low places that all dislike.",
     "以水喻道，闡述老子處下、守柔、不爭、清靜無為之極高人生智慧。",
     "【漢越音考證】上 (Thượng), 善 (Thiện), 若 (Nhược), 水 (Thủy), 爭 (Tranh), 淵 (Uyên), 仁 (Nhân), 信 (Tín), 治 (Trị).",
     [{"viet": "Thượng thiện nhược thủy. Thủy thiện lợi vạn vật nhi bất tranh.", "zh": "上善若水。水善利萬物而不爭。", "en": "Highest virtue is like water, benefiting all without striving.", "hanViet": "Thượng thiện nhược thủy"}]),

    (2, "v1", "r02_03_zhuangzi_xiaoyaoyou", "《莊子·逍遙遊》", "Trang Tử - Tiêu Dao Du", "Zhuangzi: Free and Easy Wandering", "莊子", "Trang Tử", "戰國", "Chiến Quốc",
     "北冥有魚，其名為鯤。鯤之大，不知其幾千里也；化而為鳥，其名為鵬。鵬之背，不知其幾千里也；怒而飛，其翼若垂天之雲。摶扶搖而上者九萬里！",
     "北海巨鯤化為大鵬，雙翼若垂天之雲，乘盤旋颶風直上九萬里高空飛往南海。小知不及大知，追求絕待逍遙。",
     "In the Northern Ocean is a fish named Kun, transforming into the giant bird Peng rising 90,000 li on whirlwind.",
     "莊子以奇幻壯麗寓言破除有限凡俗束縛，倡導無待逍遙之超然精神自由。",
     "【漢越音考證】莊 (Trang), 逍 (Tiêu), 遙 (Dao), 遊 (Du), 鯤 (Côn), 鵬 (Bằng), 冥 (Minh), 翼 (Dực).",
     [{"viet": "Bắc minh hữu ngư, kỳ danh vi côn. Côn chi đại, bất tri kỳ kỷ thiên lý dã.", "zh": "北冥有魚，其名為鯤。鯤之大，不知其幾千里也。", "en": "In Northern Ocean is a fish named Kun.", "hanViet": "Bắc minh hữu ngư"}]),

    (2, "v1", "r02_04_zhuangzi_qiwulun", "《莊子·齊物論》", "Trang Tử - Tề Vật Luận", "Zhuangzi: On the Equality of Things", "莊子", "Trang Tử", "戰國", "Chiến Quốc",
     "昔者莊周夢為胡蝶，栩栩然胡蝶也，自喻適志與！不知周也。俄然覺，則蘧蘧然周也。不知周之夢為胡蝶與，胡蝶之夢為周與？此之謂物化。",
     "莊周夢中化蝶翩然自得，醒來乃知為莊周。不知周夢為蝶抑或蝶夢為周。主客相泯，融通萬物名為物化。",
     "Once Zhuang Zhou dreamed he was a butterfly. Awakening, he knew not if Zhou dreamed of butterfly or butterfly dreamed of Zhou.",
     "「莊周夢蝶」以超越二元對立之哲學睿智，探討主客互融與萬物齊一之崇高境地。",
     "【漢越音考證】齊 (Tề), 物 (Vật), 論 (Luận), 夢 (Mộng), 蝶 (Điệp), 覺 (Giác), 化 (Hóa).",
     [{"viet": "Thiên địa dữ ngã tịnh sinh, nhi vạn vật dữ ngã vi nhất.", "zh": "天地與我並生，而萬物與我為一。", "en": "Heaven, Earth and I were born together, all things and I are one.", "hanViet": "Thiên địa dữ ngã tịnh sinh"}]),

    (2, "v1", "r02_05_zhuangzi_yangshengzhu", "《莊子·養生主》", "Trang Tử - Dưỡng Sinh Chủ", "Zhuangzi: Caring for Life", "莊子", "Trang Tử", "戰國", "Chiến Quốc",
     "庖丁為文惠君解牛。庖丁釋刀對曰：「臣之所好者道也，進乎技矣。依乎天理，批大郤，導大窾，因其固然。以無厚入有間，恢恢乎其於遊刃必有餘地矣。」",
     "庖丁解牛合於音律。其言道進乎技，依循天然骨理縫隙下刀，以薄刃遊於骨節空間，故十九年而刀刃若新發於硎。",
     "Cook Ding carved an ox for Lord Wenhui. Ding said: 'What I love is the Tao, navigating gaps with ease and keeping the blade keen.'",
     "藉由庖丁解牛神技，喻示順應天理、避讓鋒芒、遊刃有餘之養生處世之法。",
     "【漢越音考證】養 (Dưỡng), 生 (Sinh), 庖 (Bào), 丁 (Đinh), 刀 (Đao), 技 (Kỹ), 理 (Lý), 刃 (Nhận).",
     [{"viet": "Thần chi sở hảo giả đạo dã, tiến hồ kỹ hĩ.", "zh": "臣之所好者道也，進乎技矣。", "en": "What I love is the Tao, which is beyond mere skill.", "hanViet": "Thần chi sở hảo giả đạo dã"}]),

    # Round 3: 法、兵、墨
    (3, "v1", "r03_01_sunzi_ji", "《孫子兵法·計篇》", "Tôn Tử Binh Pháp - Kế Thiên", "Sun Tzu: Strategic Assessments", "孫武", "Tôn Vũ", "春秋", "Xuân Thu",
     "兵者，國之大事，死生之地，存亡之道，不可不察也。故經之以五事，校之以計，而索其情：一曰道，二曰天，三曰地，四曰將，五曰法。",
     "軍事戰爭是國家的大事，關係到百姓生死與國家存亡，不可不認真考察研究。故從道、天、地、將、法五大要素全面衡量籌劃。",
     "Military action is of vital importance to the State, the province of life and death, the road to survival or ruin.",
     "《孫子兵法》首篇立論慎戰與戰略廟算，為世界軍事學最高經典。",
     "【漢越音考證】兵 (Binh), 計 (Kế), 道 (Đạo), 天 (Thiên), 地 (Địa), 將 (Tướng), 法 (Pháp).",
     [{"viet": "Binh giả, quốc chi đại sự, tử sinh chi địa, tồn vong chi đạo.", "zh": "兵者，國之大事，死生之地，存亡之道。", "en": "Military affairs are the vital matters of state.", "hanViet": "Binh giả quốc chi đại sự"}]),

    (3, "v1", "r03_02_sunzi_mougong", "《孫子兵法·謀攻篇》", "Tôn Tử Binh Pháp - Mưu Công Thiên", "Sun Tzu: Attack by Stratagem", "孫武", "Tôn Vũ", "春秋", "Xuân Thu",
     "不戰而屈人之兵，善之善者也。故知勝有五：知可以戰與不可以戰者勝，識眾寡之用者勝。知彼知己，百戰不殆；不知彼而知己，一勝一負；不知彼不知己，每戰必殆。",
     "不透過交戰而使敵軍屈服，才是高明中最高明的。知己知彼，百戰不會遭遇危殆。",
     "To subdue the enemy without fighting is the acme of skill. If you know the enemy and know yourself, you will not be imperiled in a hundred battles.",
     "謀攻篇主張全勝戰略與不戰而屈人之兵，強調知己知彼之情報與心理認知。",
     "【漢越音考證】謀 (Mưu), 攻 (Công), 勝 (Thắng), 敵 (Địch), 知 (Tri), 殆 (Đãi).",
     [{"viet": "Tri bỉ tri kỷ, bách chiến bất đãi.", "zh": "知彼知己，百戰不殆。", "en": "Know the enemy and know yourself, and you will not be imperiled in hundred battles.", "hanViet": "Tri bỉ tri kỷ bách chiến bất đãi"}]),

    (3, "v1", "r03_03_hanfeizi_wudu", "《韓非子·五蠹》", "Hàn Phi Tử - Ngũ Đỗ", "Han Feizi: The Five Vermin", "韓非", "Hàn Phi", "戰國", "Chiến Quốc",
     "宋人有耕者。田中有株，兔走觸株，折頸而死。因釋其耒而守株，冀復得兔。兔不可復得，而身為宋國笑。今欲以先王之政，治當世之民，皆守株之類也。世異則事異，事異則備變。",
     "宋國農夫守株待兔終無所得反遭恥笑。時代不同則政事不同，政事不同則法治措施必須因時變通革新。",
     "Past practices cannot fit present realities. If times change, circumstances change, and measures must adapt.",
     "法家集大成者韓非子倡導法、術、勢合一，以守株待兔寓言痛斥墨守成規。",
     "【漢越音考證】韓 (Hàn), 非 (Phi), 蠹 (Đỗ), 株 (Chu), 兔 (Thố), 變 (Biến).",
     [{"viet": "Thế dị tắc sự dị, sự dị tắc bị biến.", "zh": "世異則事異，事異則備變。", "en": "When times change, circumstances change, and adaptations must follow.", "hanViet": "Thế dị tắc sự dị"}]),

    (3, "v1", "r03_04_guanzi_mumin", "《管子·牧民》", "Quản Tử - Mục Dân", "Guanzi: Shepherding the People", "管仲 (傳)", "Quản Trọng", "春秋", "Xuân Thu",
     "倉廩實則知禮節，衣食足則知榮辱。上服度則六親固，四維不張，國乃滅亡。何謂四維？一曰禮，二曰義，三曰廉，四曰恥。",
     "糧倉充實人民自然懂得禮節，衣食富足百姓自然懂得榮辱。禮義廉恥為維繫國家存在之四大綱維。",
     "When the granaries are full, the people understand etiquette; when clothing and food are sufficient, they know honor and shame. Propriety, righteousness, integrity, and shame are the Four Pillars.",
     "管仲經世務實政治哲學，首開物質基礎決定道德風尚之經世濟民思想。",
     "【漢越音考證】管 (Quản), 牧 (Mục), 倉 (Thương), 廩 (Lẫm), 禮 (Lễ), 義 (Nghĩa), 廉 (Liêm), 恥 (Sỉ).",
     [{"viet": "Thương lẫm thực tắc tri lễ tiết, y thực túc tắc tri vinh nhục.", "zh": "倉廩實則知禮節，衣食足則知榮辱。", "en": "When granaries are full, people learn etiquette; when fed and clothed, they know honor and shame.", "hanViet": "Thương lẫm thực tắc tri lễ tiết"}]),

    (3, "v1", "r03_05_mozi_jianai", "《墨子·兼愛上》", "Mặc Tử - Kiêm Ái Thượng", "Mozi: Universal Love", "墨子及弟子", "Mặc Tử", "戰國", "Chiến Quốc",
     "聖人以治天下為事者也，必知亂之所自起，焉能治之。天下兼相愛則治，交相惡則亂。若使天下兼相愛，愛人若愛其身，猶有不孝者乎？視父兄與君若其身，惡施不孝？",
     "治理天下必知混亂根源。若人人兼相愛、交相利，視他人如己身，視人父如己父，天下自臻和平大治。",
     "Universal mutual love brings order, whereas mutual hatred brings chaos. Regard others as oneself.",
     "墨家以兼愛、非攻、尚賢、節用為綱領，展現底層平民與勞動者的博愛互助與和平理想。",
     "【漢越音考證】墨 (Mặc), 兼 (Kiêm), 愛 (Ái), 聖 (Thánh), 治 (Trị), 亂 (Loạn).",
     [{"viet": "Thiên hạ kiêm tương ái tắc trị, giao tương ố tắc loạn.", "zh": "天下兼相愛則治，交相惡則亂。", "en": "Universal love brings peace, mutual animosity brings chaos.", "hanViet": "Thiên hạ kiêm tương ái"}]),

    # Round 4: 易經、禮記、荀子
    (4, "v1", "r04_01_yijing_qian", "《易經·乾卦·文言》", "Dịch Kinh - Càn Quái Văn Ngôn", "I Ching: Hexagram Qian", "周文王 / 孔子", "Chu Văn Vương / Khổng Tử", "先秦", "Tiên Tần",
     "天行健，君子以自強不息。潛龍勿用，陽在下也。見龍在田，德施普也。終日乾乾，與時偕行。飛龍在天，大人造也。亢龍有悔，窮之災也。",
     "天體運行剛健不息，君子應當效法天道自強不息。潛龍勿用待時而動，見龍在田德化廣布，飛龍在天大展鴻圖，亢龍有悔戒慎盈滿。",
     "The movement of heaven is full of power; the superior man strengthens himself unceasingly.",
     "《易經》乾卦為群卦之首，象徵陽剛、進取與自強不息之君子生生之德。",
     "【漢越音考證】易 (Dịch), 乾 (Càn), 健 (Kiện), 強 (Cường), 息 (Tức), 龍 (Long), 悔 (Hối).",
     [{"viet": "Thiên hành kiện, quân tử dĩ tự cường bất tức.", "zh": "天行健，君子以自強不息。", "en": "As heaven's movement is vigorous, so must the gentleman ceaselessly strive.", "hanViet": "Thiên hành kiện"}]),

    (4, "v1", "r04_02_yijing_kun", "《易經·坤卦·文言》", "Dịch Kinh - Khôn Quái Văn Ngôn", "I Ching: Hexagram Kun", "周文王 / 孔子", "Chu Văn Vương / Khổng Tử", "先秦", "Tiên Tần",
     "地勢坤，君子以厚德載物。君子黃中通理，正位居體，美在其中，而暢於四支，發於事業，美之至也。",
     "大地的形勢厚實順從，君子當效法大地以深厚美德包容承載萬物。內心通達倫理美德，化為廣大功業。",
     "The earth's condition is receptive devotion; the superior man sustains all things with vast virtue.",
     "坤卦象徵大地之包容、厚德、順承與孕育，與乾卦乾坤並建，成天人和諧之象。",
     "【漢越音考證】坤 (Khôn), 地 (Địa), 勢 (Thế), 厚 (Hậu), 德 (Đức), 載 (Tải), 物 (Vật).",
     [{"viet": "Địa thế khôn, quân tử dĩ hậu đức tái vật.", "zh": "地勢坤，君子以厚德載物。", "en": "The earth's condition is receptive; the superior man sustains all with virtue.", "hanViet": "Địa thế khôn"}]),

    (4, "v1", "r04_03_liji_datong", "《禮記·禮運大同篇》", "Lễ Ký - Lễ Vận Đại Đồng", "Classic of Rites: The Great Harmony", "孔子及門人", "Khổng Tử", "先秦", "Tiên Tần",
     "大道之行也，天下為公。選賢與能，講信修睦。故人不獨親其親，不獨子其子。使老有所終，壯有所用，幼有所長，矜寡孤獨廢疾者皆有所養。是謂大同。",
     "當大道施行之時，天下為人人共有之天下。選拔賢能講求誠信和睦。老有所養、壯有所用、幼有所長、弱者皆受照顧，這便是大同社會。",
     "When the Great Way prevailed, the world was shared by all. Men of virtue and ability were chosen; mutual trust was cultivated. This is called the Great Harmony.",
     "《禮運大同》描摹儒家最高社會理想圖景，天下為公之理念深刻啟發東亞近現代民主大同思潮。",
     "【漢越音考證】禮 (Lễ), 運 (Vận), 大 (Đại), 同 (Đồng), 公 (Công), 賢 (Hiền), 能 (Năng), 睦 (Mục).",
     [{"viet": "Đại đạo chi hành dã, thiên hạ vi công.", "zh": "大道之行也，天下為公。", "en": "When the Great Way prevails, the world is shared by all.", "hanViet": "Đại đạo chi hành dã"}]),

    (4, "v1", "r04_04_liji_xueji", "《禮記·學記》", "Lễ Ký - Học Ký", "Classic of Rites: Record on Education", "戴聖 (編)", "Đới Thánh", "先秦", "Tiên Tần",
     "玉不琢，不成器；人不學，不知道。是故古之王者建國君民，教學為先。雖有嘉肴，弗食，不知其旨也；雖有至道，弗學，不知其善也。是故學然後知不足，教然後知困。教學相長也。",
     "美玉不雕琢不能成為精美器皿，人不學習就無法明白至道。教與學相互促進提升，此即教學相長。",
     "Jade uncut cannot make a vessel; a man untaught cannot know the Way. Teaching and learning foster each other.",
     "《學記》為人類史上最早之系統教育學專論，提出「教學相長、尊師重道、啟發引導」之精闢教學法則。",
     "【漢越音考證】琢 (Trác), 器 (Khí), 肴 (Hào), 旨 (Chỉ), 困 (Khốn), 長 (Trưởng / Tràng).",
     [{"viet": "Ngọc bất trác, bất thành khí; nhân bất học, bất tri đạo.", "zh": "玉不琢，不成器；人不學，不知道。", "en": "Jade uncut makes no vessel; man untaught knows not the Way.", "hanViet": "Ngọc bất trác bất thành khí"}]),

    (4, "v1", "r04_05_xunzi_quanxue", "《荀子·勸學》", "Tuân Tử - Khuyến Học", "Xunzi: Encouraging Learning", "荀況", "Tuân Huống", "戰國", "Chiến Quốc",
     "君子曰：學不可以已。青，取之於藍，而青於藍；冰，水為之，而寒於水。積土成山，風雨興焉；積水成淵，蛟龍生焉；積善成德，而神明自得，聖心備焉。故不積跬步，無以至千里；不積小流，無以成江海。騏驥一躍，不能十步；駑馬十駕，功在不舍。",
     "君子說：求學不可停止。青出於藍而勝於藍，冰水所成而寒於水。不累積半步無法達到千里之遙，不累積涓滴無法匯成江海。駿馬一躍不過十步，劣馬連駕十天亦能及遠，成功在於堅持不舍。",
     "Learning must never cease. Green comes from blue but is greener than blue. If you do not step forward inch by inch, you cannot reach a thousand li.",
     "荀子主張「性惡論」與後天積累化性起偽，勸學篇極力闡揚持之以恆之求學方法與修身信念。",
     "【漢越音考證】荀 (Tuân), 勸 (Khuyến), 藍 (Lam), 冰 (Băng), 跬 (Khuể), 步 (Bộ), 騏 (Kỳ), 驥 (Ký), 駑 (Nô).",
     [{"viet": "Thanh, thủ chi ư lam, nhi thanh ư lam; băng, thủy vi chi, nhi hàn ư thủy.", "zh": "青，取之於藍，而青於藍；冰，水為之，而寒於水。", "en": "Indigo extracted from blue is bluer than blue; ice formed from water is colder than water.", "hanViet": "Thanh thủ chi ư lam"}]),

    # Round 5: 先秦史傳與辯士策論
    (5, "v1", "r05_01_zuozhuan_caogui", "《左傳·曹劮論戰》", "Tả Truyện - Tào Quệ Luận Chiến", "Zuo Zhuan: Cao Gui on War", "左丘明", "Tả Khâu Minh", "春秋", "Xuân Thu",
     "公與之乘，戰於長勺。公將鼓之。劮曰：「未可。」齊人三鼓。劮曰：「可矣。」齊師敗績。既克，公問其故。對曰：「夫戰，勇氣也。一鼓作氣，再而衰，三而竭。彼竭我盈，故克之。」",
     "魯莊公與曹劮同乘戰車在長勺交戰。齊軍擊鼓三次士氣耗竭，曹劮方令魯軍擊鼓進攻大破齊軍。曹劮論戰道出：作戰全憑勇氣，一鼓作氣、再而衰、三而竭，敵衰我盛故能克敵制勝。",
     "Battle is a matter of courage. At the first drum courage is aroused, at the second it flags, at the third it is exhausted. When theirs was exhausted and ours full, we conquered.",
     "《左傳》以簡潔精煉筆法刻畫長勺之戰，曹劮「一鼓作氣」揭示掌握軍事心理與戰機之精髓。",
     "【漢越音考證】左 (Tả), 傳 (Truyện), 曹 (Tào), 劮 (Quệ), 鼓 (Cổ), 衰 (Suy), 竭 (Kiệt), 盈 (Doanh).",
     [{"viet": "Nhất cổ tác khí, tái nhi suy, tam nhi kiệt.", "zh": "一鼓作氣，再而衰，三而竭。", "en": "The first drum arouses courage, the second flags, the third exhausts.", "hanViet": "Nhất cổ tác khí"}]),

    (5, "v1", "r05_02_zuozhuan_zhuzhiwu", "《左傳·燭之武退秦師》", "Tả Truyện - Chúc Chi Vũ Thoái Tần Sư", "Zuo Zhuan: Zhu Zhiwu Persuades Qin", "左丘明", "Tả Khâu Minh", "春秋", "Xuân Thu",
     "晉侯、秦伯圍鄭。燭之武夜縋而出，見秦伯曰：「秦、晉圍鄭，鄭既知亡矣。若亡鄭而有益於君，敢以煩執事。越國以鄙遠，君知其難也。焉用亡鄭以陪鄰？鄰之厚，君之薄也。」秦伯說，與鄭人盟。",
     "秦晉圍鄭國。燭之武趁夜縋城出見秦穆公，分析利害：滅鄭只會增加晉國實力而削弱秦國，秦穆公悅服退兵並與鄭結盟。",
     "Crossing another country to govern a distant border is difficult. Why eliminate Zheng to enrich your rival Jin?",
     "燭之武憑三寸不爛之舌瓦解秦晉聯盟，展現春秋時期外交辭令與均勢博弈之高超謀略。",
     "【漢越音考證】燭 (Chúc), 武 (Vũ), 縋 (Trụy), 鄭 (Trịnh), 鄰 (Lân), 盟 (Minh).",
     [{"viet": "Lân chi hậu, quân chi bạc dã.", "zh": "鄰之厚，君之薄也。", "en": "The strengthening of your neighbor means the weakening of yourself.", "hanViet": "Lân chi hậu quân chi bạc dã"}]),

    (5, "v1", "r05_03_zhanguoce_fengxuan", "《戰國策·馮諼客孟嘗君》", "Chiến Quốc Sách - Phùng Huyên Khách Mạnh Thường Quân", "Zhan Guo Ce: Feng Xuan and Mengchang Jun", "劉向 (編)", "Lưu Hướng", "戰國", "Chiến Quốc",
     "齊人有馮諼者，貧乏不能自存，使人屬孟嘗君。後馮諼收債於薛，召諸民當償者悉來合券，因燒其券，民稱萬歲。馮諼曰：「臣竊矯君命，以責賜諸民，因燒其券，市義以歸。」狡兔三窟，得免其死。",
     "馮諼替孟嘗君薛地收債，當眾焚毀債券為孟嘗君買仁義。後孟嘗君失勢歸薛，百姓迎之，乃悟狡兔三窟免死之智。",
     "Feng Xuan burnt the debt bonds to purchase benevolence for Mengchang Jun, securing safe havens like a crafty rabbit with three burrows.",
     "戰國策名篇，刻畫戰國策士遠見卓識與「狡兔三窟、收買民心」之深謀遠慮。",
     "【漢越音考證】策 (Sách), 馮 (Phùng), 諼 (Huyên), 債 (Trái), 券 (Khoán), 窟 (Khúc / Quật).",
     [{"viet": "Xảo thố tam quật, đắc miễn kỳ tử.", "zh": "狡兔三窟，得免其死。", "en": "A crafty rabbit has three burrows to escape death.", "hanViet": "Xảo thố tam quật"}]),

    (5, "v1", "r05_04_zhanguoce_zouji", "《戰國策·鄒忌諷齊王納諫》", "Chiến Quốc Sách - Trâu Kỵ Phúng Tề Vương Nạp Gián", "Zhan Guo Ce: Zou Ji Admonishes King", "劉向 (編)", "Lưu Hướng", "戰國", "Chiến Quốc",
     "鄒忌修八尺有餘，而形貌昳麗。問妻、妾、客皆曰美於徐公。既見徐公，自以為不如。暮寢而思之，曰：「吾妻之美我者，私我也；妾之美我者，畏我也；客之美我者，欲有求於我也。」齊王乃下令納諫，門庭若市，燕趙韓魏皆朝於齊。",
     "鄒忌由妻妾客人私心奉承反思齊王受蒙蔽，諷喻齊王廣開言路納諫，使齊國大治威服鄰國。",
     "My wife praised me because she is partial to me; my concubine out of fear; my guest because he wants something from me. The King is far more deceived!",
     "以小見大、借家常琐事設喻諷諫，開創古代臣子委婉納諫之最高修辭範式。",
     "【漢越音考證】鄒 (Trâu), 忌 (Kỵ), 諷 (Phúng), 諫 (Gián), 私 (Tư), 畏 (Úy), 求 (Cầu).",
     [{"viet": "Ngô thê chi mỹ ngã giả, tư ngã dã; thiếp chi mỹ ngã giả, úy ngã dã.", "zh": "吾妻之美我者，私我也；妾之美我者，畏我也。", "en": "My wife praises me out of partiality, my concubine out of fear.", "hanViet": "Ngô thê chi mỹ ngã giả"}]),

    (5, "v1", "r05_05_liezi_tangwen", "《列子·湯問》", "Liệt Tử - Thang Vấn", "Liezi: Questions of Tang", "列禦寇 (傳)", "Liệt Ngự Khấu", "先秦", "Tiên Tần",
     "太行、王屋二山，方七百里，高萬仞。北山愚公者，年且九十，面山而居。懲山北之塞，出入之迂也，聚室而謀曰：「吾與汝畢力平險，指通豫南，達於漢陰，可乎？」河曲智叟笑而止之。愚公長息曰：「雖我之死，有子存焉；子又生孫，孫又生子；子又有子，子又有孫；子子孫孫無窮匱也，而山不加增，何苦而不平？」",
     "九十歲愚公率子孫移太行王屋二山。智叟笑其愚，愚公曰子孫無窮而山不加增。感格上天神祇移走二山。",
     "Though I die, my sons remain; sons have grandsons; grandsons have sons. Generations are endless, but the mountain increases not!",
     "「愚公移山」與「伯牙高山流水」為列子哲理寓言之絕唱，象徵持之以恆改造世界之無畏氣魄。",
     "【漢越音考證】列 (Liệt), 湯 (Thang), 愚 (Ngu), 公 (Công), 移 (Di), 仞 (Nhận), 匱 (Quỹ).",
     [{"viet": "Tử tử tôn tôn vô cùng quỹ dã, nhi sơn bất gia tăng, hà khổ nhi bất bình?", "zh": "子子孫孫無窮匱也，而山不加增，何苦而不平？", "en": "Generations of descendants are endless, while mountains grow not.", "hanViet": "Tử tử tôn tôn vô cùng quỹ dã"}]),

    # Round 6: 詩經、楚辭
    (6, "v1", "r06_01_shijing_guanju", "《詩經·周南·關雎》", "Thi Kinh - Chu Nam - Quan Thư", "Classic of Poetry: Guan Ju", "佚名", "Khuyết Danh", "西周", "Tây Chu",
     "關關雎鳩，在河之洲。窈窕淑女，君子好逑。參差荇菜，左右流之。窈窕淑女，寤寐求之。求之不得，寤寐思服。悠哉悠哉，輾轉反側。參差荇菜，左右采之。窈窕淑女，琴瑟友之。參差荇菜，左右芼之。窈窕淑女，鐘鼓樂之。",
     "河洲雎鳩相和鳴，美麗賢淑女子是君子美好佳偶。日夜思慕求之不得輾轉難眠，彈琴鼓瑟鳴鐘擊鼓迎娶歡慶。",
     "Guan-guan go the ospreys, on the islet in the river. The modest, retiring, virtuous, young lady: for our prince a good mate she.",
     "《詩經》開篇之作，賦比興手法純熟，哀而不傷樂而不淫，為東亞古代抒情詩歌總源頭。",
     "【漢越音考證】詩 (Thi), 關 (Quan), 雎 (Thư), 鳩 (Cưu), 洲 (Châu), 窈 (Yểu), 窕 (Điệu), 淑 (Thục), 逑 (Cầu).",
     [{"viet": "Quan quan thư cưu, tại hà chi châu. Yểu điệu thục nữ, quân tử hảo cầu.", "zh": "關關雎鳩，在河之洲。窈窕淑女，君子好逑。", "en": "Guan-guan go the ospreys on the river islet; the virtuous maiden is a fine match for the gentleman.", "hanViet": "Quan quan thư cưu"}]),

    (6, "v1", "r06_02_shijing_jianjia", "《詩經·秦風·蒹葭》", "Thi Kinh - Tần Phong - Kiêm Gia", "Classic of Poetry: Reeds", "佚名", "Khuyết Danh", "西周", "Tây Chu",
     "蒹葭蒼蒼，白露為霜。所謂伊人，在水一方。溯洄從之，道阻且長。溯游從之，宛在水中央。蒹葭萋萋，白露未晞。所謂伊人，在水之湄。蒹葭采采，白露未已。所謂伊人，在水之涘。",
     "蘆葦青翠白露凝霜，所思慕之人遠在水一方。逆流追尋道路險長，順流尋覓彷彿就在水中央。意境朦朧飄渺。",
     "The reeds are green, the white dew turned to frost. The one of whom I think is on the water's other side.",
     "以水景秋露烘托對理想美好伊人之追尋，朦朧意象與重章疊句展現極高抒情美感。",
     "【漢越音考證】蒹 (Kiêm), 葭 (Gia), 霜 (Sương), 溯 (Tố), 湄 (Mao / Mi), 涘 (Tễ).",
     [{"viet": "Kiêm gia thương thương, bạch lộ vi sương. Sở vị y nhân, tại thủy nhất phương.", "zh": "蒹葭蒼蒼，白露為霜。所謂伊人，在水一方。", "en": "Reeds are green and dew turned to frost; the one I love is across the water.", "hanViet": "Kiêm gia thương thương"}]),

    (6, "v1", "r06_03_chuci_lisao", "《楚辭·屈原·離騷(節選)》", "Sở Từ - Khuất Nguyên - Ly Tao", "Chuci: Li Sao (Encountering Sorrow)", "屈原", "Khuất Nguyên", "戰國", "Chiến Quốc",
     "長太息以掩涕兮，哀民生之多艱。余雖好修姱以鞿羈兮，謇朝誶而夕替。既替余以蕙纕兮，又申之以攬茝。亦余心之所善兮，雖九死其猶未悔！路曼曼其修遠兮，吾將上下而求索。",
     "長聲嘆息掩面流涕，哀憐人民生活的艱難困苦。只要合於我心中的崇高善德，即使為此死上九次我也絕不後悔！道路漫長而遼遠，我將上天下地不斷追尋求索。",
     "Long did I sigh and wipe away my tears, grieving for the hardships of people. For the ideal that my heart esteems, I would not regret though I died nine deaths! Long is the road, I will seek high and low.",
     "屈原《離騷》為長篇浪漫主義抒情詩冠冕，愛國情操與「九死不悔、上下求索」精神光照千古。",
     "【漢越音考證】楚 (Sở), 辭 (Từ), 離 (Ly), 騷 (Tao), 涕 (Thế), 蕙 (Huệ), 悔 (Hối), 索 (Tác / Sách).",
     [{"viet": "Diệc dư tâm chi sở thiện hề, tuy cửu tử kỳ do vị hối!", "zh": "亦余心之所善兮，雖九死其猶未悔！", "en": "For what my heart deems good, I would not regret though I died nine times!", "hanViet": "Tuy cửu tử kỳ do vị hối"}]),

    (6, "v1", "r06_04_chuci_shejiang", "《楚辭·屈原·涉江》", "Sở Từ - Khuất Nguyên - Thiệp Giang", "Chuci: Crossing the River", "屈原", "Khuất Nguyên", "戰國", "Chiến Quốc",
     "余幼好此奇服兮，年既老而不衰。帶長鋏之陸離兮，冠切雲之崔嵬。被明月兮珮寶璐。世溷濁而莫余知兮，吾方高馳而不顧。苟余心其端直兮，雖僻遠之何傷！",
     "我自幼喜愛奇特服飾，年歲已老志趣不衰。佩長劍戴高冠佩美玉。舉世混濁無人知我，只要內心正直，即便流放偏遠又有何妨！",
     "Since youth I loved fine attire, unchanged even in age. If my heart remains upright, what harm in exile to distant wilds?",
     "屈原借奇服美玉象徵高潔志節，展現堅持正義不與濁世同流合污之孤高忠魂。",
     "【漢越音考證】涉 (Thiệp), 江 (Giang), 鋏 (Kiệp), 冠 (Quan), 濁 (Trục), 顧 (Cố).",
     [{"viet": "Cẩu dư tâm kỳ đoan trực hề, tuy tích viễn chi hà thương!", "zh": "苟余心其端直兮，雖僻遠之何傷！", "en": "If my heart is upright, what harm in distant exile!", "hanViet": "Cẩu dư tâm kỳ đoan trực"}]),

    (6, "v1", "r06_05_chuci_yufu", "《楚辭·漁父》", "Sở Từ - Ngư Phụ", "Chuci: The Fisherman", "屈原 (傳)", "Khuất Nguyên", "戰國", "Chiến Quốc",
     "屈原既放，遊於江潭，行吟澤畔，顏色憔悴，形容枯槁。漁父見而問之曰：「子非三閭大夫與？何故至於斯？」屈原曰：「舉世皆濁我獨清，眾人皆醉我獨醒，是以見放。」漁父莞爾而笑，鼓枻而去，乃歌曰：「滄浪之水清兮，可以濯吾纓；滄浪之水濁兮，可以濯吾足。」遂去，不復與言。",
     "屈原遭流放澤畔行吟。漁父勸其隨俗沉浮，屈原誓不以清白之身蒙世俗塵埃。漁父笑唱滄浪之歌泛舟而去。",
     "Qu Yuan said: 'All the world is muddy, I alone am clear; all men are drunk, I alone am sober.' The fisherman rowed off singing: 'When the Canglang River is clean, I wash my hat ribbons; when muddy, I wash my feet.'",
     "「舉世皆濁我獨清，眾人皆醉我獨醒」與漁父滄浪之水對話，展現儒家固窮守道與道家隨順應化兩種人生哲學的經典碰撞。",
     "【漢越音考證】漁 (Ngư), 父 (Phụ), 澤 (Trạch), 憔 (Tiều), 悴 (Tụy), 濯 (Trạc), 纓 (Anh).",
     [{"viet": "Cử tri giai trọc ngã độc thanh, chúng nhân giai túy ngã độc tỉnh.", "zh": "舉世皆濁我獨清，眾人皆醉我獨醒。", "en": "All the world is muddy, I alone am clear; all men are drunk, I alone am sober.", "hanViet": "Cử tri giai trọc ngã độc thanh"}]),

    # Round 7: 諸子總結
    (7, "v1", "r07_01_xunzi_tianlun", "《荀子·天論》", "Tuân Tử - Thiên Luận", "Xunzi: Discourse on Nature", "荀況", "Tuân Huống", "戰國", "Chiến Quốc",
     "天行有常，不為堯存，不為桀亡。應之以治則吉，應之以亂則凶。強本而節用，則天不能貧；養備而動時，則天不能病。故明於天人之分，則可謂至人矣。制天命而用之！",
     "大自然運行有客觀規律，不因堯帝存在，不因桀王滅亡。加強根本節約開支自然不能使人貧困。掌握天人分別，制服自然規律加以利用。",
     "Nature acts with regularity: it does not exist for Yao, nor perish for Jie. Adapt to natural laws and master them for human benefit!",
     "荀子提出古代罕見之唯物主義自然觀，「天行有常、制天命而用之」打破盲目迷信天命之宿命論。",
     "【漢越音考證】天 (Thiên), 論 (Luận), 堯 (Nhiêu), 桀 (Kiệt), 凶 (Hung), 吉 (Cát), 制 (Chế).",
     [{"viet": "Thiên hành hữu thường, bất vi Nghiêu tồn, bất vi Kiệt vong.", "zh": "天行有常，不為堯存，不為桀亡。", "en": "Nature moves with regularity, existing not for Yao nor perishing for Jie.", "hanViet": "Thiên hành hữu thường"}]),

    (7, "v1", "r07_02_mozi_feigong", "《墨子·非攻上》", "Mặc Tử - Phi Công Thượng", "Mozi: Against Offensive Warfare", "墨子及弟子", "Mặc Tử", "戰國", "Chiến Quốc",
     "今有一人，入人園圃，竊其桃李，眾聞則非之，上為政者得則罰之。至殺不辜人也，其不義又甚。今至大為不義攻國，則弗知非，從而譽之，謂之義。此可謂知義與不義之辯乎？",
     "竊人桃李皆知為非，攻殺鄰國大肆掠奪卻反讚譽為義。墨子痛斥侵略戰爭之虛偽與不義，力倡非攻兼愛。",
     "Stealing a peach is condemned as wrong, yet attacking and looting another country is praised as righteous! How can this be knowing righteousness?",
     "墨家「非攻」學說從倫理底線揭露大國爭霸攻伐之殘暴，展現追求世界和平與反對侵略之偉大良知。",
     "【漢越音考證】非 (Phi), 攻 (Công), 竊 (Thiết), 圃 (Phố), 罰 (Phạt), 辜 (Cô).",
     [{"viet": "Thiên hạ chi đại hại, công phạt chi vi dã.", "zh": "攻國不義，天下之害。", "en": "Offensive warfare against kingdoms is the greatest injustice.", "hanViet": "Phi công thượng"}]),

    (7, "v1", "r07_03_hanfeizi_dingfa", "《韓非子·定法》", "Hàn Phi Tử - Định Pháp", "Han Feizi: Determining Laws", "韓非", "Hàn Phi", "戰國", "Chiến Quốc",
     "申不害言術而商鞅為法。術者，因任而授官，循名而責實，操殺生之柄，課群臣之能者也，此人主之所執也。法者，憲令著於官府，刑罰必於民心，賞存乎慎法，而罰加乎奸令者也，此臣民之所師也。",
     "申不害強調君王用人之「術」，商鞅確立國家法令制度之「法」。法術並用，君主操術於上，臣民守法於下。",
     "Methods (Shu) are wielded by the sovereign to evaluate ministers; Laws (Fa) are enacted by the state and observed by the people.",
     "韓非子融合商鞅之法、申不害之術與慎到之勢，構建古代中國最完備之法家中央集權法理學說。",
     "【漢越音考證】定 (Định), 術 (Thuật), 憲 (Hiến), 刑 (Hình), 柄 (Bính), 奸 (Gian).",
     [{"viet": "Pháp giả, hiến lệnh trứ ư quan phủ, hình phạt tất ư dân tâm.", "zh": "法者，憲令著於官府，刑罰必於民心。", "en": "Laws are decrees proclaimed in government offices and punishments trusted by the people.", "hanViet": "Pháp giả hiến lệnh trứ"}]),

    (7, "v1", "r07_04_lvshichunqiu_chajin", "《呂氏春秋·察今》", "Lữ Thị Xuân Thu - Sát Kim", "Master Lu's Spring and Autumn: Examining Present", "呂不韋門客", "Lữ Bất Vi Môn Khách", "戰國末", "Chiến Quốc Mạt",
     "楚人有涉江者，其劍自舟中墜於水，遽契其舟，曰：「是吾劍之所從墜。」舟止，從其所契者入水求之。舟已行矣，而劍不行，求劍若此，不亦惑乎？以此故法為其國與此同。時已徙矣，而法不徙，以此為治，豈不難哉？",
     "楚人刻舟求劍，船移而劍不移。世事環境隨時代遷徙，治國法度若不隨時代變革，如同刻舟求劍般荒謬。",
     "A man dropped his sword into river and carved a notch on the boat. The boat had moved but sword had not. How absurd to govern without adapting to changing times!",
     "「刻舟求劍」為古代批判守舊泥古之經典寓言，強調察今知變、順應時代潮流實行變法改革。",
     "【漢越音考證】呂 (Lữ), 察 (Sát), 墜 (Trụy), 遽 (Cự), 契 (Khế), 舟 (Chu), 惑 (Hoặc).",
     [{"viet": "Chu dĩ hành hĩ, nhi kiếm bất hành, cầu kiếm nhược thử, bất diệc hoặc hồ?", "zh": "舟已行矣，而劍不行，求劍若此，不亦惑乎？", "en": "The boat has moved but sword has not; is it not foolish to seek the sword thus?", "hanViet": "Khắc chu cầu kiếm"}]),

    (7, "v1", "r07_05_yanzi_chunqiu", "《晏子春秋·晏子使楚》", "Yến Tử Xuân Thu - Yến Tử Sứ Sở", "Annals of Yanzi: Envoy to Chu", "晏嬰 (傳)", "Yến Anh", "春秋", "Xuân Thu",
     "晏子使楚。楚王賜晏子酒。酒酣，吏二縛一人詣王。王曰：「縛者曷為者也？」對曰：「齊人也，坐盜。」王視晏子曰：「齊人固善盜乎？」晏子避席對曰：「嬰聞之：橘生淮南則為橘，生於淮北則為枳，葉徒相似，其實味不同。所以然者何？水土異也。今民生長於齊不盜，入楚則盜，得無楚之水土使民善盜耶？」楚王笑曰：「聖人非所與熙也，寡人反取病焉。」",
     "晏子出使楚國，楚王藉齊人盜竊羞辱齊國。晏子以「橘生淮南為橘，生於淮北為枳」巧妙回擊，指出乃楚國水土社會環境使人為盜，令楚王自取其辱。",
     "Oranges grown south of Huai River are sweet; grown north they turn bitter. The leaves are alike but fruits differ due to soil and water!",
     "晏子機智外交辯才名垂青史，南橘北枳揭示環境對人性形成之深遠作用。",
     "【漢越音考證】晏 (Yến), 嬰 (Anh), 橘 (Quất), 枳 (Chỉ), 淮 (Hoài), 盜 (Đạo).",
     [{"viet": "Quất sinh Hoài nam tắc vi quất, sinh ư Hoài bắc tắc vi chỉ.", "zh": "橘生淮南則為橘，生於淮北則為枳。", "en": "Oranges grown south of Huai River are sweet; north of Huai they turn to bitter trifoliate.", "hanViet": "Quất sinh Hoài nam"}]),
]

print(f"Volume 1 items ready: {len(vol1_items)}")
