# -*- coding: utf-8 -*-
"""Volume 6: 中越交流歷代名篇與越南漢喃文獻瑰寶 (Rounds 36-42, 35 works)"""

vol6_items = [
    # Round 36: 越南獨立宣言與立國名篇
    (36, "v6", "r36_01_lichangjie_nanguoshanhe", "李常傑《南國山河》", "Lý Thường Kiệt - Nam Quốc Sơn Hà", "Ly Thuong Kiet: Mountains and Rivers of the Southern Country", "李常傑", "Lý Thường Kiệt", "李朝", "Nhà Lý (1077)",
     "南國山河南帝居，截然定分在天書。如何逆虜來侵犯，汝等行看取敗虛！",
     "南方的江山由南方的帝王居住，天意神冊上早已截然劃定分明疆界。你們這些侵略逆虜憑什麼膽敢前來侵犯犯境？你們等著看吧，必定落得慘敗空亡！",
     "The mountains and rivers of the Southern realm are where the Southern Emperor abides, clearly decreed and bounded in the Book of Heaven. Why do you rebellious invaders dare transgress? You shall witness your own utter defeat!",
     "越南歷史上第一篇「獨立宣言」（Bản Tuyên ngôn độc lập đầu tiên），作於 1077 年如月江（Sông Như Nguyệt）抗宋之戰。確立越南獨立主權神聖不可侵犯之民族精神支柱。",
     "【漢越音考證】南 (Nam), 國 (Quốc), 山 (Sơn), 河 (Hà), 帝 (Đế), 居 (Cư), 截 (Tiệt), 書 (Thư), 虜 (Lỗ), 犯 (Phạm), 敗 (Bại), 虛 (Hư).",
     [{"viet": "Nam quốc sơn hà Nam đế cư, tiệt nhiên định phận tại thiên thư. Như hà nghịch lỗ lai xâm phạm, nhữ đẳng hành khán thủ bại hư!", "zh": "南國山河南帝居，截然定分在天書。如何逆虜來侵犯，汝等行看取敗虛！", "en": "The mountains and rivers of the Southern Country the Southern Emperor shall hold, as clearly decreed in the Book of Heaven. How dare foreign invaders transgress: you will witness your utter defeat!", "hanViet": "Nam quốc sơn hà Nam đế cư"}]),

    (36, "v6", "r36_02_chenxingdao_hich", "陳興道《諭諸裨將檄 (檄將士文)》", "Trần Hưng Đạo - Hịch Tướng Sĩ", "Tran Hung Dao: Proclamation to the Officers", "陳國峻 (陳興道)", "Trần Quốc Tuấn (Trần Hưng Đạo)", "陳朝", "Nhà Trần (1284)",
     "余常聞之：紀信以身代死而脫高帝，申蒯以背受刃而救襄子。古之忠烈，豈有終極！余每聞白燕使者橫行於道，以犬羊之肉，侮辱朝廷，常臨食廢箸，中夜撫枕，涕淚交橫，心痛如割。常慨然曰：恨未得食其肉、寢其皮、飲其血也！今汝等坐視國仇而不恤，教汝等以《兵書要略》，當體余心，戮力同心，誓滅狂虜，以保宗社萬世之安！",
     "陳興道抗擊元蒙大軍前夕發布檄文勉勵三軍將士：痛心敵使橫行，中夜撫枕痛哭，恨不得生吞其肉寢其皮。傳授《兵書要略》，誓全體將士同仇敵愾保衛江山宗廟！",
     "Hearing of the enemy's insults to our court, I forget to eat and weep at midnight, my heart torn with grief. I long to devour their flesh and sleep upon their hides! Let all officers unite as one to exterminate the invaders!",
     "越南軍事文學與愛國文獻最高豐碑，慷慨激烈氣吞山河，激勵陳朝三軍於白藤江大破元軍成就「東阿氣勢（Hào khí Đông A）」。",
     "【漢越音考證】興 (Hưng), 道 (Đạo), 檄 (Hịch), 裨 (Tì), 將 (Tướng), 箸 (Trợ), 割 (Cát), 虜 (Lỗ).",
     [{"viet": "Thường lâm thực phế trợ, trung dạ phủ chẩm, thế lệ giao hoành, tâm thống như cát.", "zh": "常臨食廢箸，中夜撫枕，涕淚交橫，心痛如割。", "en": "Often I forget my chopsticks at mealtime and toss upon my pillow at midnight, tears streaming down as my heart is cut with grief.", "hanViet": "Hịch tướng sĩ"}]),

    (36, "v6", "r36_03_chenguangqi_tunggia", "陳光啟《從軍行 (福成迎駕)》", "Trần Quang Khải - Tụng Giá Hoàn Kinh Sư", "Tran Quang Khai: Accompanying the Imperial Return", "陳光啟", "Trần Quang Khải", "陳朝", "Nhà Trần (1285)",
     "奪槊章陽渡，擒胡醎子關。太平須努力，萬古此江山！",
     "在章陽渡口英勇奪取敵軍長槊，在鹹子關大獲全勝生擒元軍胡虜。戰勝之後迎來國家太平，全體軍民更須全力努力建設，保證這大好錦繡江山萬古長青！",
     "Seizing spears at Zhangyang Ferry, capturing barbarian commanders at Xianzi Pass. In times of peace we must strive with all might to keep this homeland enduring through ten thousand ages!",
     "陳朝太師陳光啟抗元凱旋名詩，豪邁雄渾，「太平須努力，萬古此江山」凝聚居安思危與建設國家的千古警句。",
     "【漢越音考證】槊 (Sóc), 渡 (Độ), 擒 (Cầm), 關 (Quan), 萬 (Vạn), 古 (Cổ).",
     [{"viet": "Đoạt sóc Chương Dương độ, cầm Hồ Hàm Tử quan. Thái bình tu nỗ lực, vạn cổ thử giang sơn!", "zh": "奪槊章陽渡，擒胡醎子關。太平須努力，萬古此江山！", "en": "Seizing spears at Zhangyang Ferry, capturing invaders at Xianzi Pass. In peace we must redouble our efforts, that this homeland may endure through ten thousand ages!", "hanViet": "Đoạt sóc Chương Dương độ"}]),

    (36, "v6", "r36_04_ruanzhongyan_shuhoai", "阮忠彥《述懷》", "Nguyễn Trung Ngạn - Thuật Hoài", "Nguyen Trung Ngan: Expressing My Aspirations", "阮忠彥", "Nguyễn Trung Ngạn", "陳朝", "Nhà Trần",
     "介馬長戈下碧霄，男兒志氣薄雲霄。江山恰恰立功名，未了功名誓不休！",
     "男兒披甲跨駿馬執長戈自碧霄奔馳而下，昂揚志氣直衝九天雲霄。面對大好江山正當建功立業報效國家，功業未立誓不罷休！",
     "Armored steed and long spear sweeping from azure skies, a valiant man's spirit pierces the clouds. With homeland before me to achieve renown, until my mission is fulfilled I swear never to rest!",
     "陳朝名相名將抒懷詩，展現陳朝士大夫兼濟天下、文韜武略、昂揚奮進之英雄主義時代豪情。",
     "【漢越音考證】忠 (Trung), 彥 (Ngạn), 述 (Thuật), 懷 (Hoài), 戈 (Qua), 霄 (Tiêu).",
     [{"viet": "Nam nhi chí khí bạc vân tiêu. Giang sơn kháp kháp lập công danh.", "zh": "男兒志氣薄雲霄，江山恰恰立功名。", "en": "A valiant man's resolve reaches high above the clouds, striving to achieve glorious deeds for the homeland.", "hanViet": "Nam nhi chí khí bạc vân tiêu"}]),

    (36, "v6", "r36_05_hujimao_dapminhsu", "胡季犛《答明使》", "Hồ Quý Ly - Đáp Minh Sứ", "Ho Quy Ly: Reply to Ming Ambassador", "胡季犛", "Hồ Quý Ly", "胡朝", "Nhà Hồ (1400)",
     "君恩浩蕩如江海，自古炎荒奉化深。萬里梯航來上國，千秋風俗自南音。",
     "天朝皇恩浩蕩廣大如江海，自古南方疆土沐浴禮樂化育深厚。萬里跋涉梯山航海前來朝覲，千秋大越風俗本具南國自立之音！",
     "Imperial grace is vast as rivers and seas, yet across ten thousand miles of voyage, the ancient customs of the South retain their own independent music through thousands of autumns.",
     "胡季犛在明越外交交鋒中不卑不亢，既守外交禮數又維護本國自立文化主權，展現剛柔並濟之外交辭令。",
     "【漢越音考證】犛 (Ly), 梯 (Thê), 航 (Hàng), 音 (Âm), 荒 (Hoang).",
     [{"viet": "Vạn lý thê hàng lai thượng quốc, thiên thu phong tục tự nam âm.", "zh": "萬里梯航來上國，千秋風俗自南音。", "en": "Across ten thousand miles of voyage to the grand state, our customs through millennia retain our own Southern melody.", "hanViet": "Thiên thu phong tục tự nam âm"}]),

    # Round 37: 阮廌與平吳大誥
    (37, "v6", "r37_01_ruanzhi_pingwudaigao_1", "阮廌《平吳大誥 (開篇·立國大綱)》", "Nguyễn Trãi - Bình Ngô Đại Cáo (Khai Thiên)", "Nguyen Trai: Great Proclamation upon Pacifying the Wu", "阮廌", "Nguyễn Trãi", "後黎朝", "Nhà Hậu Lê (1428)",
     "代天行化，皇上若曰：蓋聞，仁義之舉，要在安民；弔伐之師，莫先去暴。惟我大越之國，素稱文獻之邦。山川之封域既殊，南北之風俗亦異。自趙、丁、李、陳之肇造我國，與漢、唐、宋、元而各帝一方。雖強弱時有不同，而豪傑世未常乏！",
     "阮廌奉黎太祖黎利之命作《平吳大誥》開篇：仁義之舉在於安定百姓，正義之師首在掃除暴虐。我大越之國自古為文獻之邦，山川疆域劃分既明，南北風俗亦異。歷代與漢唐宋元各帝一方互不相屬，世世代代英雄豪傑輩出！",
     "Benevolence and righteousness aim to bring peace to the people; righteous arms eliminate violence. Our Great Viet state has long been a land of culture. Mountains and rivers have distinct borders, customs in north and south differ; throughout dynasties we reigned as emperors alongside Han, Tang, Song, and Yuan!",
     "越南第二篇獨立宣言（Bản Tuyên ngôn độc lập thứ hai），被譽為「千古雄文（Thiên cổ hùng văn）」。從歷史、地理、文化哲理全面確立大越獨立神聖地位。",
     "【漢越音考證】廌 (Trãi), 誥 (Cáo), 邦 (Bang), 殊 (Thù), 肇 (Triệu), 乏 (Phạp).",
     [{"viet": "Nhân nghĩa chi cử, yếu tại an dân; điếu phạt chi sư, mạc tiên khứ bạo. Duy ngã Đại Việt chi quốc, tố xưng văn hiến chi bang.", "zh": "仁義之舉，要在安民；弔伐之師，莫先去暴。惟我大越之國，素稱文獻之邦。", "en": "Actions of benevolence and righteousness aim above all to bring peace to the people; punitive expeditions aim first to eradicate tyranny. Our Great Viet nation has ever been renowned as a realm of culture.", "hanViet": "Nhân nghĩa chi cử yếu tại an dân"}]),

    (37, "v6", "r37_02_ruanzhi_pingwudaigao_2", "阮廌《平吳大誥 (戰事抗暴與凱旋)》", "Nguyễn Trãi - Bình Ngô Đại Cáo (Khải Hoàn)", "Nguyen Trai: Great Proclamation - Victory", "阮廌", "Nguyễn Trãi", "後黎朝", "Nhà Hậu Lê (1428)",
     "彼猖狂以肆虐，毒流於民庶。仗義興師，奮起藍山。以弱制強，以寡敵眾。以大義而勝兇殘，以至仁而易暴虐！一怒而天下安，大開萬世之太平。洗百年之積恥，立萬古之奇功。社稷從此奠安，乾坤於此旋轉。告厥四方，咸使聞知！",
     "藍山起義以大義勝兇殘、以至仁克暴虐。旌旗變色風雲震駭，一朝凱旋洗雪百年之屈辱，開萬世大同之太平，山河社稷永奠平安！",
     "Wielding righteousness to overcome cruelty, employing supreme benevolence to replace tyranny! Washing away a century of accumulated humiliation, establishing eternal peace for the nation!",
     "氣吞日月之歷史史詩，提出「以大義而勝兇殘，以至仁而易暴虐」之崇高人道主義和平思想，光耀東亞軍事思想史。",
     "【漢越音考證】藍 (Lam), 殘 (Tàn), 旋 (Tuyền), 乾 (Càn), 坤 (Khôn).",
     [{"viet": "Dĩ đại nghĩa nhi thắng hung tàn, dĩ chí nhân nhi dịch bạo ngược. Tẩy bách niên chi tích sỉ, lập vạn cổ chi kỳ công.", "zh": "以大義而勝兇殘，以至仁而易暴虐。洗百年之積恥，立萬古之奇功。", "en": "Overcoming brutality with supreme righteousness, supplanting tyranny with utmost benevolence. Cleansing a century of accumulated humiliation and founding immortal renown for ten thousand ages!", "hanViet": "Dĩ đại nghĩa nhi thắng hung tàn"}]),

    (37, "v6", "r37_03_ruanzhi_bachdang", "阮廌《白藤江海口》", "Nguyễn Trãi - Bạch Đằng Hải Khẩu", "Nguyen Trai: Estuary of the Bach Dang River", "阮廌", "Nguyễn Trãi", "後黎朝", "Nhà Hậu Lê",
     "朔風吹浪白連天，極目滄波思昔年。大舶如山沉戟折，英雄事往浪自青。乾坤千古此江海，社稷百年逢治平。回首舊遊如一夢，登臨感慨寄長吟。",
     "北風吹動巨浪白浪滔天，極目蒼茫滄波遙想吳權、陳興道白藤江大捷古戰場。千百敵艦沉江折戟，英雄事蹟已逝唯江流依舊青碧。撫今追昔登臨寄慨。",
     "North wind whips white waves connecting sky and sea, surveying the vast waters recalling heroic past. Giant warships sunk like mountains, iron halberds broken; heroic feats passed while the river rolls green forever.",
     "阮廌登臨白藤江古戰場感懷名詩，借千古江山見證英雄功業與國家長治久安之深沉哲思。",
     "【漢越音考證】藤 (Đằng), 戟 (Kích), 舶 (Bạc), 朔 (Sóc).",
     [{"viet": "Anh hùng sự vãng lãng tự thanh, càn khôn thiên cổ thử giang hải.", "zh": "英雄事往浪自青，乾坤千古此江海。", "en": "Heroic feats have passed while waves roll green as ever; Heaven and Earth endure in this eternal river and sea.", "hanViet": "Bạch Đằng hải khẩu"}]),

    (37, "v6", "r37_04_ruanzhi_quanhai", "阮廌《關海 (神投海口)》", "Nguyễn Trãi - Quan Hải", "Nguyen Trai: Watching the Sea", "阮廌", "Nguyễn Trãi", "後黎朝", "Nhà Hậu Lê",
     "天塹波濤何壯哉！當年鎖鑰重門開。地險防邊非不固，覆舟始信民如水。豪傑何曾負天下，英雄底事付塵埃？自古治平由德政，虛教關隘築仙台。",
     "神投海門天塹波濤何等壯美！當年胡朝鐵索鎖江終遭攻破。山川地險防邊固然險要，然覆舟之變始信孟子「民如水」之理。自古安邦全憑仁德政教，豈單憑關隘之險！",
     "Nature's moat and roaring waves how magnificent! Yet terrain defenses failed: overturned boats prove that people are like water. Enduring peace springs from virtuous governance alone, not merely stone fortress walls!",
     "阮廌汲取荀子「水能載舟亦能覆舟」思想，借歷史戰局論證「得民心者得天下、民為邦本」之至深政治哲學。",
     "【漢越音考證】塹 (Tiệm), 鑰 (Dược), 覆 (Phúc), 隘 (Ải), 築 (Trúc).",
     [{"viet": "Phúc chu thủy tín dân như thủy, tự cổ trị bình do đức chính.", "zh": "覆舟始信民如水，自古治平由德政。", "en": "Overturned boats prove that the people are like water; peace since ancient times comes from virtuous rule alone.", "hanViet": "Phúc chu thủy tín dân như thủy"}]),

    (37, "v6", "r37_05_ruanzhi_moxuan", "阮廌《暮春即事》", "Nguyễn Trãi - Mộ Xuân Tức Sự", "Nguyen Trai: Spring Impressions", "阮廌", "Nguyễn Trãi", "後黎朝", "Nhà Hậu Lê",
     "閒中盡日閉柴扉，靜裡春光自去飛。雨過綠陰鋪滿地，落花無數點客衣。",
     "悠閒之中整日緊閉柴門，在清靜寂寥中看春光自然逝去。春雨過後綠樹成蔭鋪滿庭院大地，無數落花隨風輕輕點綴在旅人衣襟之上。恬淡悠遠。",
     "In leisurely seclusion I close my wooden gate all day, watching spring light softly depart in quietude. Rain passed, green shadows blanket the ground; countless fallen petals lightly speckle the guest's robe.",
     "阮廌歸隱崑山（Côn Sơn）時期山水田園小詩，以極簡高雅筆觸寫出歷經風雲變幻後回歸自然之寧靜超脫心境。",
     "【漢越音考證】暮 (Mộ), 扉 (Phi), 陰 (Âm), 襟 (Khâm).",
     [{"viet": "Nhàn trung tận nhật bế sài phi, tĩnh lý xuân quang tự khứ phi. Vũ quá lục âm phô mãn địa, lạc hoa vô số điểm khách y.", "zh": "閒中盡日閉柴扉，靜裡春光自去飛。雨過綠陰鋪滿地，落花無數點客衣。", "en": "In quiet leisure I keep the gate closed all day; spring departs serenely in stillness. After rain green shade covers the earth, countless petals drift upon traveler's clothes.", "hanViet": "Mộ xuân tức sự"}]),

    # Round 38: 大越史記全書與通志
    (38, "v6", "r38_01_wushilian_daiviet_tu", "吳士連《大越史記全書·序》", "Ngô Sĩ Liên - Đại Việt Sử Ký Toàn Thư Tự", "Ngo Si Lien: Complete Annals of Great Viet Preface", "吳士連", "Ngô Sĩ Liên", "後黎朝", "Nhà Hậu Lê (1479)",
     "史者，所以記一國之治亂興衰，示萬世之規戒監戒者也。我大越開疆立極，自鴻龐始。歷丁、黎、李、陳以迄今日。天授英王，神開疆宇。命官修史，搜採往冊，刪繁補缺，編次年月，勒成全書。使善可為法，惡可為戒，百王儀表，昭然若日月之麗天。",
     "史書用以記載國家治亂興衰，示萬世法戒。吳士連奉黎聖宗之命修撰《大越史記全書》，上溯鴻龐氏雄王開國，詳述歷朝興廢善惡，昭如日月。",
     "History records the order, chaos, rise and fall of a nation to offer eternal lessons. From the founding of the Hong Bang dynasty through generations of emperors, recorded that virtue may be modeled and evil shunned!",
     "越南古代最重要之編年體官方通史巨著序文，奠定越南正統歷史體系與民族文化自豪感之基石。",
     "【漢越音考證】士 (Sĩ), 連 (Liên), 刪 (San), 勒 (Lặc), 昭 (Chiêu).",
     [{"viet": "Sử giả, sở dĩ ký nhất quốc chi trị loạn hưng suy, thị vạn thế chi quy giới giả dã.", "zh": "史者，所以記一國之治亂興衰，示萬世之規戒者也。", "en": "History serves to record the order, chaos, prosperity and ruin of a state, offering timeless guidance for myriad generations.", "hanViet": "Đại Việt sử ký toàn thư"}]),

    (38, "v6", "r38_02_wushilian_hungvuong", "吳士連《大越史記全書·雄王本紀史評》", "Ngô Sĩ Liên - Hùng Vương Bản Kỷ Sử Bình", "Ngo Si Lien: Commentary on King Hung", "吳士連", "Ngô Sĩ Liên", "後黎朝", "Nhà Hậu Lê",
     "史臣吳士連曰：水之有源，木之有本。我越自鴻龐氏涇陽王、貉龍君娶嫗姬生百卵，化為百男，長者立為雄王，國號文郎。傳十八世，皆號雄王。風俗淳厚，結繩而治。民知孝悌，土產豐饒。此我越建國之始也。後世子孫，當念祖宗創業之艱難，保我山河！",
     "吳士連史評溯源越南始祖：水有源木有本，貉龍君與嫗姬生百男化為百越，長者立為文郎國雄王，傳十八代。民風淳樸創業艱難，子孫當永懷祖德保衛疆土。",
     "Rivers have sources, trees have roots. From Lac Long Quan and Au Co bearing a hundred eggs, Hung King founded Van Lang. Descendants must forever honor ancestral toil!",
     "越南民族「龍子仙孫（Con Rồng Cháu Tiên）」傳說之權威正史記載，為全體越南人民共同認同之民族始祖根源。",
     "【漢越音考證】雄 (Hùng), 涇 (Kinh), 貉 (Lạc), 嫗 (Ẩu), 姬 (Cơ), 淳 (Thuần).",
     [{"viet": "Thủy chi hữu nguyên, mộc chi hữu bản. Con Rồng Cháu Tiên, thiên cổ tương truyền.", "zh": "水之有源，木之有本。龍子仙孫，千古傳承。", "en": "Water has its spring, trees have their roots. Children of the Dragon and Immortal, remembered across ten thousand years.", "hanViet": "Thủy chi hữu nguyên mộc chi hữu bản"}]),

    (38, "v6", "r38_03_liguidun_kienvantieuluc", "黎貴惇《見聞小錄·自序》", "Lê Quý Đôn - Kiến Văn Tiểu Lục Tự", "Le Quy Don: Little Records of Things Seen and Heard", "黎貴惇", "Lê Quý Đôn", "後黎朝", "Nhà Hậu Lê (1777)",
     "天下事，非目見耳聞、博考深究，不可妄論。僕生逢右文之世，喜讀古書，遍訪海內名山勝蹟，考訂山川地理、人物風俗、典章制度。著《見聞小錄》，分為風俗、山川、典禮、文章數門。博採眾長，去偽存真。願與海內好古之士共考之。",
     "越南十八世紀百科全書大儒黎貴惇自序：強調實事求是格物致知，遍訪山川考訂典章制度、歷史人物與文獻，去偽存真成《見聞小錄》。",
     "Matters of the world cannot be judged without eyewitness investigation and profound research. I roamed across the realm compiling geography, rites and literature to preserve truth!",
     "黎貴惇考據學與百科全書式學術巨著，代表古代越南漢學與實證考據之最高學術水平。",
     "【漢越音考證】貴 (Quý), 惇 (Đôn), 錄 (Lục), 訂 (Đính), 偽 (Ngụy).",
     [{"viet": "Thiên hạ sự, phi mục kiến nhĩ văn, bác khảo thâm cứu, bất khả vọng luận.", "zh": "天下事，非目見耳聞、博考深究，不可妄論。", "en": "Affairs under Heaven cannot be recklessly discussed without personal observation, broad verification, and profound research.", "hanViet": "Kiến văn tiểu lục"}]),

    (38, "v6", "r38_04_liguidun_phubientapluc", "黎貴惇《撫邊雜錄》", "Lê Quý Đôn - Phủ Biên Tạp Lục", "Le Quy Don: Miscellaneous Records of Pacified Frontiers", "黎貴惇", "Lê Quý Đôn", "後黎朝", "Nhà Hậu Lê (1776)",
     "順化、廣南之地，山川盤結，地沃物豐。黃沙島（Quần đảo Hoàng Sa）、長沙島（Quần đảo Trường Sa）在廣義外海，產海參、玳瑁、燕窩、螺鈿。朝廷歲遣黃沙隊乘船出海，採收物產，立界巡防。明載版圖，實我海疆之門戶也。",
     "黎貴惇奉命治理順化廣南，詳細記錄地理物產。明確記載大越朝廷設立「黃沙隊」定期乘船巡視西沙群島（黃沙）與南沙群島（長沙）採捕物產立界巡防之確鑿歷史事實。",
     "Records of the Southern frontiers: detailing historical sovereignty and expeditions of the Hoang Sa flotilla patrolling maritime islands and resources since ancient times.",
     "越南對南海諸島（黃沙、長沙群島）行使主權之最重要古代官修文獻證據，具極高歷史文獻價值。",
     "【漢越音考證】撫 (Phủ), 邊 (Biên), 玳 (Đại), 瑁 (Mạo), 螺 (Loa), 鈿 (Điền).",
     [{"viet": "Hoàng Sa đảo, Trường Sa đảo tại ngoại hải, minh tái bản đồ, hải cương môn hộ.", "zh": "黃沙島、長沙島在外海，明載版圖，實我海疆門戶。", "en": "The Hoang Sa and Truong Sa islands lie in outer seas, clearly registered in our maps as guardian gates to our maritime frontiers.", "hanViet": "Phủ biên tạp lục"}]),

    (38, "v6", "r38_05_panqingjian_suxikyhanh", "潘清簡《使西紀行》", "Phan Thanh Giản - Sứ Tây Kỷ Hành", "Phan Thanh Gian: Journal of Western Embassy", "潘清簡", "Phan Thanh Giản", "阮朝", "Nhà Nguyễn (1863)",
     "癸亥歲，余奉嗣德帝命，出使法蘭西。航渡重洋，見西人輪船鐵路、電報火器之精，宮室崇隆，科學昌明，真嘆未曾睹。歸奏朝廷曰：『西人機巧百出，不可敵以虛憍。當變法開埠，廣興格致之學，培育人才，方可立足於天下！』",
     "阮朝大臣潘清簡率團出使法國巴黎。目睹西方蒸氣火車、電報、輪船工業文明之先進，大受震動。歸國力勸變法圖強學習西方科學技術，啟迪近代化開端。",
     "Embassy to France: Observing steam railways, telegraphs, and advanced machinery. We must reform education, study natural sciences, and innovate to stand proud in the modern world!",
     "越南近代第一部走向西方之出使日記，開啟十九世紀越南有識之士放眼看世界、主張維新變法之先河。",
     "【漢越音考證】簡 (Giản), 嗣 (Tự), 埠 (Phụ), 巧 (Xảo), 憍 (Kiêu).",
     [{"viet": "Tây nhân cơ xảo bách xuất, đương biến pháp khai phụ, quảng hưng cách trí chi học.", "zh": "西人機巧百出，當變法開埠，廣興格致之學。", "en": "Western technological marvels abound; we must reform laws, open ports, and widely foster natural sciences and engineering.", "hanViet": "Sứ Tây kỷ hành"}])
]

# Add rounds 39-42
vol6_items.extend([
    # Round 39: 金雲翹傳
    (39, "v6", "r39_01_ruanyou_truyenkieu_1", "阮攸《金雲翹傳 (漢越對讀·開篇)》", "Nguyễn Du - Truyện Kiều (Khai Thiên)", "Nguyen Du: The Tale of Kieu - Opening", "阮攸", "Nguyễn Du", "阮朝", "Nhà Nguyễn (1820)",
     "Trăm năm trong cõi người ta, chữ tài chữ mệnh khéo là ghét nhau. Trải qua một cuộc bể dâu, những điều trông thấy mà đau đớn lòng. Lạ gì bỉ sắc tư phong, trời xanh quen thói má hồng đánh ghen. (百年人事，才命相妒。滄海桑田，觸目酸心。造物忌才，紅顏多薄！)",
     "百年人生在人世間，才華與命運往往互相嫉妒排擠。歷經世事滄海桑田之變幻，親眼所見之事令人痛徹心扉。造物主總是剝奪福祿，青天慣於嫉妒紅顏佳人！",
     "A hundred years in the realm of mortal men: talent and destiny ever clash in jealousy. Having lived through vast sea-changes of mulberry fields, the sights one witnesses break the tender heart!",
     "越南文學第一國寶巨著（Đại thi phẩm kiệt tác），阮攸以六八體喃字詩將才命相妒之悲劇宿命與至高人道主義同情抒寫成東亞文學豐碑。",
     "【漢越音考證】攸 (Du), 翹 (Kiều), 桑 (Tang), 滄 (Thương), 顏 (Nhan), 妒 (Đố).",
     [{"viet": "Trăm năm trong cõi người ta, chữ tài chữ mệnh khéo là ghét nhau. Trải qua một cuộc bể dâu, những điều trông thấy mà đau đớn lòng.", "zh": "百年人事在世間，才命由來相嫉妒。歷盡滄海變桑田，觸目所見皆酸辛。", "en": "A hundred years within this mortal realm: talent and fate are ever at strife. Having lived through great upheavals, what meets the eye wrings the heart.", "hanViet": "Bách niên tài mệnh tương đố"}]),

    (39, "v6", "r39_02_ruanyou_truyenkieu_2", "阮攸《金雲翹傳·金重相會》", "Nguyễn Du - Truyện Kiều - Kim Trọng Tương Ngộ", "Nguyen Du: The Tale of Kieu - Meeting Kim Trong", "阮攸", "Nguyễn Du", "阮朝", "Nhà Nguyễn",
     "Người quốc sắc, kẻ thiên tài, tình trong như đã, mặt ngoài còn e. Chập chờn lau lách bóng trăng, nhác trông dường thấy một chàng Kim sinh. Văn chương nết đất phong tư tài bộ, phong lưu rất mực, hào hoa hơn người. (國色天姿，相逢脈脈。風流金生，才貌無雙。)",
     "清明時節翠翹與風流才子金重相遇於夕陽綠柳之下。國色配天姿，脈脈含情一見鍾情，寫盡青年男女純真愛戀之萌發心動。",
     "A maiden of national beauty meets a youth of heavenly genius; affection blooms within while bashful on the outside. Kim Trong, accomplished in letters and peerless in noble charm!",
     "《金雲翹傳》最美愛情邂逅名段，六八字句音韻悠揚如天籟，展現封建束縛下對自由美好愛情之勇敢追求。",
     "【漢越音考證】色 (Sắc), 遇 (Ngộ), 脈 (Mạch), 姿 (Tư), 秀 (Tú).",
     [{"viet": "Người quốc sắc, kẻ thiên tài, tình trong như đã, mặt ngoài còn e.", "zh": "國色天香配奇才，情意暗生面含羞。", "en": "A peerless beauty and a genius of heaven; love blossomed within while modesty lingered without.", "hanViet": "Quốc sắc thiên tài"}]),

    (39, "v6", "r39_03_ruanyou_truyenkieu_3", "阮攸《金雲翹傳·賣身救父》", "Nguyễn Du - Truyện Kiều - Mại Thân Cứu Phụ", "Nguyen Du: The Tale of Kieu - Sacrificing Herself", "阮攸", "Nguyễn Du", "阮朝", "Nhà Nguyễn",
     "Duyên hội ngộ dứt tơ đào, đền ơn sinh dưỡng quản bao thân tàn! Hạt mưa sa xuống giếng dầu, phận bèo trôi nổi biết đâu bến bờ. Quyết liều một mảnh thân hoa, chuộc cha thoát khỏi vòng oan ngục tù. (斬斷情絲，賣身贖父。微軀委塵，至孝感天。)",
     "王家突遭橫禍父弟陷冤獄。王翠翹毅然斬斷與金重海誓山盟，賣身換取三百兩銀子救父出獄，開啟十五年風塵流離之悲壯苦難歷程。",
     "Severing tender love ribbons to repay parents' nurturing grace! Like a raindrop falling into a deep well, Kieu sacrificed her blossoming youth to redeem her father from prison.",
     "翠翹「犧牲自我成全大孝」之高尚人格昇華，揭露黑暗吏治對善良百姓家庭之摧毀，至孝至悲動人心魄。",
     "【漢越音考證】恩 (Ơn / Ân), 贖 (Thục), 獄 (Ngục), 孝 (Hiếu), 囚 (Tù).",
     [{"viet": "Quyết liều một mảnh thân hoa, chuộc cha thoát khỏi vòng oan ngục tù.", "zh": "決然捨棄如花身，贖父脫離冤獄苦。", "en": "Resolutely sacrificing her flower-like youth, to redeem her father from unjust prison chains.", "hanViet": "Mại thân cứu phụ"}]),

    (39, "v6", "r39_04_ruanyou_doctieuthanh", "阮攸《讀小青記》", "Nguyễn Du - Độc Tiểu Thanh Ký", "Nguyen Du: Reading the Story of Xiaoqing", "阮攸", "Nguyễn Du", "阮朝", "Nhà Nguyễn",
     "西湖花草盡荒蕪，獨弔殘編一紙書。脂粉有神憐死後，文章無命受公欺。古今恨事難窮問，風運奇冤豈自居！不知三百餘年後，天下何人泣阮攸？",
     "杭州西湖花草已荒蕪，獨自憑弔小青焚餘詩卷。脂粉通神死後猶令人憐惜，才情文章命薄受盡折磨。古今多少傷心恨事難以問天！不知三百年之後，天下間還有誰會為我阮攸落下一滴傷心之淚？",
     "West Lake's blooms and grass have turned to wild waste; alone I mourn over the surviving charred pages. In three hundred years from now, who under Heaven will weep for Nguyen Du?",
     "阮攸出使中國時所作漢詩絕唱，「不知三百餘年後，天下何人泣阮攸」將自身坎坷命運與千古才人薄命相通，哀感頑豔千古同悲。",
     "【漢越音考證】青 (Thanh), 弔 (Điếu), 脂 (Chi), 粉 (Phấn), 泣 (Khấp).",
     [{"viet": "Bất tri tam bách dư niên hậu, thiên hạ hà nhân khấp Nguyễn Du?", "zh": "不知三百餘年後，天下何人泣阮攸？", "en": "I know not three hundred years from now, who in the world will weep for Nguyen Du?", "hanViet": "Bất tri tam bách dư niên hậu thiên hạ hà nhân khấp Nguyễn Du"}]),

    (39, "v6", "r39_05_ruanyou_thailiendao", "阮攸《採蓮謠》", "Nguyễn Du - Thải Liên Dao", "Nguyen Du: Lotus Gathering Ballad", "阮攸", "Nguyễn Du", "阮朝", "Nhà Nguyễn",
     "採蓮曲，採蓮舟，採得荷花香滿流。共乘蘭橈採明月，採蓮女唱水悠悠。花開嬌豔迎朝日，葉落殘香引碧秋。採蓮归來薄暮後，相看笑指水雲浮。",
     "採蓮歌聲採蓮船，採得滿江荷花香氣流淌。姑娘們共乘蘭舟採擷明月倒影，採蓮女歌聲宛轉隨水流悠長。晚歸相視而笑，清麗宛轉如江南水鄉神品。",
     "Gathering lotus flowers in wooden boats, fragrance fills the stream. Gathering maidens sing melodies flowing like clear water under sunset skies.",
     "阮攸抒情漢詩名篇，音律明麗清新，展現其詩才兼具漢詩溫厚風雅與越南水鄉生活明麗之美。",
     "【漢越音考證】採 (Thải), 蓮 (Liên), 謠 (Dao), 橈 (Nhiêu), 嬌 (Kiều).",
     [{"viet": "Thải liên khúc, thải liên chu, thải đắc hà hoa hương mãn lưu.", "zh": "採蓮曲，採蓮舟，採得荷花香滿流。", "en": "Lotus gathering ballad, lotus gathering boats; gathering lotus flowers filling the streams with fragrance.", "hanViet": "Thải liên dao"}]),

    # Round 40: 征婦吟曲與宮怨
    (40, "v6", "r40_01_dengchenkun_chinhphu_1", "鄧陳琨／段氏點《征婦吟曲 (漢喃對讀·開篇)》", "Đặng Trần Côn / Đoàn Thị Điểm - Chinh Phụ Ngâm (Khai Thiên)", "The Lament of the Soldier's Wife: Opening", "鄧陳琨 / 段氏點", "Đặng Trần Côn / Đoàn Thị Điểm", "後黎朝", "Nhà Hậu Lê (1741)",
     "Thiên địa phong trần, hồng nhan đa truân. Du du bỉ thương hề thùy tạo nhân? Trống Trường Thành lung lay bóng nguyệt, khói Cam Tuyền mờ mịt thức mây. Chàng tuổi trẻ vốn dòng hào kiệt, xếp bút nghiên theo việc đao cung. (天地風塵，紅顏多難。悠悠蒼天，誰造成此劫！)",
     "天地間風塵滾滾烽煙四起，紅顏女子命運多災多難。悠悠蒼天啊究竟是誰造成這離亂殺伐！長城戰鼓震動夜月，年輕將士投筆從戎從軍遠征塞外。",
     "Heaven and Earth enveloped in dust and turmoil; the fair maiden endures manifold griefs! The warrior sets aside scholarly brushes to take up bow and spear for distant borders.",
     "鄧陳琨漢文原創、才女段氏點演繹為雙七六八體喃詩之經典長篇抒情名作，痛斥戰亂殘酷，呼喚和平與人間至情。",
     "【漢越音考證】琨 (Côn), 點 (Điểm), 征 (Chinh), 婦 (Phụ), 吟 (Ngâm), 塵 (Trần), 難 (Nan).",
     [{"viet": "Thiên địa phong trần, hồng nhan đa truân. Du du bỉ thương hề thùy tạo nhân?", "zh": "天地風塵，紅顏多難。悠悠彼蒼兮誰造因？", "en": "Heaven and Earth in wind and dust, fair maidens meet manifold sorrows. Oh vast blue Heaven, who caused this suffering?", "hanViet": "Thiên địa phong trần hồng nhan đa truân"}]),

    (40, "v6", "r40_02_dengchenkun_chinhphu_2", "鄧陳琨／段氏點《征婦吟曲·閨思離愁》", "Đặng Trần Côn / Đoàn Thị Điểm - Chinh Phụ Ngâm - Khuê Tứ", "The Lament of the Soldier's Wife: Longing", "鄧陳琨 / 段氏點", "Đặng Trần Côn / Đoàn Thị Điểm", "後黎朝", "Nhà Hậu Lê",
     "Dạo hiên vắng thầm gieo từng bước, ngồi rèm thưa rủ thác đòi phen. Ngoài rèm thước chẳng mách tin, trong rèm dường đã có đèn biết chăng? Đèn có biết dường bằng chẳng biết, lòng thiếp riêng bi thiết mà thôi! Buồn trông gió thổi hoa rơi, thương người muôn dặm phương trời gió sương. (獨倚危樓，望斷天涯。孤燈知我，思君淚流。)",
     "征婦獨行空廊步步沉重，掀簾望月不見歸鴻。孤燈伴我照殘影，內心無盡悲傷淒楚。遙望萬里邊塞風霜，思念遠征丈夫淚濕衣裳。",
     "Walking the deserted veranda with solitary steps, leaning by the curtain waiting in vain. Does the solitary lamp know my deep grief? Mourning for my beloved ten thousand miles away amidst wind and frost.",
     "細膩描摹古代婦女在戰亂年代之深閨幽怨與相思折磨，哀婉深沉情景交融。",
     "【漢越音考證】簾 (Liêm), 孤 (Cô), 燈 (Đăng), 霜 (Sương), 戚 (Thích).",
     [{"viet": "Đèn có biết dường bằng chẳng biết, lòng thiếp riêng bi thiết mà thôi!", "zh": "殘燈若知若不知，妾心獨自悲痛切！", "en": "Does the lamp know or know not? My heart alone suffers such acute sorrow!", "hanViet": "Chinh phụ khuê oán"}]),

    (40, "v6", "r40_03_ruanjiashao_cungoan", "阮嘉韶《宮怨吟曲》", "Nguyễn Gia Thiều - Cung Oán Ngâm Khúc", "Nguyen Gia Thieu: Laments of the Royal Palace Maid", "阮嘉韶", "Nguyễn Gia Thiều", "後黎朝", "Nhà Hậu Lê (1780)",
     "Trăm năm một giấc mộng dài, vinh hoa bọt nước mây trôi cuối trời. Cung sâu một khóa xuân tàn, phấn son nhạt nhẽo bóng trăng lạnh lùng. Ngẫm mình như chiếc lá rơi, bao nhiêu ân sủng một thời đã qua. (深宮幽閉，紅顏空老。萬種榮華，如水上漚。)",
     "百年人生如一場虛妄大夢，深宮幽閉青春葬送。恩寵過後冷落空房，昔日萬種風光如水面泡沫雲散煙消，發出深沉厭世哲思與悲憤控訴。",
     "A hundred years is but a long dream; royal favor and glory vanish like bubbles upon water. Locked in deep palace halls, youth fades into cold moonlit solitude.",
     "阮嘉韶雙七六八體哲理抒情名篇，批判封建帝王深宮摧殘女性青春，融道家虛無與佛家無常觀於深宮悲歌。",
     "【漢越音考證】韶 (Thiều), 怨 (Oán), 寵 (Sủng), 漚 (Âu), 鎖 (Tỏa).",
     [{"viet": "Trăm năm một giấc mộng dài, cung sâu một khóa xuân tàn lạnh lùng.", "zh": "百年猶如長夜夢，深宮一鎖暮春殘。", "en": "A hundred years is but a fleeting dream; locked in the deep palace, spring withers in cold despair.", "hanViet": "Cung oán ngâm khúc"}]),

    (40, "v6", "r40_04_huxunxiang_banhtroinuoc", "胡春香《詠餡湯圓 (浮萍餅)》", "Hồ Xuân Hương - Vịnh Bánh Trôi Nước", "Ho Xuan Huong: Floating Cake (Sweet Dumpling)", "胡春香", "Hồ Xuân Hương", "西山朝", "Nhà Tây Sơn (1800)",
     "Thân em vừa trắng lại vừa tròn, Bảy nổi ba chìm với nước non. Rắn nát mặc dầu tay kẻ nặn, Mà em vẫn giữ tấm lòng son. (身白體圓浮水面，七沉八浮任自然。硬軟全憑揉捏手，始終堅守赤丹心！)",
     "我的身子既潔白又圓潤，隨波逐流在江海中七沉三浮。任憑別人的手將我揉捏得堅硬或軟爛，我依然永遠堅守著內心那一顆熾熱赤誠的紅心！",
     "My body is both white and round, sinking and floating through seven trials and three depths. Hard or soft, molded by others' hands as it may be, I still preserve my loyal crimson heart!",
     "「喃字詩女王（Bà chúa thơ Nôm）」胡春香借詠物托志，以民間水圓（湯圓）象徵女性在封建男權壓迫下堅貞不屈之自主尊嚴與純真赤心。",
     "【漢越音考證】香 (Hương), 圓 (Viên), 浮 (Phù), 揉 (Nhu), 丹 (Đan).",
     [{"viet": "Thân em vừa trắng lại vừa tròn, Bảy nổi ba chìm với nước non. Rắn nát mặc dầu tay kẻ nặn, Mà em vẫn giữ tấm lòng son.", "zh": "身白體圓浮水面，七沉三浮任波瀾。硬軟全憑揉捏手，始終堅守赤丹心。", "en": "My body is pure white and round, sinking and rising across life's waves. Handled and shaped however hands may choose, I keep unbroken my true crimson heart.", "hanViet": "Thân em vừa trắng lại vừa tròn"}]),

    (40, "v6", "r40_05_huxunxiang_tutinh", "胡春香《自情三首·其二》", "Hồ Xuân Hương - Tự Tình Kỳ 2", "Ho Xuan Huong: Self-Confession II", "胡春香", "Hồ Xuân Hương", "西山朝", "Nhà Tây Sơn",
     "Đêm khuya văng vẳng trống canh dồn, Trơ cái hồng nhan với nước non. Chén rượu hương đưa say lại tỉnh, Vầng trăng bóng xế khuyết chưa tròn. Xiên ngang mặt đất rêu từng đám, Đâm toạc chân mây đá mấy hòn. Ngán nỗi xuân đi xuân lại lại, Mảnh tình san sẻ tí con con! (黑夜更鼓催人醒，孤身紅顏對江山。微醉轉醒月將落，破土苔青裂長空！)",
     "深夜更鼓催促響起，孤獨紅顏孑然面對山河。舉杯欲醉轉眼又醒，斜月將墜殘缺不圓。青苔斜斜刺破地面，巨石利刃直插雲空撕裂天際！韶華虛度，零碎情愛令人厭倦！",
     "Night drums echo through the dark; lonely beauty stands against vast hills. Wine cup sips bring temporary drunken haze only to wake. Moss slants across soil in defiance, rocks pierce clouds breaking the horizon!",
     "胡春香打破傳統閨怨之柔弱哀泣，以「斜穿地表、撕裂天際」之狂放奇崛意象，展現反抗封建妾侍制度之強大女性獨立意志。",
     "【漢越音考證】情 (Tình), 鼓 (Cổ), 苔 (Đài), 裂 (Liệt), 傲 (Ngạo).",
     [{"viet": "Xiên ngang mặt đất rêu từng đám, Đâm toạc chân mây đá mấy hòn.", "zh": "苔青斜穿破地面，怪石突刺裂長空。", "en": "Moss shoots sideways thrusting through soil, jagged rocks pierce and tear apart the sky's horizon.", "hanViet": "Tự tình kỳ nhị"}]),

    # Round 41: 近代抗法志士篇章
    (41, "v6", "r41_01_panpeizhu_haingoai", "潘佩珠《海外血書》", "Phan Bội Châu - Hải Ngoại Huyết Thư", "Phan Boi Chau: Letter Written in Tears of Blood", "潘佩珠", "Phan Bội Châu", "近代", "Cận Đại (1906)",
     "嗚呼同胞！亡國之慘，痛徹心髓。法人奴役，刮盡膏脂。士農工商，淪為牛馬。吾輩生於此土，豈可坐視祖宗基業毀於異族！發動東遊，留學自強。集天下之熱血，誓死驅逐強寇，光復我大越獨立之乾坤！",
     "潘佩珠東渡日本發表《海外血書》號召越南全體同胞：痛陳殖民亡國奴役之慘痛，發起「東遊運動（Phong trào Đông Du）」赴日求學自強，誓死光復祖國主權！",
     "Oh compatriots! The sorrow of national subjugation cuts to the marrow. Rise, study modern science abroad, rally all righteous blood to restore Vietnam's independence!",
     "二十世紀初越南民族民主革命第一篇動員檄文，熱血澎湃喚醒一代越南青年覺醒投身救國事業。",
     "【漢越音考證】佩 (Bội), 珠 (Châu), 髓 (Tủy), 奴 (Nô), 驅 (Khu), 復 (Phục).",
     [{"viet": "Hải ngoại huyết thư thức tỉnh đồng bào, thề phục giang sơn.", "zh": "海外血書喚醒同胞，誓死光復江山乾坤。", "en": "Letter in blood from overseas awakens compatriots, vowing to restore our ancestral homeland.", "hanViet": "Hải ngoại huyết thư"}]),

    (41, "v6", "r41_02_panpeizhu_xuatduong", "潘佩珠《拜別同胞出洋 (出洋留別)》", "Phan Bội Châu - Xuất Dương Lưu Biệt", "Phan Boi Chau: Farewell on Going Abroad", "潘佩珠", "Phan Bội Châu", "近代", "Cận Đại (1905)",
     "生為男子要稀奇，肯許乾坤自轉移？百年間在何人是，千載後誰知我為！江山已死身猶在，日月同懸骨未灰。願跨長風破東海，萬里波濤任我來！",
     "生為男兒當有非凡志氣，豈能任由乾坤乾枯沉淪！江山雖遭淪陷熱血猶存。願乘萬里長風橫渡東海狂濤，尋求救國救民真理！",
     "Born as a man, one must strive for the extraordinary! With homeland imperiled, how can we remain idle? I shall ride the mighty winds across the Eastern Sea!",
     "潘佩珠告別祖國赴日留別名詩，豪氣干雲，展現近代革命志士視死如歸、勇渡重洋之豪邁抱負。",
     "【漢越音考證】男 (Nam), 奇 (Kỳ), 轉 (Chuyển), 移 (Di), 灰 (Hôi), 跨 (Khóa).",
     [{"viet": "Sinh vi nam tử yếu hy kỳ, khẳng hứa càn khôn tự chuyển di?", "zh": "生為男子要稀奇，肯許乾坤自轉移？", "en": "Born as a man one must be extraordinary; how can we allow the universe to drift into ruin?", "hanViet": "Sinh vi nam tử yếu hy kỳ"}]),

    (41, "v6", "r41_03_panzhoutrinh_tinhquoc", "潘周楨《醒國民歌》", "Phan Châu Trinh - Tỉnh Quốc Dân Ca", "Phan Chau Trinh: Awakening Song for Citizens", "潘周楨", "Phan Châu Trinh", "近代", "Cận Đại (1907)",
     "開民智、振民氣、厚民生！不學新知，何以圖存？興辦新學，提倡工商，破除愚昧陋習。同心協力，自立自強，方為救國之真途！",
     "維新派領袖潘周楨力倡「開民智、振民氣、厚民生」三大救國綱領。主張普及現代教育興辦工商實業，打破迷信求自立自強。",
     "Open the people's intellect, revive their spirit, and enrich their livelihood! Universal education and industrial modernization are the true path to national salvation.",
     "越南近代維新變法啟蒙運動最高宣言，深刻推動越南近代文字改革（國語字推廣）與現代教育啟蒙。",
     "【漢越音考證】楨 (Trinh), 醒 (Tỉnh), 智 (Trí), 振 (Chấn), 陋 (Lậu).",
     [{"viet": "Khai dân trí, chấn dân khí, hậu dân sinh.", "zh": "開民智、振民氣、厚民生。", "en": "Open people's intellect, revitalize their spirit, and enrich their livelihood.", "hanViet": "Khai dân trí chấn dân khí hậu dân sinh"}]),

    (41, "v6", "r41_04_ruantingchieu_cangiuoc", "阮廷炤《祭芹玉士民文》", "Nguyễn Đình Chiểu - Văn Tế Nghĩa Sĩ Cần Giuộc", "Nguyen Dinh Chieu: Funeral Oration for the Fallen Heroes of Can Giuoc", "阮廷炤", "Nguyễn Đình Chiểu", "近代", "Cận Đại (1861)",
     "Súng giặc đất rền, lòng dân trời tỏ! Mười tám ban võ nghệ nào đợi tập rèn, chín chục trận binh thư đâu cần đọc kỹ. Áo vải thô sơ, gậy tầm vông đâm ngang họng giặc; lòng yêu nước sáng ngời soi rực ngàn thu. Sống đánh giặc, thác cũng đánh giặc, muôn thuở linh hồn theo ngọn cờ nghĩa! (銃聲震地，民心昭天。布衣竹杖，血戰衛國。生為義士，死為忠魂！)",
     "盲人愛國詩人阮廷炤祭悼芹玉農民義勇軍：以布衣農民之軀手持竹竿農具抗擊法軍洋槍大砲，生死為國捐軀。雖死猶生名垂青史！",
     "Farmer heroes wielding plain bamboo spears against Western cannons! Living they fought the invader, dying their heroic spirits rally under the righteous banner forever!",
     "越南南部第一部人民抗法史詩誄文，熱情歌頌普通農民自發保家衛國之英雄形象，感人至深震撼千古。",
     "【漢越音考證】炤 (Chiểu), 芹 (Cần), 玉 (Giuộc / Ngọc), 旗 (Kỳ), 靈 (Linh).",
     [{"viet": "Sống đánh giặc, thác cũng đánh giặc, muôn thuở linh hồn theo ngọn cờ nghĩa!", "zh": "生則殺敵，死亦殺敵，千秋英靈永隨義旗！", "en": "Living they fought invaders, dying their spirits follow the righteous banner for ten thousand ages!", "hanViet": "Văn tế nghĩa sĩ Cần Giuộc"}]),

    (41, "v6", "r41_05_ruanshangxian_camsu", "阮尚賢《感事》", "Nguyễn Thượng Hiền - Cảm Sự", "Nguyen Thuong Hien: Reflections on Current Affairs", "阮尚賢", "Nguyễn Thượng Hiền", "近代", "Cận Đại",
     "投筆從戎萬里行，中原回首動深情。英雄自古多磨難，誓挽天河洗甲兵！",
     "投筆從戎跋涉萬里，回望中原故土感慨深情。自古英雄皆經磨難，誓挽銀河天水洗淨戰甲兵器重迎天下太平！",
     "Laying down the brush to march ten thousand miles; heroes since ancient times meet hardships, vowing to draw the Heavenly River to wash all battle armor clean!",
     "阮朝進士阮尚賢流亡中國參與革命之感事詩，展現越中革命志士同盟抗殖民之深厚友誼與堅定信念。",
     "【漢越音考證】賢 (Hiền), 戎 (Nhung), 甲 (Giáp), 兵 (Binh).",
     [{"viet": "Đầu bút tòng nhung vạn lý hành, anh hùng tự cổ đa ma nan.", "zh": "投筆從戎萬里行，英雄自古多磨難。", "en": "Dropping the brush to march on ten thousand miles; heroes since antiquity have endured great trials.", "hanViet": "Cảm sự"}]),

    # Round 42: 胡志明獄中日記與現代漢詩
    (42, "v6", "r42_01_huzhiming_nhatky_1", "胡志明《獄中日記·卷首》", "Hồ Chí Minh - Nhật Ký Trong Tù (Thủ Thiên)", "Ho Chi Minh: Prison Diary - Opening", "胡志明", "Hồ Chí Minh", "現代", "Hiện Đại (1942)",
     "身體在獄中，精神在獄外。欲成大事業，精神更要大！",
     "肉體雖被囚禁在牢獄之中，革命精神卻早已翱翔在牢獄之外。若要成就解放民族之偉大事業，精神境界必須更加宏大堅定！",
     "The body is in prison, but the spirit soars outside. To achieve a grand enterprise, the spirit must be boundless!",
     "《獄中日記》（Nhật Ký Trong Tù）開宗明義首詩，展現無產階級革命家身處囹圄樂觀豁達、傲視苦難之崇高革命浪漫主義。",
     "【漢越音考證】胡 (Hồ), 志 (Chí), 明 (Minh), 獄 (Ngục), 軀 (Khu), 業 (Nghiệp).",
     [{"viet": "Thân thể tại ngục trung, tinh thần tại ngục ngoại. Dục thành đại sự nghiệp, tinh thần cánh yếu đại!", "zh": "身體在獄中，精神在獄外。欲成大事業，精神更要大！", "en": "The physical body is in prison, but the spirit is free outside. To accomplish great deeds, one's spirit must be immensely great!", "hanViet": "Nhật ký trong tù"}]),

    (42, "v6", "r42_02_huzhiming_taotinh", "胡志明《獄中日記·早晴》", "Hồ Chí Minh - Nhật Ký Trong Tù - Tảo Tình", "Ho Chi Minh: Prison Diary - Clear Morning", "胡志明", "Hồ Chí Minh", "現代", "Hiện Đại (1942)",
     "日出滿天雲霧散，光明普照大人間。大千生物同歡樂，萬物逢春盡展顏！",
     "紅日升起滿天陰霾雲霧自然消散，溫暖光明普照廣大人間天地。大千世界生靈一同歡欣喜悅，萬物逢春皆展露歡顏！",
     "The sun rises, dispersing all clouds and mist; bright light illuminates the vast world of men. Myriad living creatures rejoice together, greeting spring with joyful smiles!",
     "借牢房清晨日出陰雲散盡之景，象徵光明必將戰勝黑暗、革命必將迎來全面勝利之堅定樂觀信念。",
     "【漢越音考證】晴 (Tình), 霧 (Vụ), 普 (Phổ), 顏 (Nhan).",
     [{"viet": "Nhật xuất mãn thiên vân vụ tán, quang minh phổ chiếu đại nhân gian.", "zh": "日出滿天雲霧散，光明普照大人間。", "en": "The sun rises, all mist and clouds across the sky disperse; radiant light illuminates the vast world of men.", "hanViet": "Tảo tình"}]),

    (42, "v6", "r42_03_huzhiming_thungme", "胡志明《獄中日記·聽舂米聲》", "Hồ Chí Minh - Nhật Ký Trong Tù - Thính Thung Mễ Thanh", "Ho Chi Minh: Prison Diary - Sound of Mortar", "胡志明", "Hồ Chí Minh", "現代", "Hiện Đại (1942)",
     "米舂過後白如玉，人受磨礪自成金。試看古來成大器，誰非歷盡苦中尋！",
     "稻穀經過千百次舂打之後自然潔白如玉，人經過千錘百鍊之磨難砥礪自然鍛造成金。試看古往今來成大器之偉人，哪一個不是歷盡千辛萬苦成就事業！",
     "Rice grains turned pure white as jade after being pounded in the mortar; man forged through trials turns into pure gold. Who achieved great destiny without traversing arduous hardships!",
     "借監獄舂米聲提煉人生哲理，「米舂過後白如玉，人受磨礪自成金」成為勉勵青年克服逆境奮發圖強之名句。",
     "【漢越音考證】舂 (Thung), 礪 (Lệ), 磨 (Ma), 尋 (Tầm).",
     [{"viet": "Mễ thung quá hậu bạch như ngọc, nhân thụ ma lệ tự thành kim.", "zh": "米舂過後白如玉，人受磨礪自成金。", "en": "Rice pounded in the mortar emerges white as jade; man tempered through hardships turns into pure gold.", "hanViet": "Thính thung mễ thanh"}]),

    (42, "v6", "r42_04_huzhiming_ngamtrang", "胡志明《獄中日記·看月 (望月)》", "Hồ Chí Minh - Nhật Ký Trong Tù - Ngắm Trăng", "Ho Chi Minh: Prison Diary - Viewing the Moon", "胡志明", "Hồ Chí Minh", "現代", "Hiện Đại (1942)",
     "獄中無酒亦無花，對此良宵奈若何？人向窗前看明月，月從窗隙看詩家。",
     "鐵窗牢獄中既沒有美酒也沒有鮮花，面對如此迷人月色良宵該如何慶賀？詩人向著鐵窗前凝望天上一輪明月，明月也從鐵窗縫隙間默默探看著窗內詩人！",
     "In prison there is neither wine nor flowers; facing this lovely night what can one do? The poet gazes at the bright moon through iron bars; the moon peers through the bars to gaze upon the poet.",
     "胡志明流傳最廣之漢詩名篇，在極端惡劣囚禁環境下與明月相視相惜，展現超脫物外之藝術情操與崇高精神境界。",
     "【漢越音考證】宵 (Tiêu), 隙 (Khích), 詩 (Thi), 家 (Gia).",
     [{"viet": "Ngục trung vô tửu diệc vô hoa, đối thử lương tiêu nại nhược hà? Nhân hướng song tiền khán minh nguyệt, nguyệt tòng song khích khán thi gia.", "zh": "獄中無酒亦無花，對此良宵奈若何？人向窗前看明月，月從窗隙看詩家。", "en": "In prison there is neither wine nor flowers; facing this lovely night what is one to do? The man looks out the window to view the bright moon; the moon looks through window bars to behold the poet.", "hanViet": "Ngắm trăng"}]),

    (42, "v6", "r42_05_huzhiming_nguyentieu", "胡志明《元宵》", "Hồ Chí Minh - Nguyên Tiêu", "Ho Chi Minh: Lantern Festival Night", "胡志明", "Hồ Chí Minh", "現代", "Hiện Đại (1948)",
     "今夕元宵月正圓，春江春水接春天。煙波深處商軍事，夜半歸來月滿船。",
     "今夜元宵佳節明月正圓，春江春水浩浩蕩蕩與春天相連。在越北叢林煙波深處秘密商討抗法軍事大計，夜半泛舟凱旋歸來，滿船沐浴在皎潔明月清輝之中！",
     "Tonight on Lantern Festival the moon is round; spring river waters merge into spring skies. In misty depths discussing military affairs, returning at midnight with the boat full of moonlight!",
     "胡志明在越北抗戰根據地所作經典漢詩，融軍事決策之嚴肅與月滿歸舟之詩情於一體，意境優美雄健。",
     "【漢越音考證】元 (Nguyên), 宵 (Tiêu), 舟 (Chu), 煙 (Yên).",
     [{"viet": "Kim tịch nguyên tiêu nguyệt chính viên, xuân giang xuân thủy tiếp xuân thiên. Yên ba thâm xứ thương quân sự, dạ bán quy lai nguyệt mãn thuyền.", "zh": "今夕元宵月正圓，春江春水接春天。煙波深處商軍事，夜半歸來月滿船。", "en": "Tonight is Lantern Festival and the moon is round; spring river waters join spring skies. Deep in mist discussing army plans, returning at midnight with the boat full of moonlight.", "hanViet": "Nguyên tiêu"}])
])

print(f"Volume 6 items ready: {len(vol6_items)}")
