# -*- coding: utf-8 -*-
"""Volume 3: 唐宋八大家與盛世文章 (Rounds 15-21, 35 works)"""

vol3_items = [
    # Round 15: 韓愈古文名篇
    (15, "v3", "r15_01_hanyu_shishuo", "韓愈《師說》", "Hàn Dũ - Sư Thuyết", "Han Yu: On Teachers", "韓愈", "Hàn Dũ", "唐代", "Đường",
     "古之學者必有師。師者，所以傳道受業解惑也。人非生而知之者，孰能無惑？惑而不從師，其為惑也，終不解矣。生乎吾前，其聞道也固先乎吾，吾從而師之；生乎吾後，其聞道也亦先乎吾，吾從而師之。吾師道也，夫庸知其年之先後生於吾乎？是故無貴無賤，無長無少，道之所存，師之所存也。聖人無常師。弟子不必不如師，師不必賢於弟子，聞道有先後，術業有專攻，如是而已。",
     "古代求學之人必定有老師。老師是傳授道理、講授學業、解答疑難困惑的人。人不是生來就具備知識，誰能沒有困惑？聖人無固定老師，弟子未必不如老師，老師未必賢於弟子，只因領悟道理有先後、學術專業各有專精罷了。",
     "Ancient scholars always had teachers. A teacher transmits the Way, teaches skills, and resolves perplexities. Disciples are not necessarily inferior to teachers; teachers are not necessarily wiser than disciples.",
     "韓愈古文運動代表作，抨擊當時士大夫階層恥於從師陋習，提出「道之所存，師之所存」與「教學相長、術業專攻」之偉大教育真理。",
     "【漢越音考證】愈 (Dũ), 師 (Sư), 說 (Thuyết), 惑 (Hoặc), 賤 (Tiện), 聖 (Thánh), 專 (Chuyên), 攻 (Công).",
     [{"viet": "Cổ chi học giả tất hữu sư. Sư giả, sở dĩ truyền đạo thụ nghiệp giải hoặc dã.", "zh": "古之學者必有師。師者，所以傳道受業解惑也。", "en": "Ancient scholars always had teachers. A teacher transmits the Way, teaches skills, and resolves perplexities.", "hanViet": "Cổ chi học giả tất hữu sư"}]),

    (15, "v3", "r15_02_hanyu_jinxuejie", "韓愈《進學解》", "Hàn Dũ - Tiến Học Giải", "Han Yu: Explaining Advancement in Learning", "韓愈", "Hàn Dũ", "唐代", "Đường",
     "國子先生晨入太學，召諸生立館下，誨之曰：「業精於勤，荒於嬉；行成於思，毀於隨。方今聖賢相逢，治具畢張。拔淹通之德，蓄長育之材。諸生業患不能精，無患有司之不明；行患不能成，無患有司之不公。」",
     "韓愈訓勉太學生：學業的精進在於勤奮，荒廢在於嬉鬧懈怠；德行的成就源於獨立深思，毀滅在於盲目隨波逐流。只患自己學業不精、品行不成，勿患他人不識人才。",
     "Mastery of one's work comes from diligence and is ruined by frivolous play; moral character is formed by deep reflection and destroyed by thoughtless conformity.",
     "名句「業精於勤荒於嬉，行成於思毀於隨」為東亞士子千百年來砥礪勤學修身之至理名言。",
     "【漢越音考證】進 (Tiến), 誨 (Hối), 勤 (Cần), 嬉 (Hi), 毀 (Hủy), 隨 (Tùy).",
     [{"viet": "Nghiệp tinh ư cần, hoang ư hi; hành thành ư tư, hủy ư tùy.", "zh": "業精於勤，荒於嬉；行成於思，毀於隨。", "en": "Excellence in learning comes from diligence and is ruined by play; virtue is shaped by thought and destroyed by blind following.", "hanViet": "Nghiệp tinh ư cần hoang ư hi"}]),

    (15, "v3", "r15_03_hanyu_jishierlang", "韓愈《祭十二郎文》", "Hàn Dũ - Tế Thập Nhị Lang Văn", "Han Yu: Elegy for My Nephew Shierlang", "韓愈", "Hàn Dũ", "唐代", "Đường",
     "年、月、日，季父愈聞汝十二郎之喪，告汝十二郎之靈：吾少孤，及長，不省所怙，惟兄嫂是依。中年兄歿，吾與汝俱幼，從嫂歸葬河陽。吾與汝相從也，未嘗一日相離也。吾年未四十，而視茫茫，而髮蒼蒼，而齒牙動搖。孰謂汝志森而體堅，乃死我先！嗚呼！言有窮而情不可終，汝其知也邪？其不知也邪？嗚呼哀哉！尚饗！",
     "韓愈痛悼早逝之姪兒十二郎。自幼相依為命，痛惜生死永訣白髮人送黑髮人。情真意切催人淚下，被譽為「祭文之冠」。",
     "I write in anguish for my beloved nephew. We grew together since youth as orphans. Words have an end but sorrow knows no finish!",
     "與袁枚《祭妹文》、蘇軾《祭歐陽文忠公文》並稱古代三大哀感頑豔祭文，真情迸發字字血淚。",
     "【漢越音考證】祭 (Tế), 郎 (Lang), 喪 (Tang), 怙 (Hỗ), 歿 (Một), 茫 (Mang), 饗 (Hưởng).",
     [{"viet": "Ngôn hữu cùng nhi tình bất khả chung, nhữ kỳ tri dã tà? Kỳ bất tri dã tà? Ô hô ai tai!", "zh": "言有窮而情不可終，汝其知也邪？其不知也邪？嗚呼哀哉！", "en": "Words reach an end, but grief knows no close. Alas, what boundless sorrow!", "hanViet": "Ngôn hữu cùng nhi tình bất khả chung"}]),

    (15, "v3", "r15_04_hanyu_yuandao", "韓愈《原道》", "Hàn Dũ - Nguyên Đạo", "Han Yu: Tracing the Way to Its Source", "韓愈", "Hàn Dũ", "唐代", "Đường",
     "博愛之謂仁，行而宜之之謂義，由是而之焉之謂道，足乎己無待於外之謂德。仁與義為定名，道與德為虛位。故道有君子小人，而德有凶有吉。老子之小仁義，非毀仁義也，其見者小也。孔子傳道於孟軻，軻之死，不得其傳焉。荀與揚也，擇焉而不精，語焉而不詳。軻之死，其道遂隱。僕雖不敏，願發揚之！",
     "韓愈系統界定儒家核心範疇：博愛稱為仁，行為適當稱為義。確立堯舜禹湯文武周公孔孟道統傳承，發願力挽儒學狂瀾抗擊佛老迷信。",
     "Universal benevolence is Ren; acting fittingly is Yi. The True Way of the sages must be revived to bring light to the world!",
     "韓愈首倡儒家「道統論」，為宋代理學（程朱理學）之先聲，奠定中世紀東亞儒家文化復興之理論基石。",
     "【漢越音考證】原 (Nguyên), 博 (Bác), 仁 (Nhân), 義 (Nghĩa), 德 (Đức), 軻 (Kha), 統 (Thống).",
     [{"viet": "Bác ái chi vị nhân, hành nhi nghi chi chi vị nghĩa.", "zh": "博愛之謂仁，行而宜之之謂義。", "en": "Universal love is called benevolence; acting appropriately is called righteousness.", "hanViet": "Bác ái chi vị nhân"}]),

    (15, "v3", "r15_05_hanyu_mashuo", "韓愈《雜說四·馬說》", "Hàn Dũ - Mã Thuyết", "Han Yu: On Horses", "韓愈", "Hàn Dũ", "唐代", "Đường",
     "世有伯樂，然後有千里馬。千里馬常有，而伯樂不常有。故雖有名馬，祇辱於奴隸人之手，駢死於槽櫪之間，不以千里稱也。馬之千里者，一食或盡粟一石。食馬者不知其能千里而食也。策之不以其道，食之不能盡其材，鳴之而不能通其意，執策而臨之，曰：「天下無馬！」嗚呼！其真無馬邪？其真不知馬也！",
     "世間先有識馬伯樂然後才有千里馬。千里馬常有而伯樂難得。庸人不知馬之雄才，策之不以道，反嘆天下無馬。痛斥統治者摧殘壓抑賢才。",
     "There are Bole who recognize talent, and only then千里 horses emerge. The feeder starves the steed and wields the whip crying: 'There are no steeds under Heaven!' Alas, he simply knows not steeds!",
     "韓愈借千里馬受辱槽櫪設喻，為懷才不遇之士大夫發出震耳欲聾之憤懣抗議，喻理精闢令人深省。",
     "【漢越音考證】馬 (Mã), 伯 (Bá), 樂 (Nhạc / Lạc), 槽 (Tào), 櫪 (Lịch), 策 (Sách).",
     [{"viet": "Thế hữu Bá Nhạc, nhiên hậu hữu thiên lý mã. Thiên lý mã thường hữu, nhi Bá Nhạc bất thường hữu.", "zh": "世有伯樂，然後有千里馬。千里馬常有，而伯樂不常有。", "en": "Only when there is a Bole in the world are thousand-li steeds discovered. Such steeds are common, but Bole is rare.", "hanViet": "Thế hữu Bá Nhạc"}]),

    # Round 16: 柳宗元山水散文
    (16, "v3", "r16_01_liuzongyuan_xishan", "柳宗元《始得西山宴遊記》", "Liễu Tông Nguyên - Thủy Đắc Tây Sơn Yến Du Ký", "Liu Zongyuan: First Excursion to West Mountain", "柳宗元", "Liễu Tông Nguyên", "唐代", "Đường",
     "自余為僇人，居是州，恆惴慄。其隙也，則施施而行，漫漫而遊。日與其徒上高山，入深林，窮迴溪，幽泉怪石，無遠不到。今年九月二十八日，因坐法華西亭，望西山，始指異之。遂命僕過湘江，緣染溪，斫榛莽，焚茅茷，窮山之高而止。攀援而登，箕踞而遨，則凡數州之土壤，皆在衽席之下。心凝形釋，與萬化冥合。然後知吾嚮之未始遊，遊於是乎始！",
     "柳宗元貶謫永州登西山。登臨絕頂四顧蒼茫，心神凝結形體消解，與天地萬物化合為一。方知此前非真遊，遊歷自西山始。",
     "Sitting on the summit of West Mountain, my mind condensed and bodily constraints dissolved, merging into oneness with the boundless transformation of the cosmos!",
     "永州八記首篇，開闢中國山水遊記散文天人合一、藉山水滌蕩政治遷謫憂憤之崇高審美境域。",
     "【漢越音考證】柳 (Liễu), 宗 (Tông), 元 (Nguyên), 僇 (Lục), 榛 (Trăn), 冥 (Minh).",
     [{"viet": "Tâm ngưng hình thích, dữ vạn hóa minh hợp.", "zh": "心凝形釋，與萬化冥合。", "en": "Mind condensed and physical form dissolved, merging into union with the infinite cosmos.", "hanViet": "Tâm ngưng hình thích"}]),

    (16, "v3", "r16_02_liuzongyuan_xiaoshitan", "柳宗元《小石潭記》", "Liễu Tông Nguyên - Tiểu Thạch Đàm Ký", "Liu Zongyuan: The Small Stone Pond", "柳宗元", "Liễu Tông Nguyên", "唐代", "Đường",
     "從小丘西行百二十步，隔篁竹，聞水聲，如鳴珮環，心樂之。伐竹取道，下見小潭，水尤清冽。全石以為底，近岸，卷石底以出，為坻，為嶼，為嵁，為巖。青樹翠蔓，蒙絡搖綴，參差披拂。潭中魚可百許頭，皆若空游無所依，日光下澈，影布石上。佁然不動，俶爾遠逝，往來翕忽。坐潭上，四面竹樹環合，寂寥無人，悽神寒骨，悄愴幽邃。以其境過清，不可久居，乃記之而去。",
     "小石潭水尤清冽全石為底。潭中游魚百許若空游無所依，日光下澈影布石上。潭四周竹樹環合寂寥幽邃，悽神寒骨不可久居乃記之而去。",
     "Fish swam as if floating in clear air with sunlight casting shadows on rocks below. The absolute solitude chilled the spirit with deep haunting sorrow.",
     "小石潭記以神妙筆觸寫水之空靈清澈與游魚動靜，結尾融情入景，幽邃孤清照見貶謫文人之孤寂心靈。",
     "【漢越音考證】潭 (Đàm), 冽 (Liệt), 嶼 (Dữ), 俶 (Thục), 寂 (Tịch), 寥 (Liêu), 邃 (Thúy).",
     [{"viet": "Đàm trung ngư khả bách hứa đầu, giai nhược không du vô sở y.", "zh": "潭中魚可百許頭，皆若空游無所依。", "en": "About a hundred fish in the pool seemed to swim freely in empty air with nothing underneath.", "hanViet": "Đàm trung ngư giai nhược không du"}]),

    (16, "v3", "r16_03_liuzongyuan_bushezhe", "柳宗元《捕蛇者說》", "Liễu Tông Nguyên - Bổ Xà Giả Thuyết", "Liu Zongyuan: The Snake Catcher", "柳宗元", "Liễu Tông Nguyên", "唐代", "Đường",
     "永州之野產異蛇，黑質而白章，觸草木盡死，以齧人，無御之者。然得而腊之以為餌，可以已大風、攣踠、瘻癘。太醫以王命聚之，歲賦其二。蔣氏大戚，汪然出涕曰：「君將哀而生之乎？則吾斯役之不幸，未若復吾賦不幸之甚也！悍吏之來吾鄉，叫囂乎東西，隳突乎南北，譁然而駭者，雖雞狗不得寧焉。吾恂恂而起，視其缶，而吾蛇尚存，則弛然而臥。孰知賦斂之毒，有甚是蛇者乎！」",
     "永州毒蛇劇毒無比，捕蛇人蔣氏祖父三代寧冒奇毒捕蛇免稅。苛政猛於虎，催租悍吏橫行鄉里，深刻揭露賦斂之毒甚於毒蛇之殘酷社會現實。",
     "Fierce tax collectors terrorize our village worse than venomous snakes. Who knew that the poison of oppressive taxation is far deadlier than deadly snakes!",
     "柳宗元繼承《禮記·苛政猛於虎》精神，以銳利筆鋒揭露唐代苛捐雜稅剝削百姓之慘狀，具強烈現實批判力。",
     "【漢越音考證】蛇 (Xà), 捕 (Bổ), 齧 (Niết), 賦 (Phú), 囂 (Hiêu), 毒 (Độc).",
     [{"viet": "Thục tri phú liễm chi độc, hữu thậm thị xà giả hồ!", "zh": "孰知賦斂之毒，有甚是蛇者乎！", "en": "Who would have thought that the poison of oppressive taxation is far worse than this venomous snake!", "hanViet": "Phú liễm chi độc thậm thị xà"}]),

    (16, "v3", "r16_04_liuzongyuan_guotuo", "柳宗元《種樹郭橐駝傳》", "Liễu Tông Nguyên - Chủng Thụ Quách Thác Đà Truyện", "Liu Zongyuan: Camel Guo the Tree Planter", "柳宗元", "Liễu Tông Nguyên", "唐代", "Đường",
     "郭橐駝不知始何名。病僂，隆然伏行，有類橐駝者，故鄉人號之「駝」。橐駝善種樹，凡長安豪家富人為觀遊及賣果者，皆爭迎取養。橐駝曰：「橐駝非能使木壽且孳也，能順木之天，以致其性焉爾。凡植木之性，其本欲舒，其培欲平，其土欲故，其築欲密。既然已，勿動勿慮，去不復顧。其蒔也若子，其置也若棄，則其天者全而其性得矣。吾聞長安之政，長吏好煩其令，旦暮吏來呼曰：『官命促爾耕，勖爾植！』爪其膚以驗其生枯，搖其本以觀其疏密，木安得生？」",
     "駝背郭橐駝善種樹，秘訣在於順應樹木自然生長天性，栽種後不妄加擾動。以此諷喻官吏政令煩苛頻頻騷擾百姓反致民不聊生。",
     "The secret to planting trees is allowing their natural nature to flourish without meddling. Over-governing with incessant orders only destroys the people!",
     "以寓言寄寓政治哲理，主張寬簡為政、休養生息、反對盲目干預折騰百姓，為古代無為而治之生動闡發。",
     "【漢越音考證】橐 (Thác), 駝 (Đà), 僂 (Lũ), 孳 (Tư), 舒 (Thư), 煩 (Phiền).",
     [{"viet": "Năng thuận mộc chi thiên, dĩ trí kỳ tính yên nhĩ.", "zh": "能順木之天，以致其性焉爾。", "en": "Simply conform to the tree's natural principles so its inherent nature may fulfill itself.", "hanViet": "Thuận mộc chi thiên"}]),

    (16, "v3", "r16_05_liuzongyuan_qianzhilv", "柳宗元《三戒·黔之驢》", "Liễu Tông Nguyên - Tam Giới - Kiềm Chi Lư", "Liu Zongyuan: The Donkey of Qian", "柳宗元", "Liễu Tông Nguyên", "唐代", "Đường",
     "黔無驢，有好事者船載以入。至則無可用，放之山下。虎見之，龐然大物也，以為神，蔽林間窺之。稍出近之，慭慭然，莫相知。他日，驢一鳴，虎大駭，遠遁；以為且噬己也，甚恐。然往來視之，覺無異能者；益習其聲，又近出前後，終不敢搏。稍近益狎，蕩倚衝冒。驢不勝怒，蹄之。虎因喜，計之曰：「技止此耳！」因跳踉大㘎，斷其喉，盡其肉，乃去。",
     "貴州無驢，好事者運驢置於山下。老虎初見龐然大物懼之，後見驢只會大叫踢腿，大喜道「技止此耳」，撲殺食其肉而去。",
     "The tiger feared the donkey as a giant divine beast at first, but realizing its only trick was kicking, the tiger laughed: 'Its skill is merely this!' and devoured it.",
     "「龐然大物、黔驢技窮」成為漢語與漢越成語經典，諷刺無才無德空有虛表之無能庸官終將自取滅亡。",
     "【漢越音考證】黔 (Kiềm), 驢 (Lư), 龐 (Bàng), 遁 (Độn), 噬 (Phệ), 蹄 (Đề), 踉 (Lương).",
     [{"viet": "Hổ nhân hỉ, kế chi viết: 'Kỹ chỉ thử nhĩ!'", "zh": "虎因喜，計之曰：「技止此耳！」", "en": "The tiger rejoiced, calculating: 'Its trick is merely this!'", "hanViet": "Kiềm lư kỹ cùng"}]),

    # Round 17: 歐陽修平易清新
    (17, "v3", "r17_01_ouyangxiu_zuiwengting", "歐陽修《醉翁亭記》", "Âu Dương Tu - Túy Ông Đình Ký", "Ouyang Xiu: An Account of the Old Drunkard Pavilion", "歐陽修", "Âu Dương Tu", "北宋", "Bắc Tống",
     "環滁皆山也。其西南諸峰，林壑尤美，望之蔚然而深秀者，瑯琊也。山行六七里，漸聞水聲潺潺，而瀉出於兩峰之間者，釀泉也。峰回路轉，有亭翼然臨於泉上者，醉翁亭也。作亭者誰？山之僧智仙也。名之者誰？太守自謂也。太守與客來飲於此，飲少輒醉，而年又最高，故自號曰醉翁也。醉翁之意不在酒，在乎山水之間也。山水之樂，得之心而寓之酒也。人知從太守遊而樂，而不知太守之樂其樂也。醉能同其樂，醒能述以文者，太守也。太守謂誰？廬陵歐陽修也。",
     "滁州瑯琊山峰回路轉釀泉之上建醉翁亭。歐陽修自號醉翁，醉翁之意不在酒在乎山水之間也。與民同樂，太守樂其樂，醒能述以文者太守歐陽修也。",
     "The Old Drunkard's interest lies not in the wine, but in the mountains and waters. To rejoice in their joy while drunk, and record it in prose when sober - that is the Prefect!",
     "北宋散文登峰造極之作，辭調流暢舒緩層層設色，將「與民同樂」之儒家政治情懷融入醉翁山水勝境。",
     "【漢越音考證】歐 (Âu), 陽 (Dương), 修 (Tu), 滁 (Trừ), 瑯 (Lang), 琊 (Gia), 壑 (Hác), 潺 (Sàn).",
     [{"viet": "Túy ông chi ý bất tại tửu, tại hồ sơn thủy chi gian dã. Sơn thủy chi lạc, đắc chi tâm nhi ngụ chi tửu dã.", "zh": "醉翁之意不在酒，在乎山水之間也。山水之樂，得之心而寓之酒也。", "en": "The Old Drunkard's delight lies not in wine, but in hills and waters, grasped by the heart and lodged in wine.", "hanViet": "Túy ông chi ý bất tại tửu"}]),

    (17, "v3", "r17_02_ouyangxiu_qiushengfu", "歐陽修《秋聲賦》", "Âu Dương Tu - Thu Thanh Phú", "Ouyang Xiu: Rhapsody on the Sounds of Autumn", "歐陽修", "Âu Dương Tu", "北宋", "Bắc Tống",
     "歐陽子方夜讀書，聞有聲自西南來者，悚然而聽之，曰：「異哉！」初淅瀝以蕭颯，忽奔騰而澎湃，如波濤夜驚，風雨驟至。其觸於物也，鏜鏜鏜，金鐵皆鳴；又如赴敵之兵，銜枚疾走，不聞號令，但聞人馬之行聲。余曰：「噫，嘻！此秋聲也。草拂之而色變，木遭之而葉脫；其所以摧敗零落者，乃其一氣之餘烈。夫秋，刑官也，於時為陰；又兵象也，於行為金。夫草木無情，有時飄零。人為動物，惟物之靈。百憂感其心，萬事勞其形。奈何以非金石之質，欲與草木而爭榮？念誰為之戕賊，亦何恨乎秋聲！」",
     "夜讀聞秋聲蕭颯澎湃如兵馬夜行。秋風肅殺草木摧殘，人為萬物之靈百憂感心萬事勞形，何必以血肉之軀與草木爭榮、怨恨秋聲！",
     "Autumn comes with the sound of raging seas and iron blades, stripping foliage bare. Why should man of fragile flesh labor with endless cares and blame the sound of autumn?",
     "歐陽修借秋聲之肅殺發抒生命衰老與人生憂患之深刻反思，文氣跌宕駢散結合，為宋賦散文化之傑作。",
     "【漢越音考證】秋 (Thu), 聲 (Thanh), 賦 (Phú), 悚 (Khủng), 澎 (Bành), 湃 (Bái), 戕 (Tường).",
     [{"viet": "Bách ưu cảm kỳ tâm, vạn sự lao kỳ hình. Nại hà dĩ phi kim thạch chi chất, dục dữ thảo mộc nhi tranh vinh?", "zh": "百憂感其心，萬事勞其形。奈何以非金石之質，欲與草木而爭榮？", "en": "A hundred cares stir man's heart and myriad affairs exhaust his frame; why strive with fragile body against grass and trees for fleeting glory?", "hanViet": "Bách ưu cảm kỳ tâm"}]),

    (17, "v3", "r17_03_ouyangxiu_pengdanglun", "歐陽修《朋黨論》", "Âu Dương Tu - Bằng Đảng Luận", "Ouyang Xiu: On Political Parties", "歐陽修", "Âu Dương Tu", "北宋", "Bắc Tống",
     "臣聞朋黨之說，自古有之，惟幸人君辨其君子小人而已。大凡君子與君子，以同道為朋；小人與小人，以同利為朋，此自然之理也。然臣謂小人無朋，其暫為朋者，偽也。君子則不然。所守者道義，所行者忠信，所惜者名節。以之修身，則同道而相益；以之事國，則同心而共濟，終始如一，此君子之朋也。故為人君者，但當退小人之偽朋，用君子之真朋，則天下治矣。",
     "歐陽修精闢辨析朋黨：小人以私利結黨，利盡則互相傾軋交殘無真朋；君子以同道為朋，守道義行忠信休戚與共。人君當辨退小人偽朋而用君子真朋。",
     "Gentlemen unite as party through shared moral Way, whereas petty men unite for transient mutual profit. An enlightened ruler rejects false factions of petty men and embraces true parties of gentlemen.",
     "宋代改革派政治綱領名篇，打破歷代將「朋黨」一概斥為奸邪之定論，提出「君子同道之朋」的光明正大之論。",
     "【漢越音考證】朋 (Bằng), 黨 (Đảng), 辨 (Biện), 濟 (Tế), 偽 (Ngụy).",
     [{"viet": "Đại phàm quân tử dữ quân tử, dĩ đồng đạo vi bằng; tiểu nhân dữ tiểu nhân, dĩ đồng lợi vi bằng.", "zh": "大凡君子與君子，以同道為朋；小人與小人，以同利為朋。", "en": "Gentlemen form comradeship through shared moral Way; petty men form factions through common selfish profit.", "hanViet": "Đồng đạo vi bằng"}]),

    (17, "v3", "r17_04_ouyangxiu_maiyouweng", "歐陽修《賣油翁》", "Âu Dương Tu - Mại Dầu Ông", "Ouyang Xiu: The Oil Peddler", "歐陽修", "Âu Dương Tu", "北宋", "Bắc Tống",
     "陳康肅公堯咨善射，當世無雙，公亦以此自矜。嘗射於家圃，十中八九，客皆歎絕。見一賣油翁釋擔而立，睨之，久而不去。見其發矢十中八九，但微頷之。康肅問曰：「汝亦知射乎？吾射不亦精乎？」翁曰：「無他，但手熟爾。」康肅忿然曰：「爾安敢輕吾射！」翁曰：「以我酌油知之。」乃取一葫蘆置於地，以錢覆其口，徐以杓酌油瀝之，自錢孔入，而錢不濕。因曰：「我亦無他，唯手熟爾。」康肅笑而遣之。",
     "陳堯咨射箭十中八九自矜自傲。賣油翁取葫蘆覆銅錢，自銅錢方孔瀝油而錢孔不濕，淡然道「無他，但手熟爾」，陳堯咨笑服。",
     "The old oil peddler poured oil through a coin's hole without wetting it, smiling: 'There is no special secret, merely practice making skill perfect!'",
     "以生動短小故事闡述深奧哲理，千古名言「無他，但手熟爾（熟能生巧）」教人戒驕戒躁虛心求精。",
     "【漢越音考證】賣 (Mại), 油 (Du), 翁 (Ông), 矜 (Căng), 頷 (Hạm), 酌 (Chước), 杓 (Tiêu / Chước).",
     [{"viet": "Vô tha, đãn thủ thục nhĩ.", "zh": "無他，但手熟爾。", "en": "There is no special secret, merely that hands are well-practiced.", "hanViet": "Vô tha đãn thủ thục nhĩ"}]),

    (17, "v3", "r17_05_ouyangxiu_lingguan", "歐陽修《新五代史·伶官傳序》", "Âu Dương Tu - Tân Ngũ Đại Sử - Linh Quan Truyện Tự", "Ouyang Xiu: Preface to the Lives of the Actors", "歐陽修", "Âu Dương Tu", "北宋", "Bắc Tống",
     "嗚呼！盛衰之理，雖曰天命，豈非人事哉！原莊宗之所以得天下，與其所以失之者，可以知之矣。世言晉王之將終也，以三矢賜莊宗而告之曰：「梁，吾仇也；燕王，吾所立；契丹與吾約為兄弟，而皆背晉以歸梁。此三者，吾遺恨也。與爾三矢，爾其無忘乃父之志！」莊宗受而藏之於廟。其後用兵，負矢而行，遂滅燕、破契丹、平朱梁。方其係燕父子以組，函梁君臣之首，入於太廟，還矢先王，而告以成功，其意氣之盛，可謂壯哉！及仇讎已滅，天下已定，一夫夜呼，亂者四應，身死國滅，為天下笑。憂勞可以興國，逸豫可以亡身，自然之理也。故夫禍患常積於忽微，而智勇多困於所溺，豈獨伶人也哉！",
     "後唐莊宗受父三矢奮勇滅燕破契丹克梁，意氣風發何等雄壯！然天下既定溺愛伶人歌舞，終致身死國滅。結論：憂勞可以興國，逸豫可以亡身，禍患常積於忽微，智勇多困於所溺。",
     "Diligence and hardship can revive a kingdom, while indolence and pleasure lead to ruin. Disasters accumulate from trivial oversights, and wisdom is trapped by indulgence!",
     "史論散文名篇，以抑揚頓挫、氣勢磅礴之文筆論證盛衰由人事非天命，警示千古治國興衰成敗。",
     "【漢越音考證】伶 (Linh), 官 (Quan), 矢 (Thỉ), 函 (Hàm), 仇 (Cừu), 讎 (Thù), 溺 (Nịch).",
     [{"viet": "Ưu lao khả dĩ hưng quốc, dật dự khả dĩ vong thân, tự nhiên chi lý dã.", "zh": "憂勞可以興國，逸豫可以亡身，自然之理也。", "en": "Hardship and vigilance can prosper a nation; luxury and ease can destroy a life.", "hanViet": "Ưu lao khả dĩ hưng quốc"}]),

    # Round 18: 蘇軾曠達赤壁
    (18, "v3", "r18_01_sushi_qianchibi", "蘇軾《前赤壁賦》", "Tô Thức - Tiền Xích Bích Phú", "Su Shi: Former Rhapsody on the Red Cliff", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "壬戌之秋，七月既望，蘇子與客泛舟遊於赤壁之下。清風徐來，水波不興。誦明月之詩，歌窈窕之章。少焉，月出於東山之上，徘徊於斗牛之間。白露橫江，水光接天。縱一葦之所如，凌萬頃之茫然。客有吹洞簫者，倚歌而和之。其聲嗚嗚然，如怨如慕，如泣如訴，餘音嫋嫋，不絕如縷。舞幽壑之潛蛟，泣孤舟之嫠婦。蘇子愀然，問客何為感傷。客論曹操千古英雄安在，感人生短促如蜉蝣渺滄海之一粟。蘇子曰：「客亦知夫水與月乎？逝者如斯，而未嘗往也；盈虛者如彼，而卒莫消長也。蓋將自其變者而觀之，則天地曾不能以一瞬；自其不變者而觀之，則物與我皆無盡也，而又何羨乎！且夫天地之間，物各有主，苟非吾之所有，雖一毫而莫取。惟江上之清風，與山間之明月，耳得之而為聲，目遇之而成色，取之無禁，用之不竭，是造物者之無盡藏也，而吾與子之所共適。」客喜而笑，洗盞更酌。餚核既盡，杯盤狼籍。相與枕藉乎舟中，不知東方之既白。",
     "蘇軾貶黃州與客泛舟赤壁，聞洞簫悲咽感喟人生短促英雄安在。蘇軾以水月之喻開解：自變者觀之天地不存一瞬，自不變者觀之物我皆無盡。惟江上清風山間明月取之無禁，乃造物者無盡寶藏。客喜大悟醉臥迎東方既白。",
     "Su Shi and his guest floated beneath the Red Cliff. The guest lamented human life as fleeting as mayflies. Su Shi replied: 'Viewed from change, Heaven and Earth vanish in an instant; viewed from constancy, all things and we are limitless. The pure breeze on the river and bright moon upon hills are the Creator's inexhaustible treasure!'",
     "中國賦體文學與儒釋道曠達哲思融合之千古第一賦，文辭如行雲流水，以超然物外之大智慧安頓心靈苦難。",
     "【漢越音考證】軾 (Thức), 赤 (Xích), 壁 (Bích), 賦 (Phú), 葦 (Vĩ), 簫 (Tiêu), 嫋 (Niểu), 蜉 (Phù), 蝣 (Du), 藏 (Tàng).",
     [{"viet": "Duy giang thượng chi thanh phong, dữ sơn gian chi minh nguyệt, nhĩ đắc chi nhi vi thanh, mục ngộ chi nhi thành sắc, thủ chi vô cấm, dụng chi bất kiệt, thị tạo vật giả chi vô tận tàng dã.", "zh": "惟江上之清風，與山間之明月，耳得之而為聲，目遇之而成色，取之無禁，用之不竭，是造物者之無盡藏也。", "en": "The clear breeze over the river and the bright moon upon the mountains: taken without prohibition, used without exhaustion, this is the Creator's inexhaustible treasure.", "hanViet": "Tạo vật giả chi vô tận tàng"}]),

    (18, "v3", "r18_02_sushi_houchibi", "蘇軾《後赤壁賦》", "Tô Thức - Hậu Xích Bích Phú", "Su Shi: Latter Rhapsody on the Red Cliff", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "是歲十月之望，步自雪堂，將歸於臨皋。霜露既降，木葉盡脫。人影在地，仰見明月，顧而樂之，行歌相答。復攜酒與魚，再遊赤壁。江流有聲，斷岸千尺；山高月小，水落石出。曾日月之幾何，而江山不可復識矣！予乃攝衣而上，履巉巖，披蒙茸，踞虎豹，登虬龍，攀棲鶻之危巢，俯馮夷之幽宮。劃然長嘯，草木震動，山鳴谷應，風起水湧。予亦悄然而悲，肅然而恐，凜乎其不可留也。適有孤鶴，橫江東來，翅如車輪，玄裳縞衣，戛然長鳴，掠予舟而西也。夜夢道士，化鶴翩然而過。",
     "十月再遊赤壁，霜露既降木葉盡脫。山高月小水落石出江山迥異。蘇軾登巉巖長嘯風起水湧，忽有玄裳縞衣孤鶴橫江而過掠舟西去。夜夢道士化鶴仙遊。",
     "Revisiting Red Cliff in winter: frost had fallen, leaves dropped; the river echoed, cliffs stood a thousand feet; the mountain was high and the moon small, water receded revealing rocks below.",
     "名句「山高月小，水落石出」傳神寫出冬夜赤壁之奇峻幽絕，孤鶴化仙之夢境寄託超脫塵世之羽化遐思。",
     "【漢越音考證】鶴 (Hạc), 巉 (Sàm), 巖 (Nham), 縞 (Hạo), 戛 (Kiệt).",
     [{"viet": "Giang lưu hữu thanh, đoạn ngạn thiên xích; sơn cao nguyệt tiểu, thủy lạc thạch xuất.", "zh": "江流有聲，斷岸千尺；山高月小，水落石出。", "en": "The river flowed audibly, the sheer cliff rose a thousand feet; mountain was high, moon was small, water fell revealing stones.", "hanViet": "Sơn cao nguyệt tiểu thủy lạc thạch xuất"}]),

    (18, "v3", "r18_03_sushi_shizhongshan", "蘇軾《石鐘山記》", "Tô Thức - Thạch Chung Sơn Ký", "Su Shi: Record of Stone Bell Mountain", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "《水經》云：「彭蠡之口有石鐘山焉。」酈元以為下臨深潭，微風鼓浪，水石相搏，聲如洪鐘。李渤得雙石於潭上，扣而聆之，南聲函胡，北音清越。余尤疑之。元豐七年六月丁丑，余自齊安舟行適臨汝，夜泊絕壁之下。大石側立千尺，如猛獸奇鬼，森然欲搏人。而微風徐動，波浪澎湃，舟人相搏於石間，噌吰如鐘鼓不絕。事不目見耳聞，而臆斷其有無，可乎？酈元之所見聞，殆與余同，而言之不詳；李渤之臆斷，尤不足道也。此世所以不傳也。",
     "蘇軾夜乘小舟探訪鄱陽湖口石鐘山，親臨絕壁聽水石相搏如洪鐘噌吰，揭開石鐘命名之謎。結論：事不目見耳聞而臆斷有無，不可也！",
     "Su Shi visited Stone Bell Mountain at night to investigate the sound. Conclusion: Can one make arbitrary assumptions on the existence of things without seeing with one's own eyes and hearing with one's own ears?",
     "融實地科學考察、親身實踐檢驗與精湛山水描摹於一體，提出嚴謹求真之唯物實踐認識論。",
     "【漢越音考證】鐘 (Chung), 蠡 (Lễ / Loa), 噌 (Tăng), 吰 (Hoành), 臆 (Ức).",
     [{"viet": "Sự bất mục kiến nhĩ văn, nhi ức đoán kỳ hữu vô, khả hồ?", "zh": "事不目見耳聞，而臆斷其有無，可乎？", "en": "Without seeing with one's eyes and hearing with one's ears, is it proper to make subjective assumptions on truth?", "hanViet": "Sự bất mục kiến nhĩ văn"}]),

    (18, "v3", "r18_04_sushi_chengtian", "蘇軾《記承天寺夜遊》", "Tô Thức - Ký Thừa Thiên Tự Dạ Du", "Su Shi: Night Walk to Chengtian Temple", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "元豐六年十月十二日夜，解衣欲睡，月色入戶，欣然起行。念無與為樂者，遂至承天寺，尋張懷民。懷民亦未寢，相與步於中庭。庭下如積水空明，水中藻荇交橫，蓋竹柏影也。何夜無月？何處無竹柏？但少閑人如吾兩人者耳。",
     "月色入戶蘇軾夜訪承天寺張懷民。中庭月光積水空明藻荇交橫，實為竹柏疏影。何夜無月何處無竹柏？但少如吾兩人豁達之閒人耳。",
     "The moonlight flooded my doorway. I walked to Chengtian Temple to find Zhang Huaimin. Moonlight filled the courtyard like clear pooled water with shadows of bamboo and cypress. What night lacks a moon? But rare are idle minds like ours!",
     "短短八十餘字神妙如天開，以空靈透澈之筆寫月影竹柏，展現貶謫逆境中超邁曠達之名士心境。",
     "【漢越音考證】承 (Thừa), 天 (Thiên), 藻 (Tảo), 荇 (Hạnh), 柏 (Bách), 寢 (Tẩm).",
     [{"viet": "Đình hạ như tích thủy không minh, thủy trung tảo hạnh giao hoành, cái trúc bách ảnh dã. Hà dạ vô nguyệt? Hà xứ vô trúc bách? Đãn thiểu nhàn nhân như ngô lưỡng nhân giả nhĩ.", "zh": "庭下如積水空明，水中藻荇交橫，蓋竹柏影也。何夜無月？何處無竹柏？但少閑人如吾兩人者耳。", "en": "The courtyard was like clear water pooled, with algae and weeds crossing—these were shadows of bamboo and cypress. What night has no moon? But rare are leisure souls like us two.", "hanViet": "Đình hạ như tích thủy không minh"}]),

    (18, "v3", "r18_05_sushi_liuhoulun", "蘇軾《留侯論》", "Tô Thức - Lưu Hầu Luận", "Su Shi: On Marquis of Liu (Zhang Liang)", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "古之所謂豪傑之士者，必有過人之節。人情有所不能受者，匹夫見辱，拔劍而起，挺身而鬥，此不足為勇也。天下有大勇者，卒然臨之而不驚，無故加之而不怒。此其所挾持者甚大，而其志甚遠也。張良圯上受書於黃石公，忍小忿而就大謀。",
     "蘇軾論張良圯上受書大忍之智：匹夫受辱拔劍相鬥非真勇。天下大勇者猝然臨之不驚、無故加之不怒，忍小忿以成就安邦興漢之宏圖大業。",
     "A true hero of supreme courage is not alarmed when unexpected crises arrive, nor angered by baseless insult, for his vision is grand and his ambition far-reaching.",
     "立論精闢警策，「猝然臨之而不驚，無故加之而不怒」為後世論述心性大勇與戰略大忍之極致格言。",
     "【漢越音考證】留 (Lưu), 侯 (Hầu), 勇 (Dũng), 猝 (Thốt), 圯 (Tì), 忿 (Phẫn).",
     [{"viet": "Thiên hạ hữu đại dũng giả, thốt nhiên lâm chi nhi bất kinh, vô cố gia chi nhi bất nộ. Thử kỳ sở hiệp trì giả thậm đại, nhi kỳ chí thậm viễn dã.", "zh": "天下有大勇者，卒然臨之而不驚，無故加之而不怒。此其所挾持者甚大，而其志甚遠也。", "en": "The truly courageous man is not alarmed when crisis descends suddenly, nor angered when unjustly insulted, for his resolve is immense and his aim far-reaching.", "hanViet": "Thiên hạ hữu đại dũng giả"}]),

    # Round 19: 三蘇與王安石
    (19, "v3", "r19_01_suxun_liuguolun", "蘇洵《六國論》", "Tô Tuân - Lục Quốc Luận", "Su Xun: On the Six States", "蘇洵", "Tô Tuân", "北宋", "Bắc Tống",
     "六國破滅，非兵不利，戰不善，弊在賂秦。賂秦而力虧，破滅之道也。或曰：「六國互喪，率賂秦耶？」曰：「不賂者以賂者喪。蓋失強援，不能獨完。故曰：弊在賂秦也。」秦以攻取之外，小則獲邑，大則得城。較秦之所得與戰勝而得者，其實百倍；諸侯之所亡與戰敗而亡者，其實亦百倍。則秦之所大欲，諸侯之所大患，固不在戰矣。今日割五城，明日割十城，然後得一夕安寢。起視四境，而秦兵又至矣。悲夫！以賂秦之地封天下之謀臣，以事秦之心禮天下之奇才，并力西向，則吾恐秦人食之不得下咽也。苟以天下之大，下而從六國破亡之故事，是又在六國下矣。",
     "蘇洵論六國滅亡根本弊在割地賄賂秦國，賄秦力虧反助敵暴。借古諷今警示北宋統治者切勿對遼西夏屈辱納幣媾和。",
     "The fall of the Six States was not due to poor arms, but due to appeasing Qin with land. Today ceding five cities, tomorrow ten, buying only one night of troubled sleep!",
     "氣勢磅礴論點犀利，以戰國六國割地求和之覆轍，發出反對屈辱妥協、倡導同仇敵愾抵抗強暴之歷史警鐘。",
     "【漢越音考證】洵 (Tuân), 賂 (Lộ), 割 (Cát), 邑 (Ấp), 寢 (Tẩm), 援 (Viện).",
     [{"viet": "Lục quốc phá diệt, phi binh bất lợi, chiến bất thiện, tệ tại lộ Tần.", "zh": "六國破滅，非兵不利，戰不善，弊在賂秦。", "en": "The fall of the Six States was not due to poor arms or bad warfare, but due to appeasing Qin.", "hanViet": "Lục quốc phá diệt tệ tại lộ Tần"}]),

    (19, "v3", "r19_02_suzhe_shanghantaiwei", "蘇轍《上樞密韓太尉書》", "Tô Triệt - Thượng Khu Mật Hàn Thái Úy Thư", "Su Zhe: Letter to Grand Commandant Han", "蘇轍", "Tô Triệt", "北宋", "Bắc Tống",
     "轍生好為文，思之至深。以為文者氣之所形，然文不可以學而能，氣可以養而致。司馬遷行天下，周覽四海名山大川，與燕趙間豪俊交遊，故其文疏蕩，頗有奇氣。轍雖貧，行天下，過秦漢之故都，觀終南、嵩、華之高，浮黃河、長江之險，見天地之廣大，然後文氣充盈。今得見太尉，願觀大臣之容貌風采，以充吾文氣！",
     "蘇轍上書韓琦論養氣作文：文章是內在浩然之氣的展現，不可單純模擬學得，而須透過遊歷名山大川、結交天下豪傑涵養其氣。",
     "Literature is the manifestation of inner spirit (Qi). Sima Qian roamed mountains and rivers to nourish his vast spirit; I too seek to enlarge my vision.",
     "闡發孟子「養浩然之氣」與司馬遷壯遊精神，確立古代作家開闊胸襟、涵養氣質與文學創作之內在關係。",
     "【漢越音考證】轍 (Triệt), 樞 (Khu), 密 (Mật), 尉 (Úy), 氣 (Khí), 充 (Sung), 盈 (Doanh).",
     [{"viet": "Văn giả khí chi sở hình, nhiên văn bất khả dĩ học nhi năng, khí khả dĩ dưỡng nhi trí.", "zh": "文者氣之所形，然文不可以學而能，氣可以養而致。", "en": "Writing is the outward form of spirit (Qi); writing cannot be acquired merely by learning, but spirit can be nurtured to its peak.", "hanViet": "Văn giả khí chi sở hình"}]),

    (19, "v3", "r19_03_wanganshi_baochanshan", "王安石《遊褒禪山記》", "Vương An Thạch - Du Bao Thiền Sơn Ký", "Wang Anshi: Record of Trip to Mount Baochan", "王安石", "Vương An Thạch", "北宋", "Bắc Tống",
     "夫夷以近，則遊者眾；險以遠，則至者少。而世之奇偉、瑰怪，非常之觀，常在於險遠，而人之所罕至焉，故非有志者不能至也。有志矣，不隨以止也，然力不足者，亦不能至也。有志與力，而又不隨以怠，至於幽暗昏惑而無物以相之，亦不能至也。然力足以至焉，於人為可譏，而在己為有悔；盡吾志也而不能至者，可以無悔矣，其孰能譏之乎？此余之所得也。",
     "王安石遊褒禪山華陽洞未窮而返，由是深悟：世間奇偉瑰怪非常之景常在險遠之處，非有志、有力、有物相助不能至。盡吾志而不能至者可以無悔。",
     "The rarest, most sublime wonders of the world lie in perilous and distant places where few tread. Only those with unwavering will can reach them. If one exhausts one's utmost will, there is no regret!",
     "將遊山體驗昇華為追求崇高理想之哲學深思，論證「志、力、物」三者兼備方能攀登人生與事業之絕頂。",
     "【漢越音考證】褒 (Bao), 禪 (Thiền), 瑰 (Khôi), 罕 (Hãn), 怠 (Đãi), 譏 (Cơ).",
     [{"viet": "Nhi thế chi kỳ vĩ, khôi quái, phi thường chi quan, thường tại ư hiểm viễn, nhi nhân chi sở hãn chí yên, cố phi hữu chí giả bất năng chí dã.", "zh": "而世之奇偉、瑰怪，非常之觀，常在於險遠，而人之所罕至焉，故非有志者不能至也。", "en": "The world's rare, wondrous and extraordinary sights often lie in perilous and distant places; none but those of resolute will can reach them.", "hanViet": "Kỳ vĩ khôi quái thường tại hiểm viễn"}]),

    (19, "v3", "r19_04_wanganshi_dasimajianyi", "王安石《答司馬諫議書》", "Vương An Thạch - Đáp Tư Mã Gián Nghị Thư", "Wang Anshi: Reply to Sima Guang", "王安石", "Vương An Thạch", "北宋", "Bắc Tống",
     "某啟：昨日蒙教。竊以為與君實遊處相好之日久，而議事每不合，所操之術多異故也。蓋儒者所爭，尤在於名實。名實已明，而天下之理得矣。今君實所以見教者，以為侵官、生事、徵利、拒諫，以致天下怨謗也。某則以為受命於人主，議法度而修之於朝廷，以授之於有司，不為侵官；舉先王之政，以興利除弊，不為生事；為天下理財，不為徵利；辟邪說，難壬人，不為拒諫。如曰今日當一切不事事，守前所為而已，則非某之所敢知。",
     "王安石變法遭司馬光致信指責侵官生事徵利拒諫。王安石作書嚴正駁斥：興利除弊非生事、理財非徵利、闢邪說非拒諫，堅持改革初心絕不因怨謗動搖。",
     "Reforming laws to eliminate abuses is not causing trouble; managing state wealth for the people is not extorting profit. I will not yield to cowardice and maintain corrupt decay!",
     "宋代變法論戰最高文獻，文筆剛健斬截、邏輯嚴密如水銀瀉地，展現「天變不足畏、祖宗不足法、人言不足恤」之改革家無畏魄力。",
     "【漢越音考證】諫 (Gián), 謗 (Báng), 弊 (Tệ), 辟 (Tịch), 壬 (Nhâm).",
     [{"viet": "Cử tiên vương chi chính, dĩ hưng lợi trừ tệ, bất vi sinh sự; vi thiên hạ lý tài, bất vi trưng lợi.", "zh": "舉先王之政，以興利除弊，不為生事；為天下理財，不為徵利。", "en": "Promoting the sages' governance to foster benefit and eliminate abuse is not causing trouble; managing wealth for the world is not extorting profit.", "hanViet": "Hưng lợi trừ tệ"}]),

    (19, "v3", "r19_05_wanganshi_shangzhongyong", "王安石《傷仲永》", "Vương An Thạch - Thương Trọng Vĩnh", "Wang Anshi: Lament for Fang Zhongyong", "王安石", "Vương An Thạch", "北宋", "Bắc Tống",
     "金溪民方仲永，世隸耕。仲永生五年，未嘗識書具，忽啼求之。父異焉，借旁近與之，即書詩四句，並自為其名。其詩以養父母、收族為意，傳一鄉秀才觀之。自是指物作詩立就，其文理皆有可觀者。邑人奇之，稍稍賓客其父，或以錢幣乞之。父利其然也，日扳仲永環謁於邑人，不使學。余聞之也久。明道中，從先人還家，於舅家見之，十二三矣。令作詩，不能稱前時之聞。又七年，還自揚州，復到舅家問焉。曰：「泯然眾人矣！」王子曰：仲永之通悟，受之天也。其受之天也，賢於材人遠矣。卒之為眾人，則其受於人者不至也。彼其受之天也，如此其賢也，不受之人，且為眾人；今夫不受之天，固眾人，又不受之人，得為眾人而已邪！",
     "神童方仲永五歲能指物題詩，其父利其名聲日扳環謁不使學習。十二歲才名退減，二十歲泯然眾人。王安石感嘆：天賦雖高若不受後天教育終歸平庸。",
     "Zhongyong was a child prodigy who wrote poems at age five. His father exploited his fame and stopped his schooling. By twenty, he had become just an ordinary man!",
     "「泯然眾人矣」警醒後世：先天聰穎遠不足恃，後天勤勉學習與深造方為成才立德之唯一正道。",
     "【漢越音考證】傷 (Thương), 隸 (Lệ), 謁 (Yết), 泯 (Mẫn), 悟 (Ngộ).",
     [{"viet": "Hựu thất niên, phục đáo cữu gia vấn yên. Viết: 'Mẫn nhiên chúng nhân hĩ!'", "zh": "又七年，復到舅家問焉。曰：「泯然眾人矣！」", "en": "After seven more years I asked of him again. They replied: 'He has completely faded into an ordinary man!'", "hanViet": "Mẫn nhiên chúng nhân hĩ"}]),

    # Round 20: 宋代名臣憂樂
    (20, "v3", "r20_01_fanzhongyan_yueyanglou", "范仲淹《岳陽樓記》", "Phạm Trọng Yêm - Nhạc Dương Lâu Ký", "Fan Zhongyan: Memorial on Yueyang Tower", "范仲淹", "Phạm Trọng Yêm", "北宋", "Bắc Tống",
     "慶曆四年春，滕子京謫守巴陵郡。越明年，政通人和，百廢具興，乃重修岳陽樓。予觀夫巴陵勝狀，在洞庭一湖。銜遠山，吞長江，浩浩湯湯，橫無際涯；朝暉夕陰，氣象萬千，此則岳陽樓之大觀也。至若春和景明，波瀾不驚，上下天光，一碧萬頃；沙鷗翔集，錦鱗游泳，岸芷汀蘭，郁郁青青。而或長煙一空，皓月千里，浮光躍金，靜影沉璧，漁歌互答，此樂何極！登斯樓也，則有心曠神怡，寵辱偕忘，把酒臨風，其喜洋洋者矣。嗟夫！予嘗求古仁人之心，或異二者之為，何哉？不以物喜，不以己悲；居廟堂之高則憂其民；處江湖之遠則憂其君。是進亦憂，退亦憂。然則何時而樂耶？其必曰「先天下之憂而憂，後天下之樂而樂」歟！噫！微斯人，吾誰與歸？",
     "重修岳陽樓，范仲淹借洞庭湖陰晴萬千氣象，抒發遷客騷人覽物之情。進一步提出古仁人之心「不以物喜不以己悲」，昇華出「先天下之憂而憂，後天下之樂而樂」的偉大家國情懷。",
     "To feel neither elation by external fortune nor grief for personal loss. Worry before the world worries, and rejoice after the world rejoices!",
     "千古第一名記，將登樓寫景、感懷身世與儒家知識分子以天下為己任之最高道德擔當熔鑄為不朽精神豐碑。",
     "【漢越音考證】范 (Phạm), 淹 (Yêm), 岳 (Nhạc), 陽 (Dương), 樓 (Lâu), 滕 (Đằng), 渚 (Chử), 璧 (Bích).",
     [{"viet": "Tiên thiên hạ chi ưu nhi ưu, hậu thiên hạ chi lạc nhi lạc.", "zh": "先天下之憂而憂，後天下之樂而樂。", "en": "Worry before the world worries, and rejoice only after the world has rejoiced.", "hanViet": "Tiên thiên hạ chi ưu nhi ưu"}]),

    (20, "v3", "r20_02_simaguang_xunjian", "司馬光《訓儉示康》", "Tư Mã Quang - Huấn Kiệm Thị Khang", "Sima Guang: Admonition on Frugality to Son Kang", "司馬光", "Tư Mã Quang", "北宋", "Bắc Tống",
     "吾本寒家，世以清白相承。吾性不喜華靡，自少長，鄙薄珍奇玩好。眾人皆以奢靡為榮，吾心獨以儉素為美。孔子曰：「克己復禮為仁。」御孫曰：「儉，德之共也；侈，惡之大也。」夫儉則寡欲，君子寡欲則不役於物，可以直道而行；小人寡欲則能謹身節用，遠罪豐家。故曰儉為德之共。侈則多欲，君子多欲則貪慕富貴，枉道速禍；小人多欲則多求妄用，敗家喪身。由儉入奢易，由奢入儉難。汝當日夕自勉！",
     "司馬光訓誡其子司馬康崇尚節儉：儉為美德之共性，侈為罪惡之大端。寡欲則不為物役。由儉入奢易，由奢入儉難，當銘記清白家風。",
     "Frugality is the common bond of all virtues; luxury is the chief of all vices. To move from frugality to luxury is easy; to return from luxury to frugality is hard!",
     "司馬光傳家名訓，「由儉入奢易，由奢入儉難」成為中華民族千百年治家立身、反腐倡廉之座右銘。",
     "【漢越音考證】司 (Tư), 馬 (Mã), 光 (Quang), 儉 (Kiệm), 奢 (Xa), 侈 (Sỉ), 役 (Dịch).",
     [{"viet": "Do kiệm nhập xa dị, do xa nhập kiệm nan.", "zh": "由儉入奢易，由奢入儉難。", "en": "It is easy to shift from frugality to luxury, but hard to return from luxury to frugality.", "hanViet": "Do kiệm nhập xa dị do xa nhập kiệm nan"}]),

    (20, "v3", "r20_03_baozheng_qibuyong", "包拯《乞不用贓吏疏》", "Bao Chửng - Khất Bất Dụng Tang Lại Sớ", "Bao Zheng: Memorial against Corrupt Officials", "包拯", "Bao Chửng", "北宋", "Bắc Tống",
     "臣聞廉者，民之表也；貪者，民之賊也。今天下官吏，有犯贓受賄之人，朝廷雖加廢黜，未幾又復錄用，使貪婪之徒無所懲懼，何以肅清綱紀！伏乞陛下下明詔：凡官吏以贓罪被劾者，終身不得復仕，雖有恩赦，不在錄用之列。如此則人知廉恥，風俗清明。",
     "包青天包拯上奏仁宗嚴懲貪官：廉潔者為人民表率，貪婪者乃人民國賊。凡貪贓枉法者終身永不錄用，以整飭官風嚴明法紀。",
     "The honest official is an exemplar to the people; the corrupt official is a thief of the people. Bar all corrupt officials from office for life to purify governance!",
     "包公鐵面無私之清官風骨，嚴禁任用貪官污吏之奏疏展現古代司法清明與為民請命之崇高浩氣。",
     "【漢越音考證】包 (Bao), 拯 (Chửng), 贓 (Tang), 吏 (Lại), 賄 (Hối), 黜 (Truất).",
     [{"viet": "Liêm giả, dân chi biểu dã; tham giả, dân chi tặc dã.", "zh": "廉者，民之表也；貪者，民之賊也。", "en": "The upright official is a model for the people; the corrupt official is a thief to the people.", "hanViet": "Liêm giả dân chi biểu dã"}]),

    (20, "v3", "r20_04_wentianxiang_zhengqige", "文天祥《正氣歌·序與詩》", "Văn Thiên Tường - Chính Khí Ca", "Wen Tianxiang: Song of Upright Air", "文天祥", "Văn Thiên Tường", "南宋", "Nam Tống",
     "余囚北庭，坐一土室。室廣八尺，深可四尋，水氣、土氣、日氣、火氣、米氣、人氣、穢氣，合為七氣。余以一虛弱之軀，蒙此重癘，二年來無恙，豈非仰賴浩然正氣哉！天地有正氣，雜然賦流形。下則為河嶽，上則為日星。於人曰浩然，沛乎塞蒼冥。在齊太史簡，在晉董狐筆。在秦張良椎，在漢蘇武節。為嚴將軍頭，為嵇侍中血。為張睢陽齒，為顏常山舌。或為遼東帽，清操厲冰雪。或為《出師表》，鬼神泣壯烈。或為渡江楫，慷慨吞胡羯。或為擊賊笏，逆豎頭破裂。是氣所磅礡，凜烈萬古存。當其貫日月，生死安足論！",
     "文天祥被囚元大都地牢二年作《正氣歌》。歷數齊太史簡、董狐筆、張良椎、蘇武節、諸葛亮出師表等千古忠臣義烈之正氣，生死置之度外。",
     "Heaven and Earth possess an Upright Spirit, manifested in mountains and rivers below, sun and stars above. In man it is the boundless moral force. When it pierces sun and moon, what is life and death to be weighed!",
     "文天祥抗元殉國之浩然長歌，慷慨激昂震古爍今，為中華民族忠貞不屈、捨生取義之至高精神結晶。",
     "【漢越音考證】祥 (Tường), 嶽 (Nhạc), 沛 (Phái), 董 (Đổng), 睢 (Tuy), 笏 (Hốt), 磅 (Bàng), 礡 (Bạc).",
     [{"viet": "Thiên địa hữu chính khí, tạp nhiên phú lưu hình. Hạ tắc vi hà nhạc, thượng tắc vi nhật tinh.", "zh": "天地有正氣，雜然賦流形。下則為河嶽，上則為日星。", "en": "There is an Upright Spirit in Heaven and Earth, flowing into myriad forms: mountains and rivers below, sun and stars above.", "hanViet": "Thiên địa hữu chính khí"}]),

    (20, "v3", "r20_05_wentianxiang_guolingdingyang", "文天祥《過零丁洋》", "Văn Thiên Tường - Quá Linh Đinh Dương", "Wen Tianxiang: Passing Lingding Ocean", "文天祥", "Văn Thiên Tường", "南宋", "Nam Tống",
     "辛苦遭逢起一經，干戈寥落四周星。山河破碎風飄絮，身世浮沉雨打萍。惶恐灘頭說惶恐，零丁洋裏嘆零丁。人生自古誰無死？留取丹心照汗青。",
     "回顧一生舉進士起兵抗元，轉戰四年山河破碎身世浮沉。面對張弘範逼降，文天祥寫下千古絕句：人生自古誰無死？留取丹心照汗青！",
     "Hardships began with studying the classics, four years of warfare passed. The nation shattered like willow fluff, personal fortunes adrift like duckweed in rain. Who since ancient times has not faced death? Let my crimson heart shine in historical annals!",
     "「人生自古誰無死，留取丹心照汗青」為愛國志士視死如歸、以身殉道之永恆精神明燈。",
     "【漢越音考證】零 (Linh), 丁 (Đinh), 灘 (Than), 萍 (Bình), 丹 (Đan), 汗 (Hãn), 青 (Thanh).",
     [{"viet": "Nhân sinh tự cổ thùy vô tử? Lưu thủ đan tâm chiếu hãn thanh.", "zh": "人生自古誰無死？留取丹心照汗青。", "en": "Who has ever escaped death since ancient times? Keep a loyal heart to illuminate the pages of history.", "hanViet": "Nhân sinh tự cổ thùy vô tử"}]),

    # Round 21: 文論與第三卷總結
    (21, "v3", "r21_01_hanyu_dalishu", "韓愈《答李翊書》", "Hàn Dũ - Đáp Lý Dực Thư", "Han Yu: Reply to Li Yi on Writing", "韓愈", "Hàn Dũ", "唐代", "Đường",
     "始者，非三代兩漢之書不敢觀，非聖人之志不敢存。潛心一志，沈浸濃郁，含英咀華，作為文章，其本無所根柢，不能立也。根之茂者其實遂，膏之沃者其光曄，仁義之人，其言藹如也。氣盛則言之短長與聲之高下皆宜。",
     "韓愈指導後進為文：非三代兩漢之書不敢觀，沉浸濃郁含英咀華。根深則果實繁盛，油膏豐厚則燈光耀眼，養浩然之氣則文章氣盛言宜自然成章。",
     "Immerse deeply in classical literature, chewing its blossom and extracting its essence. When inner moral spirit is rich, words naturally flow with grace!",
     "韓愈文學修養理論名篇，「含英咀華、氣盛言宜」成為古典文學創作與博覽群書之至理指南。",
     "【漢越音考證】翊 (Dực), 咀 (Chủy), 華 (Hoa), 膏 (Cao), 沃 (Ốc), 曄 (Diệp), 藹 (Ái).",
     [{"viet": "Căn chi mậu giả kỳ thực toại, cao chi ốc giả kỳ quang diệp.", "zh": "根之茂者其實遂，膏之沃者其光曄。", "en": "Lush roots produce rich fruit; abundant oil sheds radiant light.", "hanViet": "Căn chi mậu giả kỳ thực toại"}]),

    (21, "v3", "r21_02_liuzongyuan_daweizhongli", "柳宗元《答韋中立論師道書》", "Liễu Tông Nguyên - Đáp Vi Trung Lập Luận Sư Đạo Thư", "Liu Zongyuan: Reply on Teacher's Path", "柳宗元", "Liễu Tông Nguyên", "唐代", "Đường",
     "僕才能所至，言論著述，本之《書》以求其質，本之《詩》以求其恆，本之《禮》以求其宜，本之《春秋》以求其斷，本之《易》以求其動，此吾所以取於本者也。參之以太史公以暢其氣，參之以孟、荀以暢其博，參之以莊、老以肆其端。無妄引古以自託，無苟合世以取容。",
     "柳宗元論述自己汲取經典之寫作法則：本於詩書禮易春秋以立本，參以司馬遷以暢其氣，參以孟荀莊老以擴其博。不苟且迎合世俗。",
     "Root your writing in the Classics for substance, meter and judgment; expand with Sima Qian for vitality, and Zhuangzi and Mencius for breadth!",
     "柳宗元古文理論精華，系統總結博採先秦諸子與漢代史傳精華之創作方法，強調獨立人格與思想深度。",
     "【漢越音考證】韋 (Vi), 恆 (Hằng), 暢 (Sướng), 肆 (Tứ), 容 (Dung).",
     [{"viet": "Vô vọng dẫn cổ dĩ tự thác, vô cẩu hợp thế dĩ thủ dung.", "zh": "無妄引古以自託，無苟合世以取容。", "en": "Do not falsely cite antiquity for self-excuse, nor servilely flatter current fashion for favor.", "hanViet": "Vô cẩu hợp thế dĩ thủ dung"}]),

    (21, "v3", "r21_03_sushi_jiashuo", "蘇軾《稼說送張琥》", "Tô Thức - Giá Thuyết Tống Trương Hổ", "Su Shi: Essay on Farming Presented to Zhang Hu", "蘇軾", "Tô Thức", "北宋", "Bắc Tống",
     "博觀而約取，厚積而薄發，吾告子止於此矣。富人之稼也，田地美，食力足，所以養之者備，故其禾惠大而特別。今吾十口之家，而共百畝之田。日夜憂勤，全力治之，何患其不滋蔓耶！子之才，非特農夫之稼而已。勉之哉！",
     "蘇軾勉勵友人張琥：如農夫積肥耕耘，求學修身必須「博觀而約取，厚積而薄發」，經過深厚積累方能發揮巨大能量。",
     "Observe widely and extract the essence; accumulate richly and release with refined precision!",
     "千古座右銘「博觀而約取，厚積而薄發」，精闢揭示知識積累與學術成才之客觀規律。",
     "【漢越音考證】稼 (Giá), 琥 (Hổ), 博 (Bác), 約 (Ước), 蓄 (Súc), 厚 (Hậu).",
     [{"viet": "Bác quan nhi ước thủ, hậu tích nhi bạc phát.", "zh": "博觀而約取，厚積而薄發。", "en": "Observe extensively and choose with care; accumulate deeply and express with refined power.", "hanViet": "Bác quan nhi ước thủ hậu tích nhi bạc phát"}]),

    (21, "v3", "r21_04_luyou_donglai", "陸游《冬夜讀書示子聿》", "Lục Du - Đông Dạ Độc Thư Thị Tử Duật", "Lu You: Reading on a Winter Night for Son Yu", "陸游", "Lục Du", "南宋", "Nam Tống",
     "古人學問無遺力，少壯工夫老始成。紙上得來終覺淺，絕知此事要躬行。",
     "古人求學問總是全力以赴，年輕時下的苦功夫到老方能大成。僅僅從書本紙上得到的知識終究膚淺，若要透徹理解其中的真諦，必須親身躬行實踐。",
     "Ancient scholars spared no effort in learning; efforts begun in youth mature only in old age. What is gained on paper is shallow after all; to truly know, one must personally practice!",
     "南宋愛國大詩人陸游教子名詩，「紙上得來終覺淺，絕知此事要躬行」道破知行合一與實踐出真知之真諦。",
     "【漢越音考證】陸 (Lục), 游 (Du), 聿 (Duật), 遺 (Di), 躬 (Cung).",
     [{"viet": "Chỉ thượng đắc lai chung giác thiển, tuyệt tri thử sự yếu cung hành.", "zh": "紙上得來終覺淺，絕知此事要躬行。", "en": "Knowledge gained from paper is shallow after all; to truly comprehend a matter one must personally put it into practice.", "hanViet": "Chỉ thượng đắc lai chung giác thiển"}]),

    (21, "v3", "r21_05_zhuxi_guanshu", "朱熹《觀書有感二首·其一》", "Chu Hi - Quan Thư Hữu Cảm", "Zhu Xi: Impressions on Reading", "朱熹", "Chu Hi", "南宋", "Nam Tống",
     "半畝方塘一鑑開，天光雲影共徘徊。問渠那得清如許？為有源頭活水來。",
     "半畝大的方形池塘如明鏡般展現，天光與雲影在水面上悠然徘徊倒映。要問這池塘何以能如此澄澈清瑩？乃因有源頭活水源源不斷流淌而來！",
     "A half-acre pond opens like a mirror, where sky's light and clouds linger together. How does it remain so pure and clear? Because living fresh water flows from the source!",
     "理學宗師朱熹借方塘明鏡比喻心靈與讀書，唯有不斷吸收新知、求源頭活水，心靈才能常保澄明不滯。",
     "【漢越音考證】朱 (Chu), 熹 (Hi), 鑑 (Giám), 徊 (Hồi), 渠 (Cừ), 活 (Hoạt).",
     [{"viet": "Vấn cừ na đắc thanh như hứa? Vi hữu nguyên đầu hoạt thủy lai.", "zh": "問渠那得清如許？為有源頭活水來。", "en": "How can the pool remain so crystal clear? Because fresh living water comes flowing from the spring source.", "hanViet": "Vi hữu nguyên đầu hoạt thủy lai"}]),
]

print(f"Volume 3 items ready: {len(vol3_items)}")
